[2021-12-14 02:23:55,920] {taskinstance.py:1035} INFO - Dependencies all met for <TaskInstance: scraping_daft_clare.scrap_data scheduled__2021-12-13T00:45:00+00:00 [queued]>
[2021-12-14 02:23:55,982] {taskinstance.py:1035} INFO - Dependencies all met for <TaskInstance: scraping_daft_clare.scrap_data scheduled__2021-12-13T00:45:00+00:00 [queued]>
[2021-12-14 02:23:55,984] {taskinstance.py:1241} INFO - 
--------------------------------------------------------------------------------
[2021-12-14 02:23:55,985] {taskinstance.py:1242} INFO - Starting attempt 2 of 4
[2021-12-14 02:23:55,986] {taskinstance.py:1243} INFO - 
--------------------------------------------------------------------------------
[2021-12-14 02:23:56,057] {taskinstance.py:1262} INFO - Executing <Task(SparkSubmitOperator): scrap_data> on 2021-12-13 00:45:00+00:00
[2021-12-14 02:23:56,093] {standard_task_runner.py:76} INFO - Running: ['***', 'tasks', 'run', 'scraping_daft_clare', 'scrap_data', 'scheduled__2021-12-13T00:45:00+00:00', '--job-id', '2061', '--raw', '--subdir', 'DAGS_FOLDER/scraping_daft_clare.py', '--cfg-path', '/tmp/tmpq28rfau8', '--error-file', '/tmp/tmpjwqd6r2q']
[2021-12-14 02:23:56,102] {standard_task_runner.py:77} INFO - Job 2061: Subtask scrap_data
[2021-12-14 02:23:56,082] {standard_task_runner.py:52} INFO - Started process 31383 to run task
[2021-12-14 02:23:56,387] {logging_mixin.py:109} INFO - Running <TaskInstance: scraping_daft_clare.scrap_data scheduled__2021-12-13T00:45:00+00:00 [running]> on host c81f81825bc0
[2021-12-14 02:23:56,761] {taskinstance.py:1429} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_EMAIL=clement.liscoet@gmail.com
AIRFLOW_CTX_DAG_OWNER=clemoni
AIRFLOW_CTX_DAG_ID=scraping_daft_clare
AIRFLOW_CTX_TASK_ID=scrap_data
AIRFLOW_CTX_EXECUTION_DATE=2021-12-13T00:45:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2021-12-13T00:45:00+00:00
[2021-12-14 02:23:57,058] {base.py:79} INFO - Using connection to: id: spark_default. Host: spark://spark:7077, Port: None, Schema: , Login: ***, Password: ***, extra: {}
[2021-12-14 02:23:57,271] {spark_submit.py:360} INFO - Spark-Submit cmd: spark-submit --master spark://spark:7077 --conf spark.master=spark://spark:7077 --name scrap data --verbose /opt/***/jobs/get_ads_per_county.py clare
[2021-12-14 02:25:30,978] {spark_submit.py:514} INFO - Using properties file: null
[2021-12-14 02:25:33,040] {spark_submit.py:514} INFO - WARNING: An illegal reflective access operation has occurred
[2021-12-14 02:25:33,046] {spark_submit.py:514} INFO - WARNING: Illegal reflective access by org.apache.spark.unsafe.Platform (file:/home/***/.local/lib/python3.6/site-packages/pyspark/jars/spark-unsafe_2.12-3.2.0.jar) to constructor java.nio.DirectByteBuffer(long,int)
[2021-12-14 02:25:33,052] {spark_submit.py:514} INFO - WARNING: Please consider reporting this to the maintainers of org.apache.spark.unsafe.Platform
[2021-12-14 02:25:33,055] {spark_submit.py:514} INFO - WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
[2021-12-14 02:25:33,058] {spark_submit.py:514} INFO - WARNING: All illegal access operations will be denied in a future release
[2021-12-14 02:25:34,172] {spark_submit.py:514} INFO - Parsed arguments:
[2021-12-14 02:25:34,173] {spark_submit.py:514} INFO - master                  spark://spark:7077
[2021-12-14 02:25:34,174] {spark_submit.py:514} INFO - deployMode              null
[2021-12-14 02:25:34,175] {spark_submit.py:514} INFO - executorMemory          null
[2021-12-14 02:25:34,176] {spark_submit.py:514} INFO - executorCores           null
[2021-12-14 02:25:34,177] {spark_submit.py:514} INFO - totalExecutorCores      null
[2021-12-14 02:25:34,178] {spark_submit.py:514} INFO - propertiesFile          null
[2021-12-14 02:25:34,179] {spark_submit.py:514} INFO - driverMemory            null
[2021-12-14 02:25:34,180] {spark_submit.py:514} INFO - driverCores             null
[2021-12-14 02:25:34,181] {spark_submit.py:514} INFO - driverExtraClassPath    null
[2021-12-14 02:25:34,182] {spark_submit.py:514} INFO - driverExtraLibraryPath  null
[2021-12-14 02:25:34,184] {spark_submit.py:514} INFO - driverExtraJavaOptions  null
[2021-12-14 02:25:34,186] {spark_submit.py:514} INFO - supervise               false
[2021-12-14 02:25:34,187] {spark_submit.py:514} INFO - queue                   null
[2021-12-14 02:25:34,188] {spark_submit.py:514} INFO - numExecutors            null
[2021-12-14 02:25:34,189] {spark_submit.py:514} INFO - files                   null
[2021-12-14 02:25:34,190] {spark_submit.py:514} INFO - pyFiles                 null
[2021-12-14 02:25:34,191] {spark_submit.py:514} INFO - archives                null
[2021-12-14 02:25:34,193] {spark_submit.py:514} INFO - mainClass               null
[2021-12-14 02:25:34,193] {spark_submit.py:514} INFO - primaryResource         file:/opt/***/jobs/get_ads_per_county.py
[2021-12-14 02:25:34,194] {spark_submit.py:514} INFO - name                    scrap data
[2021-12-14 02:25:34,195] {spark_submit.py:514} INFO - childArgs               [clare]
[2021-12-14 02:25:34,196] {spark_submit.py:514} INFO - jars                    null
[2021-12-14 02:25:34,198] {spark_submit.py:514} INFO - packages                null
[2021-12-14 02:25:34,199] {spark_submit.py:514} INFO - packagesExclusions      null
[2021-12-14 02:25:34,200] {spark_submit.py:514} INFO - repositories            null
[2021-12-14 02:25:34,201] {spark_submit.py:514} INFO - verbose                 true
[2021-12-14 02:25:34,202] {spark_submit.py:514} INFO - 
[2021-12-14 02:25:34,203] {spark_submit.py:514} INFO - Spark properties used, including those specified through
[2021-12-14 02:25:34,204] {spark_submit.py:514} INFO - --conf and those from the properties file null:
[2021-12-14 02:25:34,205] {spark_submit.py:514} INFO - (spark.master,spark://spark:7077)
[2021-12-14 02:25:34,206] {spark_submit.py:514} INFO - 
[2021-12-14 02:25:34,207] {spark_submit.py:514} INFO - 
[2021-12-14 02:25:46,414] {spark_submit.py:514} INFO - Main class:
[2021-12-14 02:25:46,460] {spark_submit.py:514} INFO - org.apache.spark.deploy.PythonRunner
[2021-12-14 02:25:46,543] {spark_submit.py:514} INFO - Arguments:
[2021-12-14 02:25:46,553] {spark_submit.py:514} INFO - file:/opt/***/jobs/get_ads_per_county.py
[2021-12-14 02:25:46,565] {spark_submit.py:514} INFO - null
[2021-12-14 02:25:46,572] {spark_submit.py:514} INFO - clare
[2021-12-14 02:25:46,577] {spark_submit.py:514} INFO - --verbose
[2021-12-14 02:25:46,652] {spark_submit.py:514} INFO - Spark config:
[2021-12-14 02:25:46,666] {spark_submit.py:514} INFO - (spark.app.name,scrap data)
[2021-12-14 02:25:46,675] {spark_submit.py:514} INFO - (spark.master,spark://spark:7077)
[2021-12-14 02:25:46,680] {spark_submit.py:514} INFO - (spark.submit.pyFiles,)
[2021-12-14 02:25:46,687] {spark_submit.py:514} INFO - (spark.submit.deployMode,client)
[2021-12-14 02:25:46,709] {spark_submit.py:514} INFO - Classpath elements:
[2021-12-14 02:25:46,716] {spark_submit.py:514} INFO - 
[2021-12-14 02:25:46,725] {spark_submit.py:514} INFO - 
[2021-12-14 02:25:46,730] {spark_submit.py:514} INFO - 
[2021-12-14 02:56:17,897] {spark_submit.py:514} INFO - Using Spark's default log4j profile: org/apache/spark/log4j-defaults.properties
[2021-12-14 02:56:17,934] {spark_submit.py:514} INFO - 21/12/14 02:56:17 INFO SparkContext: Running Spark version 3.2.0
[2021-12-14 02:56:18,486] {spark_submit.py:514} INFO - 21/12/14 02:56:18 WARN NativeCodeLoader: Unable to load native-hadoop library for your platform... using builtin-java classes where applicable
[2021-12-14 02:56:23,443] {local_task_job.py:212} WARNING - State of this instance has been externally set to up_for_retry. Terminating instance.
[2021-12-14 02:56:23,578] {process_utils.py:100} INFO - Sending Signals.SIGTERM to GPID 31383
[2021-12-14 02:56:23,608] {taskinstance.py:1411} ERROR - Received SIGTERM. Terminating subprocesses.
[2021-12-14 02:56:23,643] {spark_submit.py:644} INFO - Sending kill signal to spark-submit
[2021-12-14 02:56:25,023] {process_utils.py:66} INFO - Process psutil.Process(pid=31758, status='terminated', started='02:25:48') (31758) terminated with exit code None
[2021-12-14 02:56:26,228] {taskinstance.py:1703} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 1332, in _run_raw_task
    self._execute_task_with_callbacks(context)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 1458, in _execute_task_with_callbacks
    result = self._execute_task(context, self.task)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 1514, in _execute_task
    result = execute_callable(context=context)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/providers/apache/spark/operators/spark_submit.py", line 179, in execute
    self._hook.submit(self._application)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/providers/apache/spark/hooks/spark_submit.py", line 433, in submit
    self._process_spark_submit_log(iter(self._submit_sp.stdout))  # type: ignore
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/providers/apache/spark/hooks/spark_submit.py", line 482, in _process_spark_submit_log
    for line in itr:
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 1413, in signal_handler
    raise AirflowException("Task received SIGTERM signal")
airflow.exceptions.AirflowException: Task received SIGTERM signal
[2021-12-14 02:56:26,959] {taskinstance.py:1280} INFO - Marking task as UP_FOR_RETRY. dag_id=scraping_daft_clare, task_id=scrap_data, execution_date=20211213T004500, start_date=20211214T022355, end_date=20211214T025626
[2021-12-14 02:56:27,939] {standard_task_runner.py:91} ERROR - Failed to execute job 2061 for task scrap_data
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/task/task_runner/standard_task_runner.py", line 85, in _start_by_fork
    args.func(args, dag=self.dag)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/cli/cli_parser.py", line 48, in command
    return func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/utils/cli.py", line 92, in wrapper
    return f(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/cli/commands/task_command.py", line 292, in task_run
    _run_task_by_selected_method(args, dag, ti)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/cli/commands/task_command.py", line 107, in _run_task_by_selected_method
    _run_raw_task(args, ti)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/cli/commands/task_command.py", line 184, in _run_raw_task
    error_file=args.error_file,
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/utils/session.py", line 70, in wrapper
    return func(*args, session=session, **kwargs)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 1332, in _run_raw_task
    self._execute_task_with_callbacks(context)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 1458, in _execute_task_with_callbacks
    result = self._execute_task(context, self.task)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 1514, in _execute_task
    result = execute_callable(context=context)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/providers/apache/spark/operators/spark_submit.py", line 179, in execute
    self._hook.submit(self._application)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/providers/apache/spark/hooks/spark_submit.py", line 433, in submit
    self._process_spark_submit_log(iter(self._submit_sp.stdout))  # type: ignore
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/providers/apache/spark/hooks/spark_submit.py", line 482, in _process_spark_submit_log
    for line in itr:
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 1413, in signal_handler
    raise AirflowException("Task received SIGTERM signal")
airflow.exceptions.AirflowException: Task received SIGTERM signal
[2021-12-14 02:56:28,278] {process_utils.py:66} INFO - Process psutil.Process(pid=31383, status='terminated', exitcode=1, started='02:23:55') (31383) terminated with exit code 1
[2021-12-14 02:56:28,294] {process_utils.py:66} INFO - Process psutil.Process(pid=31386, status='terminated', started='02:23:57') (31386) terminated with exit code None
