[2021-12-29 09:24:03,638] {taskinstance.py:1035} INFO - Dependencies all met for <TaskInstance: scraping_daft_clare.persist_data scheduled__2021-12-28T09:15:00+00:00 [queued]>
[2021-12-29 09:24:03,938] {taskinstance.py:1035} INFO - Dependencies all met for <TaskInstance: scraping_daft_clare.persist_data scheduled__2021-12-28T09:15:00+00:00 [queued]>
[2021-12-29 09:24:03,960] {taskinstance.py:1241} INFO - 
--------------------------------------------------------------------------------
[2021-12-29 09:24:03,968] {taskinstance.py:1242} INFO - Starting attempt 1 of 4
[2021-12-29 09:24:03,976] {taskinstance.py:1243} INFO - 
--------------------------------------------------------------------------------
[2021-12-29 09:24:04,513] {taskinstance.py:1262} INFO - Executing <Task(SparkSubmitOperator): persist_data> on 2021-12-28 09:15:00+00:00
[2021-12-29 09:24:04,968] {standard_task_runner.py:76} INFO - Running: ['***', 'tasks', 'run', 'scraping_daft_clare', 'persist_data', 'scheduled__2021-12-28T09:15:00+00:00', '--job-id', '5300', '--raw', '--subdir', 'DAGS_FOLDER/scraping_daft_clare.py', '--cfg-path', '/tmp/tmpnmat6w9j', '--error-file', '/tmp/tmpa7_x301a']
[2021-12-29 09:24:05,053] {standard_task_runner.py:77} INFO - Job 5300: Subtask persist_data
[2021-12-29 09:24:04,706] {standard_task_runner.py:52} INFO - Started process 23672 to run task
[2021-12-29 09:24:07,154] {logging_mixin.py:109} INFO - Running <TaskInstance: scraping_daft_clare.persist_data scheduled__2021-12-28T09:15:00+00:00 [running]> on host 6bdda4c19a85
[2021-12-29 09:24:10,732] {taskinstance.py:1429} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_EMAIL=clement.liscoet@gmail.com
AIRFLOW_CTX_DAG_OWNER=clemoni
AIRFLOW_CTX_DAG_ID=scraping_daft_clare
AIRFLOW_CTX_TASK_ID=persist_data
AIRFLOW_CTX_EXECUTION_DATE=2021-12-28T09:15:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2021-12-28T09:15:00+00:00
[2021-12-29 09:24:11,522] {base.py:79} INFO - Using connection to: id: spark_default. Host: spark://spark:7077, Port: None, Schema: , Login: ***, Password: ***, extra: {}
[2021-12-29 09:24:11,798] {spark_submit.py:360} INFO - Spark-Submit cmd: spark-submit --master spark://spark:7077 --conf spark.master=spark://spark:7077 --name persist data --verbose /opt/***/jobs/persist_db.py clare
[2021-12-29 09:25:38,920] {spark_submit.py:514} INFO - Using properties file: null
[2021-12-29 09:25:46,245] {spark_submit.py:514} INFO - WARNING: An illegal reflective access operation has occurred
[2021-12-29 09:25:46,267] {spark_submit.py:514} INFO - WARNING: Illegal reflective access by org.apache.spark.unsafe.Platform (file:/home/***/.local/lib/python3.6/site-packages/pyspark/jars/spark-unsafe_2.12-3.2.0.jar) to constructor java.nio.DirectByteBuffer(long,int)
[2021-12-29 09:25:46,277] {spark_submit.py:514} INFO - WARNING: Please consider reporting this to the maintainers of org.apache.spark.unsafe.Platform
[2021-12-29 09:25:46,299] {spark_submit.py:514} INFO - WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
[2021-12-29 09:25:46,321] {spark_submit.py:514} INFO - WARNING: All illegal access operations will be denied in a future release
[2021-12-29 09:25:50,092] {spark_submit.py:514} INFO - Parsed arguments:
[2021-12-29 09:25:50,102] {spark_submit.py:514} INFO - master                  spark://spark:7077
[2021-12-29 09:25:50,107] {spark_submit.py:514} INFO - deployMode              null
[2021-12-29 09:25:50,111] {spark_submit.py:514} INFO - executorMemory          null
[2021-12-29 09:25:50,119] {spark_submit.py:514} INFO - executorCores           null
[2021-12-29 09:25:50,124] {spark_submit.py:514} INFO - totalExecutorCores      null
[2021-12-29 09:25:50,134] {spark_submit.py:514} INFO - propertiesFile          null
[2021-12-29 09:25:50,138] {spark_submit.py:514} INFO - driverMemory            null
[2021-12-29 09:25:50,148] {spark_submit.py:514} INFO - driverCores             null
[2021-12-29 09:25:50,152] {spark_submit.py:514} INFO - driverExtraClassPath    null
[2021-12-29 09:25:50,162] {spark_submit.py:514} INFO - driverExtraLibraryPath  null
[2021-12-29 09:25:50,176] {spark_submit.py:514} INFO - driverExtraJavaOptions  null
[2021-12-29 09:25:50,186] {spark_submit.py:514} INFO - supervise               false
[2021-12-29 09:25:50,197] {spark_submit.py:514} INFO - queue                   null
[2021-12-29 09:25:50,212] {spark_submit.py:514} INFO - numExecutors            null
[2021-12-29 09:25:50,227] {spark_submit.py:514} INFO - files                   null
[2021-12-29 09:25:50,231] {spark_submit.py:514} INFO - pyFiles                 null
[2021-12-29 09:25:50,235] {spark_submit.py:514} INFO - archives                null
[2021-12-29 09:25:50,249] {spark_submit.py:514} INFO - mainClass               null
[2021-12-29 09:25:50,255] {spark_submit.py:514} INFO - primaryResource         file:/opt/***/jobs/persist_db.py
[2021-12-29 09:25:50,268] {spark_submit.py:514} INFO - name                    persist data
[2021-12-29 09:25:50,279] {spark_submit.py:514} INFO - childArgs               [clare]
[2021-12-29 09:25:50,295] {spark_submit.py:514} INFO - jars                    null
[2021-12-29 09:25:50,304] {spark_submit.py:514} INFO - packages                null
[2021-12-29 09:25:50,314] {spark_submit.py:514} INFO - packagesExclusions      null
[2021-12-29 09:25:50,335] {spark_submit.py:514} INFO - repositories            null
[2021-12-29 09:25:50,350] {spark_submit.py:514} INFO - verbose                 true
[2021-12-29 09:25:50,362] {spark_submit.py:514} INFO - 
[2021-12-29 09:25:50,372] {spark_submit.py:514} INFO - Spark properties used, including those specified through
[2021-12-29 09:25:50,387] {spark_submit.py:514} INFO - --conf and those from the properties file null:
[2021-12-29 09:25:50,402] {spark_submit.py:514} INFO - (spark.master,spark://spark:7077)
[2021-12-29 09:25:50,416] {spark_submit.py:514} INFO - 
[2021-12-29 09:25:50,432] {spark_submit.py:514} INFO - 
[2021-12-29 09:26:17,733] {spark_submit.py:514} INFO - Main class:
[2021-12-29 09:26:17,742] {spark_submit.py:514} INFO - org.apache.spark.deploy.PythonRunner
[2021-12-29 09:26:17,748] {spark_submit.py:514} INFO - Arguments:
[2021-12-29 09:26:17,757] {spark_submit.py:514} INFO - file:/opt/***/jobs/persist_db.py
[2021-12-29 09:26:17,762] {spark_submit.py:514} INFO - null
[2021-12-29 09:26:17,769] {spark_submit.py:514} INFO - clare
[2021-12-29 09:26:17,774] {spark_submit.py:514} INFO - --verbose
[2021-12-29 09:26:17,798] {spark_submit.py:514} INFO - Spark config:
[2021-12-29 09:26:17,806] {spark_submit.py:514} INFO - (spark.master,spark://spark:7077)
[2021-12-29 09:26:17,817] {spark_submit.py:514} INFO - (spark.app.name,persist data)
[2021-12-29 09:26:17,824] {spark_submit.py:514} INFO - (spark.submit.pyFiles,)
[2021-12-29 09:26:17,840] {spark_submit.py:514} INFO - (spark.submit.deployMode,client)
[2021-12-29 09:26:17,867] {spark_submit.py:514} INFO - Classpath elements:
[2021-12-29 09:26:17,878] {spark_submit.py:514} INFO - 
[2021-12-29 09:26:17,895] {spark_submit.py:514} INFO - 
[2021-12-29 09:26:17,900] {spark_submit.py:514} INFO - 
[2021-12-29 09:27:54,644] {spark_submit.py:514} INFO - Using Spark's default log4j profile: org/apache/spark/log4j-defaults.properties
[2021-12-29 09:27:55,652] {spark_submit.py:514} INFO - 21/12/29 09:27:55 INFO SparkContext: Running Spark version 3.2.0
[2021-12-29 09:28:04,250] {spark_submit.py:514} INFO - 21/12/29 09:28:04 WARN NativeCodeLoader: Unable to load native-hadoop library for your platform... using builtin-java classes where applicable
[2021-12-29 09:28:16,915] {spark_submit.py:514} INFO - 21/12/29 09:28:16 INFO ResourceUtils: ==============================================================
[2021-12-29 09:28:16,964] {spark_submit.py:514} INFO - 21/12/29 09:28:16 INFO ResourceUtils: No custom resources configured for spark.driver.
[2021-12-29 09:28:16,974] {spark_submit.py:514} INFO - 21/12/29 09:28:16 INFO ResourceUtils: ==============================================================
[2021-12-29 09:28:16,994] {spark_submit.py:514} INFO - 21/12/29 09:28:16 INFO SparkContext: Submitted application: Persist DB
[2021-12-29 09:28:18,485] {spark_submit.py:514} INFO - 21/12/29 09:28:18 INFO ResourceProfile: Default ResourceProfile created, executor resources: Map(cores -> name: cores, amount: 1, script: , vendor: , memory -> name: memory, amount: 1024, script: , vendor: , offHeap -> name: offHeap, amount: 0, script: , vendor: ), task resources: Map(cpus -> name: cpus, amount: 1.0)
[2021-12-29 09:28:19,907] {spark_submit.py:514} INFO - 21/12/29 09:28:19 INFO ResourceProfile: Limiting resource is cpu
[2021-12-29 09:28:19,965] {spark_submit.py:514} INFO - 21/12/29 09:28:19 INFO ResourceProfileManager: Added ResourceProfile id: 0
[2021-12-29 09:28:27,316] {spark_submit.py:514} INFO - 21/12/29 09:28:27 INFO SecurityManager: Changing view acls to: ***
[2021-12-29 09:28:27,394] {spark_submit.py:514} INFO - 21/12/29 09:28:27 INFO SecurityManager: Changing modify acls to: ***
[2021-12-29 09:28:27,445] {spark_submit.py:514} INFO - 21/12/29 09:28:27 INFO SecurityManager: Changing view acls groups to:
[2021-12-29 09:28:27,471] {spark_submit.py:514} INFO - 21/12/29 09:28:27 INFO SecurityManager: Changing modify acls groups to:
[2021-12-29 09:28:27,545] {spark_submit.py:514} INFO - 21/12/29 09:28:27 INFO SecurityManager: SecurityManager: authentication disabled; ui acls disabled; users  with view permissions: Set(***); groups with view permissions: Set(); users  with modify permissions: Set(***); groups with modify permissions: Set()
[2021-12-29 09:55:31,152] {spark_submit.py:514} INFO - 21/12/29 09:55:31 INFO Utils: Successfully started service 'sparkDriver' on port 42823.
[2021-12-29 09:55:33,937] {spark_submit.py:514} INFO - 21/12/29 09:55:33 INFO SparkEnv: Registering MapOutputTracker
[2021-12-29 09:55:37,640] {spark_submit.py:514} INFO - 21/12/29 09:55:37 INFO SparkEnv: Registering BlockManagerMaster
[2021-12-29 09:55:38,897] {spark_submit.py:514} INFO - 21/12/29 09:55:38 INFO BlockManagerMasterEndpoint: Using org.apache.spark.storage.DefaultTopologyMapper for getting topology information
[2021-12-29 09:55:38,914] {spark_submit.py:514} INFO - 21/12/29 09:55:38 INFO BlockManagerMasterEndpoint: BlockManagerMasterEndpoint up
[2021-12-29 09:55:38,964] {spark_submit.py:514} INFO - 21/12/29 09:55:38 INFO SparkEnv: Registering BlockManagerMasterHeartbeat
[2021-12-29 09:55:39,817] {spark_submit.py:514} INFO - 21/12/29 09:55:39 INFO DiskBlockManager: Created local directory at /tmp/blockmgr-66c4de72-4cc3-4f25-b500-a971b48b85a4
[2021-12-29 09:55:41,446] {spark_submit.py:514} INFO - 21/12/29 09:55:41 INFO MemoryStore: MemoryStore started with capacity 434.4 MiB
[2021-12-29 09:55:41,728] {spark_submit.py:514} INFO - 21/12/29 09:55:41 INFO SparkEnv: Registering OutputCommitCoordinator
[2021-12-29 09:55:59,599] {spark_submit.py:514} INFO - 21/12/29 09:55:59 WARN Utils: Service 'SparkUI' could not bind on port 4040. Attempting port 4041.
[2021-12-29 09:56:00,445] {spark_submit.py:514} INFO - 21/12/29 09:56:00 INFO Utils: Successfully started service 'SparkUI' on port 4041.
[2021-12-29 09:56:03,187] {spark_submit.py:514} INFO - 21/12/29 09:56:03 INFO SparkUI: Bound SparkUI to 0.0.0.0, and started at http://6bdda4c19a85:4041
[2021-12-29 11:40:03,610] {spark_submit.py:514} INFO - 21/12/29 11:39:58 WARN NettyRpcEnv: Ignored failure: java.util.concurrent.TimeoutException: Cannot receive any reply from 6bdda4c19a85:42823 in 120 seconds
[2021-12-29 11:53:58,474] {local_task_job.py:212} WARNING - State of this instance has been externally set to up_for_retry. Terminating instance.
[2021-12-29 11:53:59,632] {process_utils.py:100} INFO - Sending Signals.SIGTERM to GPID 23672
[2021-12-29 11:54:00,085] {taskinstance.py:1411} ERROR - Received SIGTERM. Terminating subprocesses.
[2021-12-29 11:54:00,980] {spark_submit.py:644} INFO - Sending kill signal to spark-submit
[2021-12-29 11:54:11,008] {taskinstance.py:1703} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 1332, in _run_raw_task
    self._execute_task_with_callbacks(context)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 1458, in _execute_task_with_callbacks
    result = self._execute_task(context, self.task)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 1514, in _execute_task
    result = execute_callable(context=context)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/providers/apache/spark/operators/spark_submit.py", line 179, in execute
    self._hook.submit(self._application)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/providers/apache/spark/hooks/spark_submit.py", line 433, in submit
    self._process_spark_submit_log(iter(self._submit_sp.stdout))  # type: ignore
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/providers/apache/spark/hooks/spark_submit.py", line 482, in _process_spark_submit_log
    for line in itr:
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 1413, in signal_handler
    raise AirflowException("Task received SIGTERM signal")
airflow.exceptions.AirflowException: Task received SIGTERM signal
[2021-12-29 11:54:12,847] {taskinstance.py:1280} INFO - Marking task as UP_FOR_RETRY. dag_id=scraping_daft_clare, task_id=persist_data, execution_date=20211228T091500, start_date=20211229T092403, end_date=20211229T115412
[2021-12-29 11:54:14,315] {process_utils.py:66} INFO - Process psutil.Process(pid=23923, status='terminated', started='09:26:24') (23923) terminated with exit code None
[2021-12-29 11:54:15,436] {standard_task_runner.py:91} ERROR - Failed to execute job 5300 for task persist_data
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/task/task_runner/standard_task_runner.py", line 85, in _start_by_fork
    args.func(args, dag=self.dag)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/cli/cli_parser.py", line 48, in command
    return func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/utils/cli.py", line 92, in wrapper
    return f(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/cli/commands/task_command.py", line 292, in task_run
    _run_task_by_selected_method(args, dag, ti)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/cli/commands/task_command.py", line 107, in _run_task_by_selected_method
    _run_raw_task(args, ti)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/cli/commands/task_command.py", line 184, in _run_raw_task
    error_file=args.error_file,
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/utils/session.py", line 70, in wrapper
    return func(*args, session=session, **kwargs)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 1332, in _run_raw_task
    self._execute_task_with_callbacks(context)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 1458, in _execute_task_with_callbacks
    result = self._execute_task(context, self.task)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 1514, in _execute_task
    result = execute_callable(context=context)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/providers/apache/spark/operators/spark_submit.py", line 179, in execute
    self._hook.submit(self._application)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/providers/apache/spark/hooks/spark_submit.py", line 433, in submit
    self._process_spark_submit_log(iter(self._submit_sp.stdout))  # type: ignore
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/providers/apache/spark/hooks/spark_submit.py", line 482, in _process_spark_submit_log
    for line in itr:
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 1413, in signal_handler
    raise AirflowException("Task received SIGTERM signal")
airflow.exceptions.AirflowException: Task received SIGTERM signal
[2021-12-29 11:54:16,073] {process_utils.py:66} INFO - Process psutil.Process(pid=23676, status='terminated', started='09:24:11') (23676) terminated with exit code None
[2021-12-29 11:54:16,161] {process_utils.py:66} INFO - Process psutil.Process(pid=23672, status='terminated', exitcode=1, started='09:24:03') (23672) terminated with exit code 1
