[2021-12-29 12:28:44,071] {taskinstance.py:1035} INFO - Dependencies all met for <TaskInstance: scraping_daft_sligo.scrap_data scheduled__2021-12-28T10:45:00+00:00 [queued]>
[2021-12-29 12:28:44,351] {taskinstance.py:1035} INFO - Dependencies all met for <TaskInstance: scraping_daft_sligo.scrap_data scheduled__2021-12-28T10:45:00+00:00 [queued]>
[2021-12-29 12:28:44,363] {taskinstance.py:1241} INFO - 
--------------------------------------------------------------------------------
[2021-12-29 12:28:44,384] {taskinstance.py:1242} INFO - Starting attempt 3 of 4
[2021-12-29 12:28:44,395] {taskinstance.py:1243} INFO - 
--------------------------------------------------------------------------------
[2021-12-29 12:28:45,547] {taskinstance.py:1262} INFO - Executing <Task(SparkSubmitOperator): scrap_data> on 2021-12-28 10:45:00+00:00
[2021-12-29 12:29:19,368] {standard_task_runner.py:52} INFO - Started process 33623 to run task
[2021-12-29 12:29:29,102] {standard_task_runner.py:76} INFO - Running: ['***', 'tasks', 'run', 'scraping_daft_sligo', 'scrap_data', 'scheduled__2021-12-28T10:45:00+00:00', '--job-id', '5381', '--raw', '--subdir', 'DAGS_FOLDER/scraping_daft_sligo.py', '--cfg-path', '/tmp/tmphk5ijv73', '--error-file', '/tmp/tmp8gxnhplw']
[2021-12-29 12:29:44,120] {standard_task_runner.py:77} INFO - Job 5381: Subtask scrap_data
[2021-12-29 12:47:37,994] {logging_mixin.py:109} INFO - Running <TaskInstance: scraping_daft_sligo.scrap_data scheduled__2021-12-28T10:45:00+00:00 [running]> on host 6bdda4c19a85
[2021-12-29 12:47:43,536] {taskinstance.py:1429} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_EMAIL=clement.liscoet@gmail.com
AIRFLOW_CTX_DAG_OWNER=clemoni
AIRFLOW_CTX_DAG_ID=scraping_daft_sligo
AIRFLOW_CTX_TASK_ID=scrap_data
AIRFLOW_CTX_EXECUTION_DATE=2021-12-28T10:45:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2021-12-28T10:45:00+00:00
[2021-12-29 12:47:44,538] {base.py:79} INFO - Using connection to: id: spark_default. Host: spark://spark:7077, Port: None, Schema: , Login: ***, Password: ***, extra: {}
[2021-12-29 12:47:44,771] {spark_submit.py:360} INFO - Spark-Submit cmd: spark-submit --master spark://spark:7077 --conf spark.master=spark://spark:7077 --name scrap data --verbose /opt/***/jobs/get_ads_per_county.py sligo
[2021-12-29 12:47:51,909] {local_task_job.py:212} WARNING - State of this instance has been externally set to up_for_retry. Terminating instance.
[2021-12-29 12:47:51,998] {process_utils.py:100} INFO - Sending Signals.SIGTERM to GPID 33623
[2021-12-29 12:47:52,024] {taskinstance.py:1411} ERROR - Received SIGTERM. Terminating subprocesses.
[2021-12-29 12:47:52,320] {process_utils.py:66} INFO - Process psutil.Process(pid=33635, status='terminated', started='12:30:17') (33635) terminated with exit code None
[2021-12-29 12:47:52,386] {process_utils.py:66} INFO - Process psutil.Process(pid=33641, status='terminated', started='12:30:20') (33641) terminated with exit code None
[2021-12-29 12:47:52,409] {process_utils.py:66} INFO - Process psutil.Process(pid=33640, status='terminated', started='12:30:20') (33640) terminated with exit code None
[2021-12-29 12:47:58,008] {taskinstance.py:1703} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 1332, in _run_raw_task
    self._execute_task_with_callbacks(context)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 1458, in _execute_task_with_callbacks
    result = self._execute_task(context, self.task)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 1514, in _execute_task
    result = execute_callable(context=context)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/providers/apache/spark/operators/spark_submit.py", line 179, in execute
    self._hook.submit(self._application)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/providers/apache/spark/hooks/spark_submit.py", line 433, in submit
    self._process_spark_submit_log(iter(self._submit_sp.stdout))  # type: ignore
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/providers/apache/spark/hooks/spark_submit.py", line 482, in _process_spark_submit_log
    for line in itr:
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 1413, in signal_handler
    raise AirflowException("Task received SIGTERM signal")
airflow.exceptions.AirflowException: Task received SIGTERM signal
[2021-12-29 12:47:58,311] {taskinstance.py:1280} INFO - Marking task as FAILED. dag_id=scraping_daft_sligo, task_id=scrap_data, execution_date=20211228T104500, start_date=20211229T122844, end_date=20211229T124758
[2021-12-29 12:47:59,915] {warnings.py:99} WARNING - /home/***/.local/lib/python3.6/site-packages/***/utils/email.py:102: PendingDeprecationWarning: Fetching SMTP credentials from configuration variables will be deprecated in a future release. Please set credentials using a connection instead.
  send_mime_email(e_from=smtp_mail_from, e_to=recipients, mime_msg=msg, conn_id=conn_id, dryrun=dryrun)

[2021-12-29 12:47:59,949] {email.py:208} INFO - Email alerting: attempt 1
[2021-12-29 12:48:01,907] {email.py:220} INFO - Sent an alert email to ['clement.liscoet@gmail.com']
[2021-12-29 12:48:06,521] {standard_task_runner.py:91} ERROR - Failed to execute job 5381 for task scrap_data
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/task/task_runner/standard_task_runner.py", line 85, in _start_by_fork
    args.func(args, dag=self.dag)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/cli/cli_parser.py", line 48, in command
    return func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/utils/cli.py", line 92, in wrapper
    return f(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/cli/commands/task_command.py", line 292, in task_run
    _run_task_by_selected_method(args, dag, ti)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/cli/commands/task_command.py", line 107, in _run_task_by_selected_method
    _run_raw_task(args, ti)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/cli/commands/task_command.py", line 184, in _run_raw_task
    error_file=args.error_file,
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/utils/session.py", line 70, in wrapper
    return func(*args, session=session, **kwargs)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 1332, in _run_raw_task
    self._execute_task_with_callbacks(context)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 1458, in _execute_task_with_callbacks
    result = self._execute_task(context, self.task)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 1514, in _execute_task
    result = execute_callable(context=context)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/providers/apache/spark/operators/spark_submit.py", line 179, in execute
    self._hook.submit(self._application)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/providers/apache/spark/hooks/spark_submit.py", line 433, in submit
    self._process_spark_submit_log(iter(self._submit_sp.stdout))  # type: ignore
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/providers/apache/spark/hooks/spark_submit.py", line 482, in _process_spark_submit_log
    for line in itr:
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 1413, in signal_handler
    raise AirflowException("Task received SIGTERM signal")
airflow.exceptions.AirflowException: Task received SIGTERM signal
[2021-12-29 12:48:08,767] {process_utils.py:66} INFO - Process psutil.Process(pid=33623, status='terminated', exitcode=1, started='12:29:18') (33623) terminated with exit code 1
