[2021-12-28 13:49:44,259] {taskinstance.py:1035} INFO - Dependencies all met for <TaskInstance: scraping_daft_leitrim.persist_data scheduled__2021-12-27T10:00:00+00:00 [queued]>
[2021-12-28 13:49:44,291] {taskinstance.py:1035} INFO - Dependencies all met for <TaskInstance: scraping_daft_leitrim.persist_data scheduled__2021-12-27T10:00:00+00:00 [queued]>
[2021-12-28 13:49:44,292] {taskinstance.py:1241} INFO - 
--------------------------------------------------------------------------------
[2021-12-28 13:49:44,293] {taskinstance.py:1242} INFO - Starting attempt 3 of 4
[2021-12-28 13:49:44,297] {taskinstance.py:1243} INFO - 
--------------------------------------------------------------------------------
[2021-12-28 13:49:44,332] {taskinstance.py:1262} INFO - Executing <Task(SparkSubmitOperator): persist_data> on 2021-12-27 10:00:00+00:00
[2021-12-28 13:49:44,341] {standard_task_runner.py:52} INFO - Started process 57413 to run task
[2021-12-28 13:49:44,382] {standard_task_runner.py:76} INFO - Running: ['***', 'tasks', 'run', 'scraping_daft_leitrim', 'persist_data', 'scheduled__2021-12-27T10:00:00+00:00', '--job-id', '5124', '--raw', '--subdir', 'DAGS_FOLDER/scraping_daft_leitrim.py', '--cfg-path', '/tmp/tmp3b4h12eu', '--error-file', '/tmp/tmpe_us2_3s']
[2021-12-28 13:49:44,383] {standard_task_runner.py:77} INFO - Job 5124: Subtask persist_data
[2021-12-28 13:49:44,540] {logging_mixin.py:109} INFO - Running <TaskInstance: scraping_daft_leitrim.persist_data scheduled__2021-12-27T10:00:00+00:00 [running]> on host 0c125a5bba95
[2021-12-28 13:49:44,769] {taskinstance.py:1429} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_EMAIL=clement.liscoet@gmail.com
AIRFLOW_CTX_DAG_OWNER=clemoni
AIRFLOW_CTX_DAG_ID=scraping_daft_leitrim
AIRFLOW_CTX_TASK_ID=persist_data
AIRFLOW_CTX_EXECUTION_DATE=2021-12-27T10:00:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2021-12-27T10:00:00+00:00
[2021-12-28 13:49:44,809] {base.py:79} INFO - Using connection to: id: spark_default. Host: spark://spark:7077, Port: None, Schema: , Login: ***, Password: ***, extra: {}
[2021-12-28 13:49:44,818] {spark_submit.py:360} INFO - Spark-Submit cmd: spark-submit --master spark://spark:7077 --conf spark.master=spark://spark:7077 --name persist data --verbose /opt/***/jobs/persist_db.py leitrim
[2021-12-28 13:49:48,635] {spark_submit.py:514} INFO - Using properties file: null
[2021-12-28 13:49:49,110] {spark_submit.py:514} INFO - WARNING: An illegal reflective access operation has occurred
[2021-12-28 13:49:49,112] {spark_submit.py:514} INFO - WARNING: Illegal reflective access by org.apache.spark.unsafe.Platform (file:/home/***/.local/lib/python3.6/site-packages/pyspark/jars/spark-unsafe_2.12-3.2.0.jar) to constructor java.nio.DirectByteBuffer(long,int)
[2021-12-28 13:49:49,113] {spark_submit.py:514} INFO - WARNING: Please consider reporting this to the maintainers of org.apache.spark.unsafe.Platform
[2021-12-28 13:49:49,113] {spark_submit.py:514} INFO - WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
[2021-12-28 13:49:49,114] {spark_submit.py:514} INFO - WARNING: All illegal access operations will be denied in a future release
[2021-12-28 13:49:49,204] {spark_submit.py:514} INFO - Parsed arguments:
[2021-12-28 13:49:49,205] {spark_submit.py:514} INFO - master                  spark://spark:7077
[2021-12-28 13:49:49,206] {spark_submit.py:514} INFO - deployMode              null
[2021-12-28 13:49:49,207] {spark_submit.py:514} INFO - executorMemory          null
[2021-12-28 13:49:49,208] {spark_submit.py:514} INFO - executorCores           null
[2021-12-28 13:49:49,209] {spark_submit.py:514} INFO - totalExecutorCores      null
[2021-12-28 13:49:49,210] {spark_submit.py:514} INFO - propertiesFile          null
[2021-12-28 13:49:49,211] {spark_submit.py:514} INFO - driverMemory            null
[2021-12-28 13:49:49,212] {spark_submit.py:514} INFO - driverCores             null
[2021-12-28 13:49:49,213] {spark_submit.py:514} INFO - driverExtraClassPath    null
[2021-12-28 13:49:49,214] {spark_submit.py:514} INFO - driverExtraLibraryPath  null
[2021-12-28 13:49:49,216] {spark_submit.py:514} INFO - driverExtraJavaOptions  null
[2021-12-28 13:49:49,216] {spark_submit.py:514} INFO - supervise               false
[2021-12-28 13:49:49,217] {spark_submit.py:514} INFO - queue                   null
[2021-12-28 13:49:49,218] {spark_submit.py:514} INFO - numExecutors            null
[2021-12-28 13:49:49,219] {spark_submit.py:514} INFO - files                   null
[2021-12-28 13:49:49,220] {spark_submit.py:514} INFO - pyFiles                 null
[2021-12-28 13:49:49,221] {spark_submit.py:514} INFO - archives                null
[2021-12-28 13:49:49,222] {spark_submit.py:514} INFO - mainClass               null
[2021-12-28 13:49:49,223] {spark_submit.py:514} INFO - primaryResource         file:/opt/***/jobs/persist_db.py
[2021-12-28 13:49:49,224] {spark_submit.py:514} INFO - name                    persist data
[2021-12-28 13:49:49,225] {spark_submit.py:514} INFO - childArgs               [leitrim]
[2021-12-28 13:49:49,226] {spark_submit.py:514} INFO - jars                    null
[2021-12-28 13:49:49,227] {spark_submit.py:514} INFO - packages                null
[2021-12-28 13:49:49,228] {spark_submit.py:514} INFO - packagesExclusions      null
[2021-12-28 13:49:49,229] {spark_submit.py:514} INFO - repositories            null
[2021-12-28 13:49:49,230] {spark_submit.py:514} INFO - verbose                 true
[2021-12-28 13:49:49,231] {spark_submit.py:514} INFO - 
[2021-12-28 13:49:49,232] {spark_submit.py:514} INFO - Spark properties used, including those specified through
[2021-12-28 13:49:49,233] {spark_submit.py:514} INFO - --conf and those from the properties file null:
[2021-12-28 13:49:49,233] {spark_submit.py:514} INFO - (spark.master,spark://spark:7077)
[2021-12-28 13:49:49,235] {spark_submit.py:514} INFO - 
[2021-12-28 13:49:49,236] {spark_submit.py:514} INFO - 
[2021-12-28 13:49:50,261] {spark_submit.py:514} INFO - Main class:
[2021-12-28 13:49:50,262] {spark_submit.py:514} INFO - org.apache.spark.deploy.PythonRunner
[2021-12-28 13:49:50,263] {spark_submit.py:514} INFO - Arguments:
[2021-12-28 13:49:50,264] {spark_submit.py:514} INFO - file:/opt/***/jobs/persist_db.py
[2021-12-28 13:49:50,265] {spark_submit.py:514} INFO - null
[2021-12-28 13:49:50,266] {spark_submit.py:514} INFO - leitrim
[2021-12-28 13:49:50,267] {spark_submit.py:514} INFO - --verbose
[2021-12-28 13:49:50,271] {spark_submit.py:514} INFO - Spark config:
[2021-12-28 13:49:50,272] {spark_submit.py:514} INFO - (spark.master,spark://spark:7077)
[2021-12-28 13:49:50,273] {spark_submit.py:514} INFO - (spark.app.name,persist data)
[2021-12-28 13:49:50,274] {spark_submit.py:514} INFO - (spark.submit.pyFiles,)
[2021-12-28 13:49:50,275] {spark_submit.py:514} INFO - (spark.submit.deployMode,client)
[2021-12-28 13:49:50,276] {spark_submit.py:514} INFO - Classpath elements:
[2021-12-28 13:49:50,277] {spark_submit.py:514} INFO - 
[2021-12-28 13:49:50,278] {spark_submit.py:514} INFO - 
[2021-12-28 13:49:50,279] {spark_submit.py:514} INFO - 
[2021-12-28 13:49:54,531] {spark_submit.py:514} INFO - Using Spark's default log4j profile: org/apache/spark/log4j-defaults.properties
[2021-12-28 13:49:54,593] {spark_submit.py:514} INFO - 21/12/28 13:49:54 INFO SparkContext: Running Spark version 3.2.0
[2021-12-28 13:49:55,436] {spark_submit.py:514} INFO - 21/12/28 13:49:55 WARN NativeCodeLoader: Unable to load native-hadoop library for your platform... using builtin-java classes where applicable
[2021-12-28 13:49:55,913] {spark_submit.py:514} INFO - 21/12/28 13:49:55 INFO ResourceUtils: ==============================================================
[2021-12-28 13:49:55,914] {spark_submit.py:514} INFO - 21/12/28 13:49:55 INFO ResourceUtils: No custom resources configured for spark.driver.
[2021-12-28 13:49:55,916] {spark_submit.py:514} INFO - 21/12/28 13:49:55 INFO ResourceUtils: ==============================================================
[2021-12-28 13:49:55,918] {spark_submit.py:514} INFO - 21/12/28 13:49:55 INFO SparkContext: Submitted application: Persist DB
[2021-12-28 13:49:56,034] {spark_submit.py:514} INFO - 21/12/28 13:49:56 INFO ResourceProfile: Default ResourceProfile created, executor resources: Map(cores -> name: cores, amount: 1, script: , vendor: , memory -> name: memory, amount: 1024, script: , vendor: , offHeap -> name: offHeap, amount: 0, script: , vendor: ), task resources: Map(cpus -> name: cpus, amount: 1.0)
[2021-12-28 13:49:56,071] {spark_submit.py:514} INFO - 21/12/28 13:49:56 INFO ResourceProfile: Limiting resource is cpu
[2021-12-28 13:49:56,074] {spark_submit.py:514} INFO - 21/12/28 13:49:56 INFO ResourceProfileManager: Added ResourceProfile id: 0
[2021-12-28 13:49:56,362] {spark_submit.py:514} INFO - 21/12/28 13:49:56 INFO SecurityManager: Changing view acls to: ***
[2021-12-28 13:49:56,364] {spark_submit.py:514} INFO - 21/12/28 13:49:56 INFO SecurityManager: Changing modify acls to: ***
[2021-12-28 13:49:56,366] {spark_submit.py:514} INFO - 21/12/28 13:49:56 INFO SecurityManager: Changing view acls groups to:
[2021-12-28 13:49:56,367] {spark_submit.py:514} INFO - 21/12/28 13:49:56 INFO SecurityManager: Changing modify acls groups to:
[2021-12-28 13:49:56,368] {spark_submit.py:514} INFO - 21/12/28 13:49:56 INFO SecurityManager: SecurityManager: authentication disabled; ui acls disabled; users  with view permissions: Set(***); groups with view permissions: Set(); users  with modify permissions: Set(***); groups with modify permissions: Set()
[2021-12-28 13:49:58,425] {spark_submit.py:514} INFO - 21/12/28 13:49:58 INFO Utils: Successfully started service 'sparkDriver' on port 41079.
[2021-12-28 13:49:58,593] {spark_submit.py:514} INFO - 21/12/28 13:49:58 INFO SparkEnv: Registering MapOutputTracker
[2021-12-28 13:49:58,711] {spark_submit.py:514} INFO - 21/12/28 13:49:58 INFO SparkEnv: Registering BlockManagerMaster
[2021-12-28 13:49:58,835] {spark_submit.py:514} INFO - 21/12/28 13:49:58 INFO BlockManagerMasterEndpoint: Using org.apache.spark.storage.DefaultTopologyMapper for getting topology information
[2021-12-28 13:49:58,840] {spark_submit.py:514} INFO - 21/12/28 13:49:58 INFO BlockManagerMasterEndpoint: BlockManagerMasterEndpoint up
[2021-12-28 13:49:58,874] {spark_submit.py:514} INFO - 21/12/28 13:49:58 INFO SparkEnv: Registering BlockManagerMasterHeartbeat
[2021-12-28 13:49:59,112] {spark_submit.py:514} INFO - 21/12/28 13:49:59 INFO DiskBlockManager: Created local directory at /tmp/blockmgr-acf75ed2-7858-46f3-be4c-8ea321dacb9a
[2021-12-28 13:49:59,181] {spark_submit.py:514} INFO - 21/12/28 13:49:59 INFO MemoryStore: MemoryStore started with capacity 434.4 MiB
[2021-12-28 13:49:59,242] {spark_submit.py:514} INFO - 21/12/28 13:49:59 INFO SparkEnv: Registering OutputCommitCoordinator
[2021-12-28 13:50:00,231] {spark_submit.py:514} INFO - 21/12/28 13:50:00 WARN Utils: Service 'SparkUI' could not bind on port 4040. Attempting port 4041.
[2021-12-28 13:50:00,233] {spark_submit.py:514} INFO - 21/12/28 13:50:00 WARN Utils: Service 'SparkUI' could not bind on port 4041. Attempting port 4042.
[2021-12-28 13:50:00,234] {spark_submit.py:514} INFO - 21/12/28 13:50:00 WARN Utils: Service 'SparkUI' could not bind on port 4042. Attempting port 4043.
[2021-12-28 13:50:00,236] {spark_submit.py:514} INFO - 21/12/28 13:50:00 WARN Utils: Service 'SparkUI' could not bind on port 4043. Attempting port 4044.
[2021-12-28 13:50:00,260] {spark_submit.py:514} INFO - 21/12/28 13:50:00 INFO Utils: Successfully started service 'SparkUI' on port 4044.
[2021-12-28 13:50:00,401] {spark_submit.py:514} INFO - 21/12/28 13:50:00 INFO SparkUI: Bound SparkUI to 0.0.0.0, and started at http://0c125a5bba95:4044
[2021-12-28 13:50:01,172] {spark_submit.py:514} INFO - 21/12/28 13:50:01 INFO StandaloneAppClient$ClientEndpoint: Connecting to master spark://spark:7077...
[2021-12-28 13:50:01,434] {spark_submit.py:514} INFO - 21/12/28 13:50:01 WARN StandaloneAppClient$ClientEndpoint: Failed to connect to master spark:7077
[2021-12-28 13:50:01,436] {spark_submit.py:514} INFO - org.apache.spark.SparkException: Exception thrown in awaitResult:
[2021-12-28 13:50:01,437] {spark_submit.py:514} INFO - at org.apache.spark.util.ThreadUtils$.awaitResult(ThreadUtils.scala:301)
[2021-12-28 13:50:01,439] {spark_submit.py:514} INFO - at org.apache.spark.rpc.RpcTimeout.awaitResult(RpcTimeout.scala:75)
[2021-12-28 13:50:01,440] {spark_submit.py:514} INFO - at org.apache.spark.rpc.RpcEnv.setupEndpointRefByURI(RpcEnv.scala:101)
[2021-12-28 13:50:01,441] {spark_submit.py:514} INFO - at org.apache.spark.rpc.RpcEnv.setupEndpointRef(RpcEnv.scala:109)
[2021-12-28 13:50:01,442] {spark_submit.py:514} INFO - at org.apache.spark.deploy.client.StandaloneAppClient$ClientEndpoint$$anon$1.run(StandaloneAppClient.scala:107)
[2021-12-28 13:50:01,444] {spark_submit.py:514} INFO - at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
[2021-12-28 13:50:01,445] {spark_submit.py:514} INFO - at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
[2021-12-28 13:50:01,446] {spark_submit.py:514} INFO - at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
[2021-12-28 13:50:01,447] {spark_submit.py:514} INFO - at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
[2021-12-28 13:50:01,448] {spark_submit.py:514} INFO - at java.base/java.lang.Thread.run(Thread.java:829)
[2021-12-28 13:50:01,449] {spark_submit.py:514} INFO - Caused by: java.io.IOException: Failed to connect to spark:7077
[2021-12-28 13:50:01,451] {spark_submit.py:514} INFO - at org.apache.spark.network.client.TransportClientFactory.createClient(TransportClientFactory.java:288)
[2021-12-28 13:50:01,452] {spark_submit.py:514} INFO - at org.apache.spark.network.client.TransportClientFactory.createClient(TransportClientFactory.java:218)
[2021-12-28 13:50:01,452] {spark_submit.py:514} INFO - at org.apache.spark.network.client.TransportClientFactory.createClient(TransportClientFactory.java:230)
[2021-12-28 13:50:01,453] {spark_submit.py:514} INFO - at org.apache.spark.rpc.netty.NettyRpcEnv.createClient(NettyRpcEnv.scala:204)
[2021-12-28 13:50:01,454] {spark_submit.py:514} INFO - at org.apache.spark.rpc.netty.Outbox$$anon$1.call(Outbox.scala:202)
[2021-12-28 13:50:01,455] {spark_submit.py:514} INFO - at org.apache.spark.rpc.netty.Outbox$$anon$1.call(Outbox.scala:198)
[2021-12-28 13:50:01,456] {spark_submit.py:514} INFO - ... 4 more
[2021-12-28 13:50:01,457] {spark_submit.py:514} INFO - Caused by: java.net.UnknownHostException: spark
[2021-12-28 13:50:01,458] {spark_submit.py:514} INFO - at java.base/java.net.InetAddress$CachedAddresses.get(InetAddress.java:797)
[2021-12-28 13:50:01,459] {spark_submit.py:514} INFO - at java.base/java.net.InetAddress.getAllByName0(InetAddress.java:1509)
[2021-12-28 13:50:01,460] {spark_submit.py:514} INFO - at java.base/java.net.InetAddress.getAllByName(InetAddress.java:1368)
[2021-12-28 13:50:01,460] {spark_submit.py:514} INFO - at java.base/java.net.InetAddress.getAllByName(InetAddress.java:1302)
[2021-12-28 13:50:01,461] {spark_submit.py:514} INFO - at java.base/java.net.InetAddress.getByName(InetAddress.java:1252)
[2021-12-28 13:50:01,462] {spark_submit.py:514} INFO - at io.netty.util.internal.SocketUtils$8.run(SocketUtils.java:156)
[2021-12-28 13:50:01,463] {spark_submit.py:514} INFO - at io.netty.util.internal.SocketUtils$8.run(SocketUtils.java:153)
[2021-12-28 13:50:01,464] {spark_submit.py:514} INFO - at java.base/java.security.AccessController.doPrivileged(Native Method)
[2021-12-28 13:50:01,465] {spark_submit.py:514} INFO - at io.netty.util.internal.SocketUtils.addressByName(SocketUtils.java:153)
[2021-12-28 13:50:01,466] {spark_submit.py:514} INFO - at io.netty.resolver.DefaultNameResolver.doResolve(DefaultNameResolver.java:41)
[2021-12-28 13:50:01,467] {spark_submit.py:514} INFO - at io.netty.resolver.SimpleNameResolver.resolve(SimpleNameResolver.java:61)
[2021-12-28 13:50:01,468] {spark_submit.py:514} INFO - at io.netty.resolver.SimpleNameResolver.resolve(SimpleNameResolver.java:53)
[2021-12-28 13:50:01,469] {spark_submit.py:514} INFO - at io.netty.resolver.InetSocketAddressResolver.doResolve(InetSocketAddressResolver.java:55)
[2021-12-28 13:50:01,470] {spark_submit.py:514} INFO - at io.netty.resolver.InetSocketAddressResolver.doResolve(InetSocketAddressResolver.java:31)
[2021-12-28 13:50:01,473] {spark_submit.py:514} INFO - at io.netty.resolver.AbstractAddressResolver.resolve(AbstractAddressResolver.java:106)
[2021-12-28 13:50:01,474] {spark_submit.py:514} INFO - at io.netty.bootstrap.Bootstrap.doResolveAndConnect0(Bootstrap.java:206)
[2021-12-28 13:50:01,476] {spark_submit.py:514} INFO - at io.netty.bootstrap.Bootstrap.access$000(Bootstrap.java:46)
[2021-12-28 13:50:01,477] {spark_submit.py:514} INFO - at io.netty.bootstrap.Bootstrap$1.operationComplete(Bootstrap.java:180)
[2021-12-28 13:50:01,478] {spark_submit.py:514} INFO - at io.netty.bootstrap.Bootstrap$1.operationComplete(Bootstrap.java:166)
[2021-12-28 13:50:01,479] {spark_submit.py:514} INFO - at io.netty.util.concurrent.DefaultPromise.notifyListener0(DefaultPromise.java:578)
[2021-12-28 13:50:01,480] {spark_submit.py:514} INFO - at io.netty.util.concurrent.DefaultPromise.notifyListenersNow(DefaultPromise.java:552)
[2021-12-28 13:50:01,481] {spark_submit.py:514} INFO - at io.netty.util.concurrent.DefaultPromise.notifyListeners(DefaultPromise.java:491)
[2021-12-28 13:50:01,482] {spark_submit.py:514} INFO - at io.netty.util.concurrent.DefaultPromise.setValue0(DefaultPromise.java:616)
[2021-12-28 13:50:01,483] {spark_submit.py:514} INFO - at io.netty.util.concurrent.DefaultPromise.setSuccess0(DefaultPromise.java:605)
[2021-12-28 13:50:01,484] {spark_submit.py:514} INFO - at io.netty.util.concurrent.DefaultPromise.trySuccess(DefaultPromise.java:104)
[2021-12-28 13:50:01,485] {spark_submit.py:514} INFO - at io.netty.channel.DefaultChannelPromise.trySuccess(DefaultChannelPromise.java:84)
[2021-12-28 13:50:01,486] {spark_submit.py:514} INFO - at io.netty.channel.AbstractChannel$AbstractUnsafe.safeSetSuccess(AbstractChannel.java:1008)
[2021-12-28 13:50:01,487] {spark_submit.py:514} INFO - at io.netty.channel.AbstractChannel$AbstractUnsafe.register0(AbstractChannel.java:516)
[2021-12-28 13:50:01,488] {spark_submit.py:514} INFO - at io.netty.channel.AbstractChannel$AbstractUnsafe.access$200(AbstractChannel.java:429)
[2021-12-28 13:50:01,489] {spark_submit.py:514} INFO - at io.netty.channel.AbstractChannel$AbstractUnsafe$1.run(AbstractChannel.java:486)
[2021-12-28 13:50:01,491] {spark_submit.py:514} INFO - at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:164)
[2021-12-28 13:50:01,492] {spark_submit.py:514} INFO - at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:469)
[2021-12-28 13:50:01,493] {spark_submit.py:514} INFO - at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:500)
[2021-12-28 13:50:01,493] {spark_submit.py:514} INFO - at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:986)
[2021-12-28 13:50:01,494] {spark_submit.py:514} INFO - at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
[2021-12-28 13:50:01,495] {spark_submit.py:514} INFO - at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
[2021-12-28 13:50:01,496] {spark_submit.py:514} INFO - ... 1 more
[2021-12-28 13:50:21,132] {spark_submit.py:514} INFO - 21/12/28 13:50:21 INFO StandaloneAppClient$ClientEndpoint: Connecting to master spark://spark:7077...
[2021-12-28 13:50:21,150] {spark_submit.py:514} INFO - 21/12/28 13:50:21 WARN StandaloneAppClient$ClientEndpoint: Failed to connect to master spark:7077
[2021-12-28 13:50:21,151] {spark_submit.py:514} INFO - org.apache.spark.SparkException: Exception thrown in awaitResult:
[2021-12-28 13:50:21,152] {spark_submit.py:514} INFO - at org.apache.spark.util.ThreadUtils$.awaitResult(ThreadUtils.scala:301)
[2021-12-28 13:50:21,153] {spark_submit.py:514} INFO - at org.apache.spark.rpc.RpcTimeout.awaitResult(RpcTimeout.scala:75)
[2021-12-28 13:50:21,154] {spark_submit.py:514} INFO - at org.apache.spark.rpc.RpcEnv.setupEndpointRefByURI(RpcEnv.scala:101)
[2021-12-28 13:50:21,155] {spark_submit.py:514} INFO - at org.apache.spark.rpc.RpcEnv.setupEndpointRef(RpcEnv.scala:109)
[2021-12-28 13:50:21,157] {spark_submit.py:514} INFO - at org.apache.spark.deploy.client.StandaloneAppClient$ClientEndpoint$$anon$1.run(StandaloneAppClient.scala:107)
[2021-12-28 13:50:21,158] {spark_submit.py:514} INFO - at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
[2021-12-28 13:50:21,158] {spark_submit.py:514} INFO - at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
[2021-12-28 13:50:21,159] {spark_submit.py:514} INFO - at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
[2021-12-28 13:50:21,160] {spark_submit.py:514} INFO - at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
[2021-12-28 13:50:21,161] {spark_submit.py:514} INFO - at java.base/java.lang.Thread.run(Thread.java:829)
[2021-12-28 13:50:21,162] {spark_submit.py:514} INFO - Caused by: java.io.IOException: Failed to connect to spark:7077
[2021-12-28 13:50:21,163] {spark_submit.py:514} INFO - at org.apache.spark.network.client.TransportClientFactory.createClient(TransportClientFactory.java:288)
[2021-12-28 13:50:21,164] {spark_submit.py:514} INFO - at org.apache.spark.network.client.TransportClientFactory.createClient(TransportClientFactory.java:218)
[2021-12-28 13:50:21,165] {spark_submit.py:514} INFO - at org.apache.spark.network.client.TransportClientFactory.createClient(TransportClientFactory.java:230)
[2021-12-28 13:50:21,166] {spark_submit.py:514} INFO - at org.apache.spark.rpc.netty.NettyRpcEnv.createClient(NettyRpcEnv.scala:204)
[2021-12-28 13:50:21,166] {spark_submit.py:514} INFO - at org.apache.spark.rpc.netty.Outbox$$anon$1.call(Outbox.scala:202)
[2021-12-28 13:50:21,167] {spark_submit.py:514} INFO - at org.apache.spark.rpc.netty.Outbox$$anon$1.call(Outbox.scala:198)
[2021-12-28 13:50:21,168] {spark_submit.py:514} INFO - ... 4 more
[2021-12-28 13:50:21,169] {spark_submit.py:514} INFO - Caused by: java.net.UnknownHostException: spark
[2021-12-28 13:50:21,170] {spark_submit.py:514} INFO - at java.base/java.net.InetAddress$CachedAddresses.get(InetAddress.java:797)
[2021-12-28 13:50:21,171] {spark_submit.py:514} INFO - at java.base/java.net.InetAddress.getAllByName0(InetAddress.java:1509)
[2021-12-28 13:50:21,172] {spark_submit.py:514} INFO - at java.base/java.net.InetAddress.getAllByName(InetAddress.java:1368)
[2021-12-28 13:50:21,172] {spark_submit.py:514} INFO - at java.base/java.net.InetAddress.getAllByName(InetAddress.java:1302)
[2021-12-28 13:50:21,173] {spark_submit.py:514} INFO - at java.base/java.net.InetAddress.getByName(InetAddress.java:1252)
[2021-12-28 13:50:21,174] {spark_submit.py:514} INFO - at io.netty.util.internal.SocketUtils$8.run(SocketUtils.java:156)
[2021-12-28 13:50:21,175] {spark_submit.py:514} INFO - at io.netty.util.internal.SocketUtils$8.run(SocketUtils.java:153)
[2021-12-28 13:50:21,176] {spark_submit.py:514} INFO - at java.base/java.security.AccessController.doPrivileged(Native Method)
[2021-12-28 13:50:21,177] {spark_submit.py:514} INFO - at io.netty.util.internal.SocketUtils.addressByName(SocketUtils.java:153)
[2021-12-28 13:50:21,178] {spark_submit.py:514} INFO - at io.netty.resolver.DefaultNameResolver.doResolve(DefaultNameResolver.java:41)
[2021-12-28 13:50:21,179] {spark_submit.py:514} INFO - at io.netty.resolver.SimpleNameResolver.resolve(SimpleNameResolver.java:61)
[2021-12-28 13:50:21,180] {spark_submit.py:514} INFO - at io.netty.resolver.SimpleNameResolver.resolve(SimpleNameResolver.java:53)
[2021-12-28 13:50:21,180] {spark_submit.py:514} INFO - at io.netty.resolver.InetSocketAddressResolver.doResolve(InetSocketAddressResolver.java:55)
[2021-12-28 13:50:21,181] {spark_submit.py:514} INFO - at io.netty.resolver.InetSocketAddressResolver.doResolve(InetSocketAddressResolver.java:31)
[2021-12-28 13:50:21,182] {spark_submit.py:514} INFO - at io.netty.resolver.AbstractAddressResolver.resolve(AbstractAddressResolver.java:106)
[2021-12-28 13:50:21,183] {spark_submit.py:514} INFO - at io.netty.bootstrap.Bootstrap.doResolveAndConnect0(Bootstrap.java:206)
[2021-12-28 13:50:21,185] {spark_submit.py:514} INFO - at io.netty.bootstrap.Bootstrap.access$000(Bootstrap.java:46)
[2021-12-28 13:50:21,186] {spark_submit.py:514} INFO - at io.netty.bootstrap.Bootstrap$1.operationComplete(Bootstrap.java:180)
[2021-12-28 13:50:21,188] {spark_submit.py:514} INFO - at io.netty.bootstrap.Bootstrap$1.operationComplete(Bootstrap.java:166)
[2021-12-28 13:50:21,191] {spark_submit.py:514} INFO - at io.netty.util.concurrent.DefaultPromise.notifyListener0(DefaultPromise.java:578)
[2021-12-28 13:50:21,193] {spark_submit.py:514} INFO - at io.netty.util.concurrent.DefaultPromise.notifyListenersNow(DefaultPromise.java:552)
[2021-12-28 13:50:21,196] {spark_submit.py:514} INFO - at io.netty.util.concurrent.DefaultPromise.notifyListeners(DefaultPromise.java:491)
[2021-12-28 13:50:21,199] {spark_submit.py:514} INFO - at io.netty.util.concurrent.DefaultPromise.setValue0(DefaultPromise.java:616)
[2021-12-28 13:50:21,201] {spark_submit.py:514} INFO - at io.netty.util.concurrent.DefaultPromise.setSuccess0(DefaultPromise.java:605)
[2021-12-28 13:50:21,203] {spark_submit.py:514} INFO - at io.netty.util.concurrent.DefaultPromise.trySuccess(DefaultPromise.java:104)
[2021-12-28 13:50:21,204] {spark_submit.py:514} INFO - at io.netty.channel.DefaultChannelPromise.trySuccess(DefaultChannelPromise.java:84)
[2021-12-28 13:50:21,205] {spark_submit.py:514} INFO - at io.netty.channel.AbstractChannel$AbstractUnsafe.safeSetSuccess(AbstractChannel.java:1008)
[2021-12-28 13:50:21,207] {spark_submit.py:514} INFO - at io.netty.channel.AbstractChannel$AbstractUnsafe.register0(AbstractChannel.java:516)
[2021-12-28 13:50:21,207] {spark_submit.py:514} INFO - at io.netty.channel.AbstractChannel$AbstractUnsafe.access$200(AbstractChannel.java:429)
[2021-12-28 13:50:21,208] {spark_submit.py:514} INFO - at io.netty.channel.AbstractChannel$AbstractUnsafe$1.run(AbstractChannel.java:486)
[2021-12-28 13:50:21,209] {spark_submit.py:514} INFO - at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:164)
[2021-12-28 13:50:21,210] {spark_submit.py:514} INFO - at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:469)
[2021-12-28 13:50:21,211] {spark_submit.py:514} INFO - at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:500)
[2021-12-28 13:50:21,212] {spark_submit.py:514} INFO - at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:986)
[2021-12-28 13:50:21,212] {spark_submit.py:514} INFO - at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
[2021-12-28 13:50:21,213] {spark_submit.py:514} INFO - at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
[2021-12-28 13:50:21,214] {spark_submit.py:514} INFO - ... 1 more
[2021-12-28 14:20:36,613] {spark_submit.py:514} INFO - 21/12/28 14:20:36 INFO StandaloneAppClient$ClientEndpoint: Connecting to master spark://spark:7077...
[2021-12-28 14:20:41,013] {spark_submit.py:514} INFO - 21/12/28 14:20:41 WARN TransportClientFactory: DNS resolution failed for spark:7077 took 3188 ms
[2021-12-28 14:20:57,637] {spark_submit.py:514} INFO - 21/12/28 14:20:57 WARN StandaloneSchedulerBackend: Application ID is not initialized yet.
[2021-12-28 14:20:59,047] {spark_submit.py:514} INFO - 21/12/28 14:20:57 ERROR StandaloneSchedulerBackend: Application has been killed. Reason: All masters are unresponsive! Giving up.
[2021-12-28 14:21:05,783] {spark_submit.py:514} INFO - 21/12/28 14:21:04 WARN StandaloneAppClient$ClientEndpoint: Failed to connect to master spark:7077
[2021-12-28 14:21:05,800] {spark_submit.py:514} INFO - org.apache.spark.SparkException: Exception thrown in awaitResult:
[2021-12-28 14:21:05,872] {spark_submit.py:514} INFO - at org.apache.spark.util.ThreadUtils$.awaitResult(ThreadUtils.scala:301)
[2021-12-28 14:21:05,995] {spark_submit.py:514} INFO - at org.apache.spark.rpc.RpcTimeout.awaitResult(RpcTimeout.scala:75)
[2021-12-28 14:21:06,314] {spark_submit.py:514} INFO - at org.apache.spark.rpc.RpcEnv.setupEndpointRefByURI(RpcEnv.scala:101)
[2021-12-28 14:21:06,626] {spark_submit.py:514} INFO - at org.apache.spark.rpc.RpcEnv.setupEndpointRef(RpcEnv.scala:109)
[2021-12-28 14:21:06,648] {spark_submit.py:514} INFO - at org.apache.spark.deploy.client.StandaloneAppClient$ClientEndpoint$$anon$1.run(StandaloneAppClient.scala:107)
[2021-12-28 14:21:06,666] {spark_submit.py:514} INFO - at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
[2021-12-28 14:21:06,694] {spark_submit.py:514} INFO - at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
[2021-12-28 14:21:06,708] {spark_submit.py:514} INFO - at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
[2021-12-28 14:21:06,730] {spark_submit.py:514} INFO - at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
[2021-12-28 14:21:06,753] {spark_submit.py:514} INFO - at java.base/java.lang.Thread.run(Thread.java:829)
[2021-12-28 14:21:06,764] {spark_submit.py:514} INFO - Caused by: java.io.IOException: Failed to connect to spark:7077
[2021-12-28 14:21:06,790] {spark_submit.py:514} INFO - at org.apache.spark.network.client.TransportClientFactory.createClient(TransportClientFactory.java:288)
[2021-12-28 14:21:06,893] {spark_submit.py:514} INFO - at org.apache.spark.network.client.TransportClientFactory.createClient(TransportClientFactory.java:218)
[2021-12-28 14:21:06,934] {spark_submit.py:514} INFO - at org.apache.spark.network.client.TransportClientFactory.createClient(TransportClientFactory.java:230)
[2021-12-28 14:21:06,960] {spark_submit.py:514} INFO - at org.apache.spark.rpc.netty.NettyRpcEnv.createClient(NettyRpcEnv.scala:204)
[2021-12-28 14:21:07,014] {spark_submit.py:514} INFO - at org.apache.spark.rpc.netty.Outbox$$anon$1.call(Outbox.scala:202)
[2021-12-28 14:21:07,035] {spark_submit.py:514} INFO - at org.apache.spark.rpc.netty.Outbox$$anon$1.call(Outbox.scala:198)
[2021-12-28 14:21:07,162] {spark_submit.py:514} INFO - ... 4 more
[2021-12-28 14:21:07,371] {spark_submit.py:514} INFO - Caused by: java.net.UnknownHostException: spark: Name or service not known
[2021-12-28 14:21:07,412] {spark_submit.py:514} INFO - at java.base/java.net.Inet4AddressImpl.lookupAllHostAddr(Native Method)
[2021-12-28 14:21:07,424] {spark_submit.py:514} INFO - at java.base/java.net.InetAddress$PlatformNameService.lookupAllHostAddr(InetAddress.java:929)
[2021-12-28 14:21:07,574] {spark_submit.py:514} INFO - at java.base/java.net.InetAddress.getAddressesFromNameService(InetAddress.java:1519)
[2021-12-28 14:21:07,614] {spark_submit.py:514} INFO - at java.base/java.net.InetAddress$NameServiceAddresses.get(InetAddress.java:848)
[2021-12-28 14:21:07,661] {spark_submit.py:514} INFO - at java.base/java.net.InetAddress.getAllByName0(InetAddress.java:1509)
[2021-12-28 14:21:07,749] {spark_submit.py:514} INFO - at java.base/java.net.InetAddress.getAllByName(InetAddress.java:1368)
[2021-12-28 14:21:07,782] {spark_submit.py:514} INFO - at java.base/java.net.InetAddress.getAllByName(InetAddress.java:1302)
[2021-12-28 14:21:07,845] {spark_submit.py:514} INFO - at java.base/java.net.InetAddress.getByName(InetAddress.java:1252)
[2021-12-28 14:21:07,977] {spark_submit.py:514} INFO - at io.netty.util.internal.SocketUtils$8.run(SocketUtils.java:156)
[2021-12-28 14:21:08,018] {spark_submit.py:514} INFO - at io.netty.util.internal.SocketUtils$8.run(SocketUtils.java:153)
[2021-12-28 14:21:08,436] {spark_submit.py:514} INFO - at java.base/java.security.AccessController.doPrivileged(Native Method)
[2021-12-28 14:21:08,848] {spark_submit.py:514} INFO - at io.netty.util.internal.SocketUtils.addressByName(SocketUtils.java:153)
[2021-12-28 14:21:09,039] {spark_submit.py:514} INFO - at io.netty.resolver.DefaultNameResolver.doResolve(DefaultNameResolver.java:41)
[2021-12-28 14:21:09,074] {spark_submit.py:514} INFO - at io.netty.resolver.SimpleNameResolver.resolve(SimpleNameResolver.java:61)
[2021-12-28 14:21:09,465] {spark_submit.py:514} INFO - at io.netty.resolver.SimpleNameResolver.resolve(SimpleNameResolver.java:53)
[2021-12-28 14:21:09,534] {spark_submit.py:514} INFO - at io.netty.resolver.InetSocketAddressResolver.doResolve(InetSocketAddressResolver.java:55)
[2021-12-28 14:21:09,545] {spark_submit.py:514} INFO - at io.netty.resolver.InetSocketAddressResolver.doResolve(InetSocketAddressResolver.java:31)
[2021-12-28 14:21:09,679] {spark_submit.py:514} INFO - at io.netty.resolver.AbstractAddressResolver.resolve(AbstractAddressResolver.java:106)
[2021-12-28 14:21:10,154] {spark_submit.py:514} INFO - at io.netty.bootstrap.Bootstrap.doResolveAndConnect0(Bootstrap.java:206)
[2021-12-28 14:21:10,169] {spark_submit.py:514} INFO - at io.netty.bootstrap.Bootstrap.access$000(Bootstrap.java:46)
[2021-12-28 14:21:10,281] {spark_submit.py:514} INFO - at io.netty.bootstrap.Bootstrap$1.operationComplete(Bootstrap.java:180)
[2021-12-28 14:21:10,324] {spark_submit.py:514} INFO - at io.netty.bootstrap.Bootstrap$1.operationComplete(Bootstrap.java:166)
[2021-12-28 14:21:10,380] {spark_submit.py:514} INFO - at io.netty.util.concurrent.DefaultPromise.notifyListener0(DefaultPromise.java:578)
[2021-12-28 14:21:10,407] {spark_submit.py:514} INFO - at io.netty.util.concurrent.DefaultPromise.notifyListenersNow(DefaultPromise.java:552)
[2021-12-28 14:21:10,447] {spark_submit.py:514} INFO - at io.netty.util.concurrent.DefaultPromise.notifyListeners(DefaultPromise.java:491)
[2021-12-28 14:21:10,461] {spark_submit.py:514} INFO - at io.netty.util.concurrent.DefaultPromise.setValue0(DefaultPromise.java:616)
[2021-12-28 14:21:10,472] {spark_submit.py:514} INFO - at io.netty.util.concurrent.DefaultPromise.setSuccess0(DefaultPromise.java:605)
[2021-12-28 14:21:10,504] {spark_submit.py:514} INFO - at io.netty.util.concurrent.DefaultPromise.trySuccess(DefaultPromise.java:104)
[2021-12-28 14:21:10,520] {spark_submit.py:514} INFO - at io.netty.channel.DefaultChannelPromise.trySuccess(DefaultChannelPromise.java:84)
[2021-12-28 14:21:10,588] {spark_submit.py:514} INFO - at io.netty.channel.AbstractChannel$AbstractUnsafe.safeSetSuccess(AbstractChannel.java:1008)
[2021-12-28 14:21:10,717] {spark_submit.py:514} INFO - at io.netty.channel.AbstractChannel$AbstractUnsafe.register0(AbstractChannel.java:516)
[2021-12-28 14:21:10,856] {spark_submit.py:514} INFO - at io.netty.channel.AbstractChannel$AbstractUnsafe.access$200(AbstractChannel.java:429)
[2021-12-28 14:21:11,017] {spark_submit.py:514} INFO - at io.netty.channel.AbstractChannel$AbstractUnsafe$1.run(AbstractChannel.java:486)
[2021-12-28 14:21:11,136] {spark_submit.py:514} INFO - at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:164)
[2021-12-28 14:21:11,144] {spark_submit.py:514} INFO - at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:469)
[2021-12-28 14:21:11,162] {spark_submit.py:514} INFO - at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:500)
[2021-12-28 14:21:11,175] {spark_submit.py:514} INFO - at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:986)
[2021-12-28 14:21:11,217] {spark_submit.py:514} INFO - at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
[2021-12-28 14:21:11,264] {spark_submit.py:514} INFO - at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
[2021-12-28 14:21:11,350] {spark_submit.py:514} INFO - ... 1 more
[2021-12-28 14:21:11,601] {spark_submit.py:514} INFO - 21/12/28 14:21:08 INFO Utils: Successfully started service 'org.apache.spark.network.netty.NettyBlockTransferService' on port 42827.
[2021-12-28 14:21:11,625] {spark_submit.py:514} INFO - 21/12/28 14:21:08 INFO NettyBlockTransferService: Server created on 0c125a5bba95:42827
[2021-12-28 14:21:11,759] {spark_submit.py:514} INFO - 21/12/28 14:21:08 INFO BlockManager: Using org.apache.spark.storage.RandomBlockReplicationPolicy for block replication policy
[2021-12-28 14:21:11,802] {spark_submit.py:514} INFO - 21/12/28 14:21:09 INFO SparkUI: Stopped Spark web UI at http://0c125a5bba95:4044
[2021-12-28 14:21:12,128] {spark_submit.py:514} INFO - 21/12/28 14:21:12 INFO BlockManagerMaster: Registering BlockManager BlockManagerId(driver, 0c125a5bba95, 42827, None)
[2021-12-28 14:21:14,415] {spark_submit.py:514} INFO - 21/12/28 14:21:14 INFO StandaloneSchedulerBackend: Shutting down all executors
[2021-12-28 14:21:14,906] {spark_submit.py:514} INFO - 21/12/28 14:21:14 INFO BlockManagerMasterEndpoint: Registering block manager 0c125a5bba95:42827 with 434.4 MiB RAM, BlockManagerId(driver, 0c125a5bba95, 42827, None)
[2021-12-28 14:21:15,087] {spark_submit.py:514} INFO - 21/12/28 14:21:15 INFO CoarseGrainedSchedulerBackend$DriverEndpoint: Asking each executor to shut down
[2021-12-28 14:21:15,669] {spark_submit.py:514} INFO - 21/12/28 14:21:15 INFO BlockManagerMaster: Registered BlockManager BlockManagerId(driver, 0c125a5bba95, 42827, None)
[2021-12-28 14:21:16,613] {spark_submit.py:514} INFO - 21/12/28 14:21:16 WARN StandaloneAppClient$ClientEndpoint: Drop UnregisterApplication(null) because has not yet connected to master
[2021-12-28 14:21:16,895] {spark_submit.py:514} INFO - 21/12/28 14:21:16 INFO BlockManager: Initialized BlockManager: BlockManagerId(driver, 0c125a5bba95, 42827, None)
[2021-12-28 14:21:20,551] {spark_submit.py:514} INFO - 21/12/28 14:21:20 INFO MapOutputTrackerMasterEndpoint: MapOutputTrackerMasterEndpoint stopped!
[2021-12-28 14:21:26,587] {spark_submit.py:514} INFO - 21/12/28 14:21:26 INFO MemoryStore: MemoryStore cleared
[2021-12-28 14:21:28,336] {spark_submit.py:514} INFO - 21/12/28 14:21:27 INFO BlockManager: BlockManager stopped
[2021-12-28 14:21:31,460] {spark_submit.py:514} INFO - 21/12/28 14:21:31 INFO BlockManagerMaster: BlockManagerMaster stopped
[2021-12-28 14:21:31,951] {spark_submit.py:514} INFO - 21/12/28 14:21:31 INFO OutputCommitCoordinator$OutputCommitCoordinatorEndpoint: OutputCommitCoordinator stopped!
[2021-12-28 14:21:35,682] {spark_submit.py:514} INFO - 21/12/28 14:21:35 INFO SparkContext: Successfully stopped SparkContext
[2021-12-28 14:22:14,946] {local_task_job.py:212} WARNING - State of this instance has been externally set to up_for_retry. Terminating instance.
[2021-12-28 14:22:15,706] {process_utils.py:100} INFO - Sending Signals.SIGTERM to GPID 57413
[2021-12-28 14:22:15,795] {taskinstance.py:1411} ERROR - Received SIGTERM. Terminating subprocesses.
[2021-12-28 14:22:18,267] {spark_submit.py:644} INFO - Sending kill signal to spark-submit
[2021-12-28 14:22:40,333] {process_utils.py:66} INFO - Process psutil.Process(pid=57689, status='terminated', started='13:49:50') (57689) terminated with exit code None
[2021-12-28 14:22:40,095] {taskinstance.py:1703} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 1332, in _run_raw_task
    self._execute_task_with_callbacks(context)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 1458, in _execute_task_with_callbacks
    result = self._execute_task(context, self.task)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 1514, in _execute_task
    result = execute_callable(context=context)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/providers/apache/spark/operators/spark_submit.py", line 179, in execute
    self._hook.submit(self._application)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/providers/apache/spark/hooks/spark_submit.py", line 433, in submit
    self._process_spark_submit_log(iter(self._submit_sp.stdout))  # type: ignore
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/providers/apache/spark/hooks/spark_submit.py", line 482, in _process_spark_submit_log
    for line in itr:
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 1413, in signal_handler
    raise AirflowException("Task received SIGTERM signal")
airflow.exceptions.AirflowException: Task received SIGTERM signal
[2021-12-28 14:22:42,906] {taskinstance.py:1280} INFO - Marking task as FAILED. dag_id=scraping_daft_leitrim, task_id=persist_data, execution_date=20211227T100000, start_date=20211228T134944, end_date=20211228T142242
[2021-12-28 14:22:46,023] {warnings.py:99} WARNING - /home/***/.local/lib/python3.6/site-packages/***/utils/email.py:102: PendingDeprecationWarning: Fetching SMTP credentials from configuration variables will be deprecated in a future release. Please set credentials using a connection instead.
  send_mime_email(e_from=smtp_mail_from, e_to=recipients, mime_msg=msg, conn_id=conn_id, dryrun=dryrun)

[2021-12-28 14:22:46,035] {email.py:208} INFO - Email alerting: attempt 1
[2021-12-28 14:22:46,843] {email.py:220} INFO - Sent an alert email to ['clement.liscoet@gmail.com']
[2021-12-28 14:22:50,210] {standard_task_runner.py:91} ERROR - Failed to execute job 5124 for task persist_data
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/task/task_runner/standard_task_runner.py", line 85, in _start_by_fork
    args.func(args, dag=self.dag)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/cli/cli_parser.py", line 48, in command
    return func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/utils/cli.py", line 92, in wrapper
    return f(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/cli/commands/task_command.py", line 292, in task_run
    _run_task_by_selected_method(args, dag, ti)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/cli/commands/task_command.py", line 107, in _run_task_by_selected_method
    _run_raw_task(args, ti)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/cli/commands/task_command.py", line 184, in _run_raw_task
    error_file=args.error_file,
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/utils/session.py", line 70, in wrapper
    return func(*args, session=session, **kwargs)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 1332, in _run_raw_task
    self._execute_task_with_callbacks(context)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 1458, in _execute_task_with_callbacks
    result = self._execute_task(context, self.task)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 1514, in _execute_task
    result = execute_callable(context=context)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/providers/apache/spark/operators/spark_submit.py", line 179, in execute
    self._hook.submit(self._application)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/providers/apache/spark/hooks/spark_submit.py", line 433, in submit
    self._process_spark_submit_log(iter(self._submit_sp.stdout))  # type: ignore
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/providers/apache/spark/hooks/spark_submit.py", line 482, in _process_spark_submit_log
    for line in itr:
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 1413, in signal_handler
    raise AirflowException("Task received SIGTERM signal")
airflow.exceptions.AirflowException: Task received SIGTERM signal
[2021-12-28 14:22:51,491] {process_utils.py:66} INFO - Process psutil.Process(pid=57413, status='terminated', exitcode=1, started='13:49:44') (57413) terminated with exit code 1
[2021-12-28 14:22:51,557] {process_utils.py:66} INFO - Process psutil.Process(pid=57439, status='terminated', started='13:49:44') (57439) terminated with exit code None
