[2021-12-29 11:57:23,071] {taskinstance.py:1035} INFO - Dependencies all met for <TaskInstance: scraping_daft_meath.scrap_data scheduled__2021-12-28T10:25:00+00:00 [queued]>
[2021-12-29 11:57:23,539] {taskinstance.py:1035} INFO - Dependencies all met for <TaskInstance: scraping_daft_meath.scrap_data scheduled__2021-12-28T10:25:00+00:00 [queued]>
[2021-12-29 11:57:23,543] {taskinstance.py:1241} INFO - 
--------------------------------------------------------------------------------
[2021-12-29 11:57:23,550] {taskinstance.py:1242} INFO - Starting attempt 1 of 4
[2021-12-29 11:57:23,552] {taskinstance.py:1243} INFO - 
--------------------------------------------------------------------------------
[2021-12-29 11:57:23,749] {taskinstance.py:1262} INFO - Executing <Task(SparkSubmitOperator): scrap_data> on 2021-12-28 10:25:00+00:00
[2021-12-29 11:57:24,153] {standard_task_runner.py:76} INFO - Running: ['***', 'tasks', 'run', 'scraping_daft_meath', 'scrap_data', 'scheduled__2021-12-28T10:25:00+00:00', '--job-id', '5325', '--raw', '--subdir', 'DAGS_FOLDER/scraping_daft_meath.py', '--cfg-path', '/tmp/tmp2jolmqmg', '--error-file', '/tmp/tmpd8l5brp6']
[2021-12-29 11:57:24,226] {standard_task_runner.py:77} INFO - Job 5325: Subtask scrap_data
[2021-12-29 11:57:24,052] {standard_task_runner.py:52} INFO - Started process 24616 to run task
[2021-12-29 11:57:27,927] {logging_mixin.py:109} INFO - Running <TaskInstance: scraping_daft_meath.scrap_data scheduled__2021-12-28T10:25:00+00:00 [running]> on host 6bdda4c19a85
[2021-12-29 11:57:30,269] {taskinstance.py:1429} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_EMAIL=clement.liscoet@gmail.com
AIRFLOW_CTX_DAG_OWNER=clemoni
AIRFLOW_CTX_DAG_ID=scraping_daft_meath
AIRFLOW_CTX_TASK_ID=scrap_data
AIRFLOW_CTX_EXECUTION_DATE=2021-12-28T10:25:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2021-12-28T10:25:00+00:00
[2021-12-29 11:57:30,536] {base.py:79} INFO - Using connection to: id: spark_default. Host: spark://spark:7077, Port: None, Schema: , Login: ***, Password: ***, extra: {}
[2021-12-29 11:57:30,636] {spark_submit.py:360} INFO - Spark-Submit cmd: spark-submit --master spark://spark:7077 --conf spark.master=spark://spark:7077 --name scrap data --verbose /opt/***/jobs/get_ads_per_county.py meath
[2021-12-29 11:59:51,892] {spark_submit.py:514} INFO - Using properties file: null
[2021-12-29 11:59:56,332] {spark_submit.py:514} INFO - WARNING: An illegal reflective access operation has occurred
[2021-12-29 11:59:56,333] {spark_submit.py:514} INFO - WARNING: Illegal reflective access by org.apache.spark.unsafe.Platform (file:/home/***/.local/lib/python3.6/site-packages/pyspark/jars/spark-unsafe_2.12-3.2.0.jar) to constructor java.nio.DirectByteBuffer(long,int)
[2021-12-29 11:59:56,335] {spark_submit.py:514} INFO - WARNING: Please consider reporting this to the maintainers of org.apache.spark.unsafe.Platform
[2021-12-29 11:59:56,336] {spark_submit.py:514} INFO - WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
[2021-12-29 11:59:56,359] {spark_submit.py:514} INFO - WARNING: All illegal access operations will be denied in a future release
[2021-12-29 11:59:57,964] {spark_submit.py:514} INFO - Parsed arguments:
[2021-12-29 11:59:57,966] {spark_submit.py:514} INFO - master                  spark://spark:7077
[2021-12-29 11:59:57,967] {spark_submit.py:514} INFO - deployMode              null
[2021-12-29 11:59:57,968] {spark_submit.py:514} INFO - executorMemory          null
[2021-12-29 11:59:57,969] {spark_submit.py:514} INFO - executorCores           null
[2021-12-29 11:59:57,971] {spark_submit.py:514} INFO - totalExecutorCores      null
[2021-12-29 11:59:57,972] {spark_submit.py:514} INFO - propertiesFile          null
[2021-12-29 11:59:57,973] {spark_submit.py:514} INFO - driverMemory            null
[2021-12-29 11:59:57,974] {spark_submit.py:514} INFO - driverCores             null
[2021-12-29 11:59:57,975] {spark_submit.py:514} INFO - driverExtraClassPath    null
[2021-12-29 11:59:57,979] {spark_submit.py:514} INFO - driverExtraLibraryPath  null
[2021-12-29 11:59:57,982] {spark_submit.py:514} INFO - driverExtraJavaOptions  null
[2021-12-29 11:59:57,984] {spark_submit.py:514} INFO - supervise               false
[2021-12-29 11:59:57,985] {spark_submit.py:514} INFO - queue                   null
[2021-12-29 11:59:57,987] {spark_submit.py:514} INFO - numExecutors            null
[2021-12-29 11:59:57,989] {spark_submit.py:514} INFO - files                   null
[2021-12-29 11:59:57,990] {spark_submit.py:514} INFO - pyFiles                 null
[2021-12-29 11:59:57,992] {spark_submit.py:514} INFO - archives                null
[2021-12-29 11:59:57,996] {spark_submit.py:514} INFO - mainClass               null
[2021-12-29 11:59:57,998] {spark_submit.py:514} INFO - primaryResource         file:/opt/***/jobs/get_ads_per_county.py
[2021-12-29 11:59:57,999] {spark_submit.py:514} INFO - name                    scrap data
[2021-12-29 11:59:58,000] {spark_submit.py:514} INFO - childArgs               [meath]
[2021-12-29 11:59:58,002] {spark_submit.py:514} INFO - jars                    null
[2021-12-29 11:59:58,005] {spark_submit.py:514} INFO - packages                null
[2021-12-29 11:59:58,007] {spark_submit.py:514} INFO - packagesExclusions      null
[2021-12-29 11:59:58,009] {spark_submit.py:514} INFO - repositories            null
[2021-12-29 11:59:58,011] {spark_submit.py:514} INFO - verbose                 true
[2021-12-29 11:59:58,026] {spark_submit.py:514} INFO - 
[2021-12-29 11:59:58,030] {spark_submit.py:514} INFO - Spark properties used, including those specified through
[2021-12-29 11:59:58,031] {spark_submit.py:514} INFO - --conf and those from the properties file null:
[2021-12-29 11:59:58,044] {spark_submit.py:514} INFO - (spark.master,spark://spark:7077)
[2021-12-29 11:59:58,052] {spark_submit.py:514} INFO - 
[2021-12-29 11:59:58,065] {spark_submit.py:514} INFO - 
[2021-12-29 12:00:03,513] {spark_submit.py:514} INFO - Main class:
[2021-12-29 12:00:03,520] {spark_submit.py:514} INFO - org.apache.spark.deploy.PythonRunner
[2021-12-29 12:00:03,530] {spark_submit.py:514} INFO - Arguments:
[2021-12-29 12:00:03,533] {spark_submit.py:514} INFO - file:/opt/***/jobs/get_ads_per_county.py
[2021-12-29 12:00:03,538] {spark_submit.py:514} INFO - null
[2021-12-29 12:00:03,546] {spark_submit.py:514} INFO - meath
[2021-12-29 12:00:03,552] {spark_submit.py:514} INFO - --verbose
[2021-12-29 12:00:03,589] {spark_submit.py:514} INFO - Spark config:
[2021-12-29 12:00:03,599] {spark_submit.py:514} INFO - (spark.app.name,scrap data)
[2021-12-29 12:00:03,602] {spark_submit.py:514} INFO - (spark.master,spark://spark:7077)
[2021-12-29 12:00:03,610] {spark_submit.py:514} INFO - (spark.submit.pyFiles,)
[2021-12-29 12:00:03,614] {spark_submit.py:514} INFO - (spark.submit.deployMode,client)
[2021-12-29 12:00:03,618] {spark_submit.py:514} INFO - Classpath elements:
[2021-12-29 12:00:03,621] {spark_submit.py:514} INFO - 
[2021-12-29 12:00:03,623] {spark_submit.py:514} INFO - 
[2021-12-29 12:00:03,625] {spark_submit.py:514} INFO - 
[2021-12-29 12:00:17,691] {spark_submit.py:514} INFO - Using Spark's default log4j profile: org/apache/spark/log4j-defaults.properties
[2021-12-29 12:00:17,758] {spark_submit.py:514} INFO - 21/12/29 12:00:17 INFO SparkContext: Running Spark version 3.2.0
[2021-12-29 12:00:19,022] {spark_submit.py:514} INFO - 21/12/29 12:00:19 WARN NativeCodeLoader: Unable to load native-hadoop library for your platform... using builtin-java classes where applicable
[2021-12-29 12:00:22,873] {spark_submit.py:514} INFO - 21/12/29 12:00:22 INFO ResourceUtils: ==============================================================
[2021-12-29 12:00:22,878] {spark_submit.py:514} INFO - 21/12/29 12:00:22 INFO ResourceUtils: No custom resources configured for spark.driver.
[2021-12-29 12:00:22,889] {spark_submit.py:514} INFO - 21/12/29 12:00:22 INFO ResourceUtils: ==============================================================
[2021-12-29 12:00:22,897] {spark_submit.py:514} INFO - 21/12/29 12:00:22 INFO SparkContext: Submitted application: Get Ads per county
[2021-12-29 12:00:23,412] {spark_submit.py:514} INFO - 21/12/29 12:00:23 INFO ResourceProfile: Default ResourceProfile created, executor resources: Map(cores -> name: cores, amount: 1, script: , vendor: , memory -> name: memory, amount: 1024, script: , vendor: , offHeap -> name: offHeap, amount: 0, script: , vendor: ), task resources: Map(cpus -> name: cpus, amount: 1.0)
[2021-12-29 12:00:23,830] {spark_submit.py:514} INFO - 21/12/29 12:00:23 INFO ResourceProfile: Limiting resource is cpu
[2021-12-29 12:00:23,872] {spark_submit.py:514} INFO - 21/12/29 12:00:23 INFO ResourceProfileManager: Added ResourceProfile id: 0
[2021-12-29 12:00:25,745] {spark_submit.py:514} INFO - 21/12/29 12:00:25 INFO SecurityManager: Changing view acls to: ***
[2021-12-29 12:00:25,789] {spark_submit.py:514} INFO - 21/12/29 12:00:25 INFO SecurityManager: Changing modify acls to: ***
[2021-12-29 12:00:25,797] {spark_submit.py:514} INFO - 21/12/29 12:00:25 INFO SecurityManager: Changing view acls groups to:
[2021-12-29 12:00:25,815] {spark_submit.py:514} INFO - 21/12/29 12:00:25 INFO SecurityManager: Changing modify acls groups to:
[2021-12-29 12:00:25,824] {spark_submit.py:514} INFO - 21/12/29 12:00:25 INFO SecurityManager: SecurityManager: authentication disabled; ui acls disabled; users  with view permissions: Set(***); groups with view permissions: Set(); users  with modify permissions: Set(***); groups with modify permissions: Set()
[2021-12-29 12:00:34,707] {spark_submit.py:514} INFO - 21/12/29 12:00:34 INFO Utils: Successfully started service 'sparkDriver' on port 42195.
[2021-12-29 12:00:36,662] {spark_submit.py:514} INFO - 21/12/29 12:00:36 INFO SparkEnv: Registering MapOutputTracker
[2021-12-29 12:00:38,225] {spark_submit.py:514} INFO - 21/12/29 12:00:38 INFO SparkEnv: Registering BlockManagerMaster
[2021-12-29 12:00:39,281] {spark_submit.py:514} INFO - 21/12/29 12:00:39 INFO BlockManagerMasterEndpoint: Using org.apache.spark.storage.DefaultTopologyMapper for getting topology information
[2021-12-29 12:00:39,284] {spark_submit.py:514} INFO - 21/12/29 12:00:39 INFO BlockManagerMasterEndpoint: BlockManagerMasterEndpoint up
[2021-12-29 12:00:39,427] {spark_submit.py:514} INFO - 21/12/29 12:00:39 INFO SparkEnv: Registering BlockManagerMasterHeartbeat
[2021-12-29 12:00:40,382] {spark_submit.py:514} INFO - 21/12/29 12:00:40 INFO DiskBlockManager: Created local directory at /tmp/blockmgr-055642e6-4464-4676-8eab-f4cbe8c396ee
[2021-12-29 12:00:40,826] {spark_submit.py:514} INFO - 21/12/29 12:00:40 INFO MemoryStore: MemoryStore started with capacity 434.4 MiB
[2021-12-29 12:00:41,464] {spark_submit.py:514} INFO - 21/12/29 12:00:41 INFO SparkEnv: Registering OutputCommitCoordinator
[2021-12-29 12:01:16,638] {spark_submit.py:514} INFO - 21/12/29 12:01:16 WARN Utils: Service 'SparkUI' could not bind on port 4040. Attempting port 4041.
[2021-12-29 12:01:16,681] {spark_submit.py:514} INFO - 21/12/29 12:01:16 WARN Utils: Service 'SparkUI' could not bind on port 4041. Attempting port 4042.
[2021-12-29 12:01:16,703] {spark_submit.py:514} INFO - 21/12/29 12:01:16 WARN Utils: Service 'SparkUI' could not bind on port 4042. Attempting port 4043.
[2021-12-29 12:01:16,730] {spark_submit.py:514} INFO - 21/12/29 12:01:16 WARN Utils: Service 'SparkUI' could not bind on port 4043. Attempting port 4044.
[2021-12-29 12:01:16,740] {spark_submit.py:514} INFO - 21/12/29 12:01:16 WARN Utils: Service 'SparkUI' could not bind on port 4044. Attempting port 4045.
[2021-12-29 12:01:16,757] {spark_submit.py:514} INFO - 21/12/29 12:01:16 WARN Utils: Service 'SparkUI' could not bind on port 4045. Attempting port 4046.
[2021-12-29 12:01:16,784] {spark_submit.py:514} INFO - 21/12/29 12:01:16 WARN Utils: Service 'SparkUI' could not bind on port 4046. Attempting port 4047.
[2021-12-29 12:01:16,795] {spark_submit.py:514} INFO - 21/12/29 12:01:16 WARN Utils: Service 'SparkUI' could not bind on port 4047. Attempting port 4048.
[2021-12-29 12:01:16,805] {spark_submit.py:514} INFO - 21/12/29 12:01:16 WARN Utils: Service 'SparkUI' could not bind on port 4048. Attempting port 4049.
[2021-12-29 12:01:16,812] {spark_submit.py:514} INFO - 21/12/29 12:01:16 WARN Utils: Service 'SparkUI' could not bind on port 4049. Attempting port 4050.
[2021-12-29 12:01:16,822] {spark_submit.py:514} INFO - 21/12/29 12:01:16 WARN Utils: Service 'SparkUI' could not bind on port 4050. Attempting port 4051.
[2021-12-29 12:01:16,835] {spark_submit.py:514} INFO - 21/12/29 12:01:16 WARN Utils: Service 'SparkUI' could not bind on port 4051. Attempting port 4052.
[2021-12-29 12:01:16,887] {spark_submit.py:514} INFO - 21/12/29 12:01:16 WARN Utils: Service 'SparkUI' could not bind on port 4052. Attempting port 4053.
[2021-12-29 12:01:16,913] {spark_submit.py:514} INFO - 21/12/29 12:01:16 WARN Utils: Service 'SparkUI' could not bind on port 4053. Attempting port 4054.
[2021-12-29 12:01:17,283] {spark_submit.py:514} INFO - 21/12/29 12:01:17 INFO Utils: Successfully started service 'SparkUI' on port 4054.
[2021-12-29 12:01:22,199] {spark_submit.py:514} INFO - 21/12/29 12:01:22 INFO SparkUI: Bound SparkUI to 0.0.0.0, and started at http://6bdda4c19a85:4054
[2021-12-29 12:02:15,713] {spark_submit.py:514} INFO - 21/12/29 12:02:15 INFO StandaloneAppClient$ClientEndpoint: Connecting to master spark://spark:7077...
[2021-12-29 12:02:37,526] {spark_submit.py:514} INFO - 21/12/29 12:02:37 INFO StandaloneAppClient$ClientEndpoint: Connecting to master spark://spark:7077...
[2021-12-29 12:02:38,774] {spark_submit.py:514} INFO - 21/12/29 12:02:38 WARN StandaloneAppClient$ClientEndpoint: Failed to connect to master spark:7077
[2021-12-29 12:02:38,776] {spark_submit.py:514} INFO - org.apache.spark.SparkException: Exception thrown in awaitResult:
[2021-12-29 12:02:38,777] {spark_submit.py:514} INFO - at org.apache.spark.util.ThreadUtils$.awaitResult(ThreadUtils.scala:301)
[2021-12-29 12:02:38,784] {spark_submit.py:514} INFO - at org.apache.spark.rpc.RpcTimeout.awaitResult(RpcTimeout.scala:75)
[2021-12-29 12:02:38,789] {spark_submit.py:514} INFO - at org.apache.spark.rpc.RpcEnv.setupEndpointRefByURI(RpcEnv.scala:101)
[2021-12-29 12:02:38,792] {spark_submit.py:514} INFO - at org.apache.spark.rpc.RpcEnv.setupEndpointRef(RpcEnv.scala:109)
[2021-12-29 12:02:38,793] {spark_submit.py:514} INFO - at org.apache.spark.deploy.client.StandaloneAppClient$ClientEndpoint$$anon$1.run(StandaloneAppClient.scala:107)
[2021-12-29 12:02:38,806] {spark_submit.py:514} INFO - at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
[2021-12-29 12:02:38,808] {spark_submit.py:514} INFO - at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
[2021-12-29 12:02:38,810] {spark_submit.py:514} INFO - at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
[2021-12-29 12:02:38,812] {spark_submit.py:514} INFO - at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
[2021-12-29 12:02:38,813] {spark_submit.py:514} INFO - at java.base/java.lang.Thread.run(Thread.java:829)
[2021-12-29 12:02:38,814] {spark_submit.py:514} INFO - Caused by: java.io.IOException: Failed to connect to spark:7077
[2021-12-29 12:02:38,816] {spark_submit.py:514} INFO - at org.apache.spark.network.client.TransportClientFactory.createClient(TransportClientFactory.java:288)
[2021-12-29 12:02:38,818] {spark_submit.py:514} INFO - at org.apache.spark.network.client.TransportClientFactory.createClient(TransportClientFactory.java:218)
[2021-12-29 12:02:38,824] {spark_submit.py:514} INFO - at org.apache.spark.network.client.TransportClientFactory.createClient(TransportClientFactory.java:230)
[2021-12-29 12:02:38,826] {spark_submit.py:514} INFO - at org.apache.spark.rpc.netty.NettyRpcEnv.createClient(NettyRpcEnv.scala:204)
[2021-12-29 12:02:38,827] {spark_submit.py:514} INFO - at org.apache.spark.rpc.netty.Outbox$$anon$1.call(Outbox.scala:202)
[2021-12-29 12:02:38,829] {spark_submit.py:514} INFO - at org.apache.spark.rpc.netty.Outbox$$anon$1.call(Outbox.scala:198)
[2021-12-29 12:02:38,843] {spark_submit.py:514} INFO - ... 4 more
[2021-12-29 12:02:38,847] {spark_submit.py:514} INFO - Caused by: java.net.UnknownHostException: spark: Name or service not known
[2021-12-29 12:02:38,852] {spark_submit.py:514} INFO - at java.base/java.net.Inet4AddressImpl.lookupAllHostAddr(Native Method)
[2021-12-29 12:02:38,854] {spark_submit.py:514} INFO - at java.base/java.net.InetAddress$PlatformNameService.lookupAllHostAddr(InetAddress.java:929)
[2021-12-29 12:02:38,870] {spark_submit.py:514} INFO - at java.base/java.net.InetAddress.getAddressesFromNameService(InetAddress.java:1519)
[2021-12-29 12:02:38,891] {spark_submit.py:514} INFO - at java.base/java.net.InetAddress$NameServiceAddresses.get(InetAddress.java:848)
[2021-12-29 12:02:38,898] {spark_submit.py:514} INFO - at java.base/java.net.InetAddress.getAllByName0(InetAddress.java:1509)
[2021-12-29 12:02:38,915] {spark_submit.py:514} INFO - at java.base/java.net.InetAddress.getAllByName(InetAddress.java:1368)
[2021-12-29 12:02:38,918] {spark_submit.py:514} INFO - at java.base/java.net.InetAddress.getAllByName(InetAddress.java:1302)
[2021-12-29 12:02:38,930] {spark_submit.py:514} INFO - at java.base/java.net.InetAddress.getByName(InetAddress.java:1252)
[2021-12-29 12:02:38,945] {spark_submit.py:514} INFO - at io.netty.util.internal.SocketUtils$8.run(SocketUtils.java:156)
[2021-12-29 12:02:38,954] {spark_submit.py:514} INFO - at io.netty.util.internal.SocketUtils$8.run(SocketUtils.java:153)
[2021-12-29 12:02:38,985] {spark_submit.py:514} INFO - at java.base/java.security.AccessController.doPrivileged(Native Method)
[2021-12-29 12:02:39,002] {spark_submit.py:514} INFO - at io.netty.util.internal.SocketUtils.addressByName(SocketUtils.java:153)
[2021-12-29 12:02:39,004] {spark_submit.py:514} INFO - at io.netty.resolver.DefaultNameResolver.doResolve(DefaultNameResolver.java:41)
[2021-12-29 12:02:39,009] {spark_submit.py:514} INFO - at io.netty.resolver.SimpleNameResolver.resolve(SimpleNameResolver.java:61)
[2021-12-29 12:02:39,012] {spark_submit.py:514} INFO - at io.netty.resolver.SimpleNameResolver.resolve(SimpleNameResolver.java:53)
[2021-12-29 12:02:39,015] {spark_submit.py:514} INFO - at io.netty.resolver.InetSocketAddressResolver.doResolve(InetSocketAddressResolver.java:55)
[2021-12-29 12:02:39,022] {spark_submit.py:514} INFO - at io.netty.resolver.InetSocketAddressResolver.doResolve(InetSocketAddressResolver.java:31)
[2021-12-29 12:02:39,031] {spark_submit.py:514} INFO - at io.netty.resolver.AbstractAddressResolver.resolve(AbstractAddressResolver.java:106)
[2021-12-29 12:02:39,042] {spark_submit.py:514} INFO - at io.netty.bootstrap.Bootstrap.doResolveAndConnect0(Bootstrap.java:206)
[2021-12-29 12:02:39,048] {spark_submit.py:514} INFO - at io.netty.bootstrap.Bootstrap.access$000(Bootstrap.java:46)
[2021-12-29 12:02:39,049] {spark_submit.py:514} INFO - at io.netty.bootstrap.Bootstrap$1.operationComplete(Bootstrap.java:180)
[2021-12-29 12:02:39,051] {spark_submit.py:514} INFO - at io.netty.bootstrap.Bootstrap$1.operationComplete(Bootstrap.java:166)
[2021-12-29 12:02:39,052] {spark_submit.py:514} INFO - at io.netty.util.concurrent.DefaultPromise.notifyListener0(DefaultPromise.java:578)
[2021-12-29 12:02:39,054] {spark_submit.py:514} INFO - at io.netty.util.concurrent.DefaultPromise.notifyListenersNow(DefaultPromise.java:552)
[2021-12-29 12:02:39,055] {spark_submit.py:514} INFO - at io.netty.util.concurrent.DefaultPromise.notifyListeners(DefaultPromise.java:491)
[2021-12-29 12:02:39,065] {spark_submit.py:514} INFO - at io.netty.util.concurrent.DefaultPromise.setValue0(DefaultPromise.java:616)
[2021-12-29 12:02:39,067] {spark_submit.py:514} INFO - at io.netty.util.concurrent.DefaultPromise.setSuccess0(DefaultPromise.java:605)
[2021-12-29 12:02:39,069] {spark_submit.py:514} INFO - at io.netty.util.concurrent.DefaultPromise.trySuccess(DefaultPromise.java:104)
[2021-12-29 12:02:39,070] {spark_submit.py:514} INFO - at io.netty.channel.DefaultChannelPromise.trySuccess(DefaultChannelPromise.java:84)
[2021-12-29 12:02:39,075] {spark_submit.py:514} INFO - at io.netty.channel.AbstractChannel$AbstractUnsafe.safeSetSuccess(AbstractChannel.java:1008)
[2021-12-29 12:02:39,076] {spark_submit.py:514} INFO - at io.netty.channel.AbstractChannel$AbstractUnsafe.register0(AbstractChannel.java:516)
[2021-12-29 12:02:39,079] {spark_submit.py:514} INFO - at io.netty.channel.AbstractChannel$AbstractUnsafe.access$200(AbstractChannel.java:429)
[2021-12-29 12:02:39,080] {spark_submit.py:514} INFO - at io.netty.channel.AbstractChannel$AbstractUnsafe$1.run(AbstractChannel.java:486)
[2021-12-29 12:02:39,081] {spark_submit.py:514} INFO - at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:164)
[2021-12-29 12:02:39,094] {spark_submit.py:514} INFO - at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:469)
[2021-12-29 12:02:39,097] {spark_submit.py:514} INFO - at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:500)
[2021-12-29 12:02:39,099] {spark_submit.py:514} INFO - at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:986)
[2021-12-29 12:02:39,101] {spark_submit.py:514} INFO - at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
[2021-12-29 12:02:39,104] {spark_submit.py:514} INFO - at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
[2021-12-29 12:02:39,105] {spark_submit.py:514} INFO - ... 1 more
[2021-12-29 12:02:55,919] {spark_submit.py:514} INFO - 21/12/29 12:02:55 INFO StandaloneAppClient$ClientEndpoint: Connecting to master spark://spark:7077...
[2021-12-29 12:02:56,677] {spark_submit.py:514} INFO - 21/12/29 12:02:56 WARN StandaloneAppClient$ClientEndpoint: Failed to connect to master spark:7077
[2021-12-29 12:02:56,682] {spark_submit.py:514} INFO - org.apache.spark.SparkException: Exception thrown in awaitResult:
[2021-12-29 12:02:56,686] {spark_submit.py:514} INFO - at org.apache.spark.util.ThreadUtils$.awaitResult(ThreadUtils.scala:301)
[2021-12-29 12:02:56,690] {spark_submit.py:514} INFO - at org.apache.spark.rpc.RpcTimeout.awaitResult(RpcTimeout.scala:75)
[2021-12-29 12:02:56,702] {spark_submit.py:514} INFO - at org.apache.spark.rpc.RpcEnv.setupEndpointRefByURI(RpcEnv.scala:101)
[2021-12-29 12:02:56,707] {spark_submit.py:514} INFO - at org.apache.spark.rpc.RpcEnv.setupEndpointRef(RpcEnv.scala:109)
[2021-12-29 12:02:56,716] {spark_submit.py:514} INFO - at org.apache.spark.deploy.client.StandaloneAppClient$ClientEndpoint$$anon$1.run(StandaloneAppClient.scala:107)
[2021-12-29 12:02:56,718] {spark_submit.py:514} INFO - at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
[2021-12-29 12:02:56,725] {spark_submit.py:514} INFO - at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
[2021-12-29 12:02:56,728] {spark_submit.py:514} INFO - at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
[2021-12-29 12:02:56,733] {spark_submit.py:514} INFO - at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
[2021-12-29 12:02:56,764] {spark_submit.py:514} INFO - at java.base/java.lang.Thread.run(Thread.java:829)
[2021-12-29 12:02:56,774] {spark_submit.py:514} INFO - Caused by: java.io.IOException: Failed to connect to spark:7077
[2021-12-29 12:02:56,794] {spark_submit.py:514} INFO - at org.apache.spark.network.client.TransportClientFactory.createClient(TransportClientFactory.java:288)
[2021-12-29 12:02:56,795] {spark_submit.py:514} INFO - at org.apache.spark.network.client.TransportClientFactory.createClient(TransportClientFactory.java:218)
[2021-12-29 12:02:56,800] {spark_submit.py:514} INFO - at org.apache.spark.network.client.TransportClientFactory.createClient(TransportClientFactory.java:230)
[2021-12-29 12:02:56,807] {spark_submit.py:514} INFO - at org.apache.spark.rpc.netty.NettyRpcEnv.createClient(NettyRpcEnv.scala:204)
[2021-12-29 12:02:56,810] {spark_submit.py:514} INFO - at org.apache.spark.rpc.netty.Outbox$$anon$1.call(Outbox.scala:202)
[2021-12-29 12:02:56,813] {spark_submit.py:514} INFO - at org.apache.spark.rpc.netty.Outbox$$anon$1.call(Outbox.scala:198)
[2021-12-29 12:02:56,829] {spark_submit.py:514} INFO - ... 4 more
[2021-12-29 12:02:56,838] {spark_submit.py:514} INFO - Caused by: java.net.UnknownHostException: spark
[2021-12-29 12:02:56,849] {spark_submit.py:514} INFO - at java.base/java.net.InetAddress$CachedAddresses.get(InetAddress.java:797)
[2021-12-29 12:02:56,858] {spark_submit.py:514} INFO - at java.base/java.net.InetAddress.getAllByName0(InetAddress.java:1509)
[2021-12-29 12:02:56,863] {spark_submit.py:514} INFO - at java.base/java.net.InetAddress.getAllByName(InetAddress.java:1368)
[2021-12-29 12:02:56,867] {spark_submit.py:514} INFO - at java.base/java.net.InetAddress.getAllByName(InetAddress.java:1302)
[2021-12-29 12:02:56,872] {spark_submit.py:514} INFO - at java.base/java.net.InetAddress.getByName(InetAddress.java:1252)
[2021-12-29 12:02:56,874] {spark_submit.py:514} INFO - at io.netty.util.internal.SocketUtils$8.run(SocketUtils.java:156)
[2021-12-29 12:02:56,891] {spark_submit.py:514} INFO - at io.netty.util.internal.SocketUtils$8.run(SocketUtils.java:153)
[2021-12-29 12:02:56,903] {spark_submit.py:514} INFO - at java.base/java.security.AccessController.doPrivileged(Native Method)
[2021-12-29 12:02:56,914] {spark_submit.py:514} INFO - at io.netty.util.internal.SocketUtils.addressByName(SocketUtils.java:153)
[2021-12-29 12:02:56,941] {spark_submit.py:514} INFO - at io.netty.resolver.DefaultNameResolver.doResolve(DefaultNameResolver.java:41)
[2021-12-29 12:02:56,947] {spark_submit.py:514} INFO - at io.netty.resolver.SimpleNameResolver.resolve(SimpleNameResolver.java:61)
[2021-12-29 12:02:56,952] {spark_submit.py:514} INFO - at io.netty.resolver.SimpleNameResolver.resolve(SimpleNameResolver.java:53)
[2021-12-29 12:02:56,955] {spark_submit.py:514} INFO - at io.netty.resolver.InetSocketAddressResolver.doResolve(InetSocketAddressResolver.java:55)
[2021-12-29 12:02:56,977] {spark_submit.py:514} INFO - at io.netty.resolver.InetSocketAddressResolver.doResolve(InetSocketAddressResolver.java:31)
[2021-12-29 12:02:56,980] {spark_submit.py:514} INFO - at io.netty.resolver.AbstractAddressResolver.resolve(AbstractAddressResolver.java:106)
[2021-12-29 12:02:57,087] {spark_submit.py:514} INFO - at io.netty.bootstrap.Bootstrap.doResolveAndConnect0(Bootstrap.java:206)
[2021-12-29 12:02:57,102] {spark_submit.py:514} INFO - at io.netty.bootstrap.Bootstrap.access$000(Bootstrap.java:46)
[2021-12-29 12:02:57,106] {spark_submit.py:514} INFO - at io.netty.bootstrap.Bootstrap$1.operationComplete(Bootstrap.java:180)
[2021-12-29 12:02:57,108] {spark_submit.py:514} INFO - at io.netty.bootstrap.Bootstrap$1.operationComplete(Bootstrap.java:166)
[2021-12-29 12:02:57,112] {spark_submit.py:514} INFO - at io.netty.util.concurrent.DefaultPromise.notifyListener0(DefaultPromise.java:578)
[2021-12-29 12:02:57,118] {spark_submit.py:514} INFO - at io.netty.util.concurrent.DefaultPromise.notifyListenersNow(DefaultPromise.java:552)
[2021-12-29 12:02:57,136] {spark_submit.py:514} INFO - at io.netty.util.concurrent.DefaultPromise.notifyListeners(DefaultPromise.java:491)
[2021-12-29 12:02:57,139] {spark_submit.py:514} INFO - at io.netty.util.concurrent.DefaultPromise.setValue0(DefaultPromise.java:616)
[2021-12-29 12:02:57,146] {spark_submit.py:514} INFO - at io.netty.util.concurrent.DefaultPromise.setSuccess0(DefaultPromise.java:605)
[2021-12-29 12:02:57,241] {spark_submit.py:514} INFO - at io.netty.util.concurrent.DefaultPromise.trySuccess(DefaultPromise.java:104)
[2021-12-29 12:02:57,283] {spark_submit.py:514} INFO - at io.netty.channel.DefaultChannelPromise.trySuccess(DefaultChannelPromise.java:84)
[2021-12-29 12:02:57,302] {spark_submit.py:514} INFO - at io.netty.channel.AbstractChannel$AbstractUnsafe.safeSetSuccess(AbstractChannel.java:1008)
[2021-12-29 12:02:57,304] {spark_submit.py:514} INFO - at io.netty.channel.AbstractChannel$AbstractUnsafe.register0(AbstractChannel.java:516)
[2021-12-29 12:02:57,308] {spark_submit.py:514} INFO - at io.netty.channel.AbstractChannel$AbstractUnsafe.access$200(AbstractChannel.java:429)
[2021-12-29 12:02:57,312] {spark_submit.py:514} INFO - at io.netty.channel.AbstractChannel$AbstractUnsafe$1.run(AbstractChannel.java:486)
[2021-12-29 12:02:57,331] {spark_submit.py:514} INFO - at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:164)
[2021-12-29 12:02:57,349] {spark_submit.py:514} INFO - at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:469)
[2021-12-29 12:02:57,354] {spark_submit.py:514} INFO - at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:500)
[2021-12-29 12:02:57,357] {spark_submit.py:514} INFO - at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:986)
[2021-12-29 12:02:57,381] {spark_submit.py:514} INFO - at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
[2021-12-29 12:02:57,404] {spark_submit.py:514} INFO - at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
[2021-12-29 12:02:57,419] {spark_submit.py:514} INFO - ... 1 more
[2021-12-29 12:03:15,779] {spark_submit.py:514} INFO - 21/12/29 12:03:15 ERROR StandaloneSchedulerBackend: Application has been killed. Reason: All masters are unresponsive! Giving up.
[2021-12-29 12:03:15,852] {spark_submit.py:514} INFO - 21/12/29 12:03:15 WARN StandaloneSchedulerBackend: Application ID is not initialized yet.
[2021-12-29 12:03:16,262] {spark_submit.py:514} INFO - 21/12/29 12:03:16 INFO Utils: Successfully started service 'org.apache.spark.network.netty.NettyBlockTransferService' on port 37359.
[2021-12-29 12:03:16,265] {spark_submit.py:514} INFO - 21/12/29 12:03:16 INFO NettyBlockTransferService: Server created on 6bdda4c19a85:37359
[2021-12-29 12:03:16,289] {spark_submit.py:514} INFO - 21/12/29 12:03:16 INFO BlockManager: Using org.apache.spark.storage.RandomBlockReplicationPolicy for block replication policy
[2021-12-29 12:03:16,502] {spark_submit.py:514} INFO - 21/12/29 12:03:16 INFO SparkUI: Stopped Spark web UI at http://6bdda4c19a85:4054
[2021-12-29 12:03:16,520] {spark_submit.py:514} INFO - 21/12/29 12:03:16 INFO BlockManagerMaster: Registering BlockManager BlockManagerId(driver, 6bdda4c19a85, 37359, None)
[2021-12-29 12:03:16,805] {spark_submit.py:514} INFO - 21/12/29 12:03:16 INFO BlockManagerMasterEndpoint: Registering block manager 6bdda4c19a85:37359 with 434.4 MiB RAM, BlockManagerId(driver, 6bdda4c19a85, 37359, None)
[2021-12-29 12:03:16,884] {spark_submit.py:514} INFO - 21/12/29 12:03:16 INFO StandaloneSchedulerBackend: Shutting down all executors
[2021-12-29 12:03:16,895] {spark_submit.py:514} INFO - 21/12/29 12:03:16 INFO BlockManagerMaster: Registered BlockManager BlockManagerId(driver, 6bdda4c19a85, 37359, None)
[2021-12-29 12:03:16,907] {spark_submit.py:514} INFO - 21/12/29 12:03:16 INFO BlockManager: Initialized BlockManager: BlockManagerId(driver, 6bdda4c19a85, 37359, None)
[2021-12-29 12:03:17,054] {spark_submit.py:514} INFO - 21/12/29 12:03:17 INFO CoarseGrainedSchedulerBackend$DriverEndpoint: Asking each executor to shut down
[2021-12-29 12:03:17,097] {spark_submit.py:514} INFO - 21/12/29 12:03:17 WARN StandaloneAppClient$ClientEndpoint: Drop UnregisterApplication(null) because has not yet connected to master
[2021-12-29 12:03:17,272] {spark_submit.py:514} INFO - 21/12/29 12:03:17 INFO MapOutputTrackerMasterEndpoint: MapOutputTrackerMasterEndpoint stopped!
[2021-12-29 12:03:17,795] {spark_submit.py:514} INFO - 21/12/29 12:03:17 INFO MemoryStore: MemoryStore cleared
[2021-12-29 12:03:17,826] {spark_submit.py:514} INFO - 21/12/29 12:03:17 INFO BlockManager: BlockManager stopped
[2021-12-29 12:03:17,957] {spark_submit.py:514} INFO - 21/12/29 12:03:17 INFO BlockManagerMaster: BlockManagerMaster stopped
[2021-12-29 12:03:18,028] {spark_submit.py:514} INFO - 21/12/29 12:03:18 INFO OutputCommitCoordinator$OutputCommitCoordinatorEndpoint: OutputCommitCoordinator stopped!
[2021-12-29 12:03:18,466] {spark_submit.py:514} INFO - 21/12/29 12:03:18 INFO SparkContext: Successfully stopped SparkContext
[2021-12-29 12:03:19,286] {spark_submit.py:514} INFO - 21/12/29 12:03:19 ERROR SparkContext: Error initializing SparkContext.
[2021-12-29 12:03:19,532] {spark_submit.py:514} INFO - java.lang.IllegalArgumentException: requirement failed: Can only call getServletHandlers on a running MetricsSystem
[2021-12-29 12:03:19,536] {spark_submit.py:514} INFO - at scala.Predef$.require(Predef.scala:281)
[2021-12-29 12:03:19,538] {spark_submit.py:514} INFO - at org.apache.spark.metrics.MetricsSystem.getServletHandlers(MetricsSystem.scala:89)
[2021-12-29 12:03:19,542] {spark_submit.py:514} INFO - at org.apache.spark.SparkContext.<init>(SparkContext.scala:603)
[2021-12-29 12:03:19,545] {spark_submit.py:514} INFO - at org.apache.spark.api.java.JavaSparkContext.<init>(JavaSparkContext.scala:58)
[2021-12-29 12:03:19,547] {spark_submit.py:514} INFO - at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
[2021-12-29 12:03:19,557] {spark_submit.py:514} INFO - at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
[2021-12-29 12:03:19,564] {spark_submit.py:514} INFO - at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
[2021-12-29 12:03:19,584] {spark_submit.py:514} INFO - at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:490)
[2021-12-29 12:03:19,596] {spark_submit.py:514} INFO - at py4j.reflection.MethodInvoker.invoke(MethodInvoker.java:247)
[2021-12-29 12:03:19,599] {spark_submit.py:514} INFO - at py4j.reflection.ReflectionEngine.invoke(ReflectionEngine.java:357)
[2021-12-29 12:03:19,603] {spark_submit.py:514} INFO - at py4j.Gateway.invoke(Gateway.java:238)
[2021-12-29 12:03:19,607] {spark_submit.py:514} INFO - at py4j.commands.ConstructorCommand.invokeConstructor(ConstructorCommand.java:80)
[2021-12-29 12:03:19,611] {spark_submit.py:514} INFO - at py4j.commands.ConstructorCommand.execute(ConstructorCommand.java:69)
[2021-12-29 12:03:19,629] {spark_submit.py:514} INFO - at py4j.ClientServerConnection.waitForCommands(ClientServerConnection.java:182)
[2021-12-29 12:03:19,637] {spark_submit.py:514} INFO - at py4j.ClientServerConnection.run(ClientServerConnection.java:106)
[2021-12-29 12:03:19,640] {spark_submit.py:514} INFO - at java.base/java.lang.Thread.run(Thread.java:829)
[2021-12-29 12:03:19,650] {spark_submit.py:514} INFO - 21/12/29 12:03:19 INFO SparkContext: SparkContext already stopped.
[2021-12-29 12:03:19,673] {spark_submit.py:514} INFO - Traceback (most recent call last):
[2021-12-29 12:03:19,675] {spark_submit.py:514} INFO - File "/opt/***/jobs/get_ads_per_county.py", line 13, in <module>
[2021-12-29 12:03:19,676] {spark_submit.py:514} INFO - .appName("Get Ads per county") \
[2021-12-29 12:03:19,678] {spark_submit.py:514} INFO - File "/home/***/.local/lib/python3.6/site-packages/pyspark/python/lib/pyspark.zip/pyspark/sql/session.py", line 228, in getOrCreate
[2021-12-29 12:03:19,680] {spark_submit.py:514} INFO - File "/home/***/.local/lib/python3.6/site-packages/pyspark/python/lib/pyspark.zip/pyspark/context.py", line 392, in getOrCreate
[2021-12-29 12:03:19,682] {spark_submit.py:514} INFO - File "/home/***/.local/lib/python3.6/site-packages/pyspark/python/lib/pyspark.zip/pyspark/context.py", line 147, in __init__
[2021-12-29 12:03:19,691] {spark_submit.py:514} INFO - File "/home/***/.local/lib/python3.6/site-packages/pyspark/python/lib/pyspark.zip/pyspark/context.py", line 209, in _do_init
[2021-12-29 12:03:19,692] {spark_submit.py:514} INFO - File "/home/***/.local/lib/python3.6/site-packages/pyspark/python/lib/pyspark.zip/pyspark/context.py", line 329, in _initialize_context
[2021-12-29 12:03:19,694] {spark_submit.py:514} INFO - File "/home/***/.local/lib/python3.6/site-packages/pyspark/python/lib/py4j-0.10.9.2-src.zip/py4j/java_gateway.py", line 1574, in __call__
[2021-12-29 12:03:19,697] {spark_submit.py:514} INFO - File "/home/***/.local/lib/python3.6/site-packages/pyspark/python/lib/py4j-0.10.9.2-src.zip/py4j/protocol.py", line 328, in get_return_value
[2021-12-29 12:03:19,716] {spark_submit.py:514} INFO - py4j.protocol.Py4JJavaError: An error occurred while calling None.org.apache.spark.api.java.JavaSparkContext.
[2021-12-29 12:03:19,720] {spark_submit.py:514} INFO - : java.lang.IllegalArgumentException: requirement failed: Can only call getServletHandlers on a running MetricsSystem
[2021-12-29 12:03:19,745] {spark_submit.py:514} INFO - at scala.Predef$.require(Predef.scala:281)
[2021-12-29 12:03:19,753] {spark_submit.py:514} INFO - at org.apache.spark.metrics.MetricsSystem.getServletHandlers(MetricsSystem.scala:89)
[2021-12-29 12:03:19,762] {spark_submit.py:514} INFO - at org.apache.spark.SparkContext.<init>(SparkContext.scala:603)
[2021-12-29 12:03:19,774] {spark_submit.py:514} INFO - at org.apache.spark.api.java.JavaSparkContext.<init>(JavaSparkContext.scala:58)
[2021-12-29 12:03:19,780] {spark_submit.py:514} INFO - at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
[2021-12-29 12:03:19,793] {spark_submit.py:514} INFO - at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
[2021-12-29 12:03:19,796] {spark_submit.py:514} INFO - at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
[2021-12-29 12:03:19,804] {spark_submit.py:514} INFO - at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:490)
[2021-12-29 12:03:19,808] {spark_submit.py:514} INFO - at py4j.reflection.MethodInvoker.invoke(MethodInvoker.java:247)
[2021-12-29 12:03:19,811] {spark_submit.py:514} INFO - at py4j.reflection.ReflectionEngine.invoke(ReflectionEngine.java:357)
[2021-12-29 12:03:19,815] {spark_submit.py:514} INFO - at py4j.Gateway.invoke(Gateway.java:238)
[2021-12-29 12:03:19,818] {spark_submit.py:514} INFO - at py4j.commands.ConstructorCommand.invokeConstructor(ConstructorCommand.java:80)
[2021-12-29 12:03:19,831] {spark_submit.py:514} INFO - at py4j.commands.ConstructorCommand.execute(ConstructorCommand.java:69)
[2021-12-29 12:03:19,838] {spark_submit.py:514} INFO - at py4j.ClientServerConnection.waitForCommands(ClientServerConnection.java:182)
[2021-12-29 12:03:19,843] {spark_submit.py:514} INFO - at py4j.ClientServerConnection.run(ClientServerConnection.java:106)
[2021-12-29 12:03:19,845] {spark_submit.py:514} INFO - at java.base/java.lang.Thread.run(Thread.java:829)
[2021-12-29 12:03:19,850] {spark_submit.py:514} INFO - 
[2021-12-29 12:03:23,155] {spark_submit.py:514} INFO - 21/12/29 12:03:23 INFO ShutdownHookManager: Shutdown hook called
[2021-12-29 12:03:23,159] {spark_submit.py:514} INFO - 21/12/29 12:03:23 INFO ShutdownHookManager: Deleting directory /tmp/spark-0c684b05-86f0-4daa-b2e0-37f8ee9af41a
[2021-12-29 12:03:23,178] {spark_submit.py:514} INFO - 21/12/29 12:03:23 INFO ShutdownHookManager: Deleting directory /tmp/spark-1bf078c6-10dd-4ca2-91dc-e6116169b4ec
[2021-12-29 12:03:27,028] {taskinstance.py:1703} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 1332, in _run_raw_task
    self._execute_task_with_callbacks(context)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 1458, in _execute_task_with_callbacks
    result = self._execute_task(context, self.task)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 1514, in _execute_task
    result = execute_callable(context=context)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/providers/apache/spark/operators/spark_submit.py", line 179, in execute
    self._hook.submit(self._application)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/providers/apache/spark/hooks/spark_submit.py", line 446, in submit
    f"Cannot execute: {self._mask_cmd(spark_submit_cmd)}. Error code is: {returncode}."
airflow.exceptions.AirflowException: Cannot execute: spark-submit --master spark://spark:7077 --conf spark.master=spark://spark:7077 --name scrap data --verbose /opt/***/jobs/get_ads_per_county.py meath. Error code is: 1.
[2021-12-29 12:03:27,254] {taskinstance.py:1280} INFO - Marking task as UP_FOR_RETRY. dag_id=scraping_daft_meath, task_id=scrap_data, execution_date=20211228T102500, start_date=20211229T115723, end_date=20211229T120327
[2021-12-29 12:03:27,396] {standard_task_runner.py:91} ERROR - Failed to execute job 5325 for task scrap_data
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/task/task_runner/standard_task_runner.py", line 85, in _start_by_fork
    args.func(args, dag=self.dag)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/cli/cli_parser.py", line 48, in command
    return func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/utils/cli.py", line 92, in wrapper
    return f(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/cli/commands/task_command.py", line 292, in task_run
    _run_task_by_selected_method(args, dag, ti)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/cli/commands/task_command.py", line 107, in _run_task_by_selected_method
    _run_raw_task(args, ti)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/cli/commands/task_command.py", line 184, in _run_raw_task
    error_file=args.error_file,
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/utils/session.py", line 70, in wrapper
    return func(*args, session=session, **kwargs)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 1332, in _run_raw_task
    self._execute_task_with_callbacks(context)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 1458, in _execute_task_with_callbacks
    result = self._execute_task(context, self.task)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 1514, in _execute_task
    result = execute_callable(context=context)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/providers/apache/spark/operators/spark_submit.py", line 179, in execute
    self._hook.submit(self._application)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/providers/apache/spark/hooks/spark_submit.py", line 446, in submit
    f"Cannot execute: {self._mask_cmd(spark_submit_cmd)}. Error code is: {returncode}."
airflow.exceptions.AirflowException: Cannot execute: spark-submit --master spark://spark:7077 --conf spark.master=spark://spark:7077 --name scrap data --verbose /opt/***/jobs/get_ads_per_county.py meath. Error code is: 1.
[2021-12-29 12:03:27,556] {local_task_job.py:154} INFO - Task exited with return code 1
[2021-12-29 12:03:27,972] {local_task_job.py:264} INFO - 0 downstream tasks scheduled from follow-on schedule check
