[2021-12-29 12:03:15,974] {taskinstance.py:1035} INFO - Dependencies all met for <TaskInstance: scraping_daft_laois.scrap_data scheduled__2021-12-28T09:55:00+00:00 [queued]>
[2021-12-29 12:03:16,070] {taskinstance.py:1035} INFO - Dependencies all met for <TaskInstance: scraping_daft_laois.scrap_data scheduled__2021-12-28T09:55:00+00:00 [queued]>
[2021-12-29 12:03:16,072] {taskinstance.py:1241} INFO - 
--------------------------------------------------------------------------------
[2021-12-29 12:03:16,074] {taskinstance.py:1242} INFO - Starting attempt 1 of 4
[2021-12-29 12:03:16,082] {taskinstance.py:1243} INFO - 
--------------------------------------------------------------------------------
[2021-12-29 12:03:16,156] {taskinstance.py:1262} INFO - Executing <Task(SparkSubmitOperator): scrap_data> on 2021-12-28 09:55:00+00:00
[2021-12-29 12:03:16,181] {standard_task_runner.py:52} INFO - Started process 27259 to run task
[2021-12-29 12:03:16,204] {standard_task_runner.py:76} INFO - Running: ['***', 'tasks', 'run', 'scraping_daft_laois', 'scrap_data', 'scheduled__2021-12-28T09:55:00+00:00', '--job-id', '5348', '--raw', '--subdir', 'DAGS_FOLDER/scraping_daft_laois.py', '--cfg-path', '/tmp/tmpkjklt4f1', '--error-file', '/tmp/tmpjlbhjpt3']
[2021-12-29 12:03:16,215] {standard_task_runner.py:77} INFO - Job 5348: Subtask scrap_data
[2021-12-29 12:03:16,841] {logging_mixin.py:109} INFO - Running <TaskInstance: scraping_daft_laois.scrap_data scheduled__2021-12-28T09:55:00+00:00 [running]> on host 6bdda4c19a85
[2021-12-29 12:03:17,600] {taskinstance.py:1429} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_EMAIL=clement.liscoet@gmail.com
AIRFLOW_CTX_DAG_OWNER=clemoni
AIRFLOW_CTX_DAG_ID=scraping_daft_laois
AIRFLOW_CTX_TASK_ID=scrap_data
AIRFLOW_CTX_EXECUTION_DATE=2021-12-28T09:55:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2021-12-28T09:55:00+00:00
[2021-12-29 12:03:17,701] {base.py:79} INFO - Using connection to: id: spark_default. Host: spark://spark:7077, Port: None, Schema: , Login: ***, Password: ***, extra: {}
[2021-12-29 12:03:17,709] {spark_submit.py:360} INFO - Spark-Submit cmd: spark-submit --master spark://spark:7077 --conf spark.master=spark://spark:7077 --name scrap data --verbose /opt/***/jobs/get_ads_per_county.py laois
[2021-12-29 12:03:29,273] {spark_submit.py:514} INFO - Using properties file: null
[2021-12-29 12:03:30,050] {spark_submit.py:514} INFO - WARNING: An illegal reflective access operation has occurred
[2021-12-29 12:03:30,051] {spark_submit.py:514} INFO - WARNING: Illegal reflective access by org.apache.spark.unsafe.Platform (file:/home/***/.local/lib/python3.6/site-packages/pyspark/jars/spark-unsafe_2.12-3.2.0.jar) to constructor java.nio.DirectByteBuffer(long,int)
[2021-12-29 12:03:30,052] {spark_submit.py:514} INFO - WARNING: Please consider reporting this to the maintainers of org.apache.spark.unsafe.Platform
[2021-12-29 12:03:30,054] {spark_submit.py:514} INFO - WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
[2021-12-29 12:03:30,056] {spark_submit.py:514} INFO - WARNING: All illegal access operations will be denied in a future release
[2021-12-29 12:03:30,285] {spark_submit.py:514} INFO - Parsed arguments:
[2021-12-29 12:03:30,289] {spark_submit.py:514} INFO - master                  spark://spark:7077
[2021-12-29 12:03:30,292] {spark_submit.py:514} INFO - deployMode              null
[2021-12-29 12:03:30,296] {spark_submit.py:514} INFO - executorMemory          null
[2021-12-29 12:03:30,299] {spark_submit.py:514} INFO - executorCores           null
[2021-12-29 12:03:30,301] {spark_submit.py:514} INFO - totalExecutorCores      null
[2021-12-29 12:03:30,309] {spark_submit.py:514} INFO - propertiesFile          null
[2021-12-29 12:03:30,311] {spark_submit.py:514} INFO - driverMemory            null
[2021-12-29 12:03:30,315] {spark_submit.py:514} INFO - driverCores             null
[2021-12-29 12:03:30,325] {spark_submit.py:514} INFO - driverExtraClassPath    null
[2021-12-29 12:03:30,329] {spark_submit.py:514} INFO - driverExtraLibraryPath  null
[2021-12-29 12:03:30,352] {spark_submit.py:514} INFO - driverExtraJavaOptions  null
[2021-12-29 12:03:30,359] {spark_submit.py:514} INFO - supervise               false
[2021-12-29 12:03:30,367] {spark_submit.py:514} INFO - queue                   null
[2021-12-29 12:03:30,380] {spark_submit.py:514} INFO - numExecutors            null
[2021-12-29 12:03:30,387] {spark_submit.py:514} INFO - files                   null
[2021-12-29 12:03:30,390] {spark_submit.py:514} INFO - pyFiles                 null
[2021-12-29 12:03:30,393] {spark_submit.py:514} INFO - archives                null
[2021-12-29 12:03:30,399] {spark_submit.py:514} INFO - mainClass               null
[2021-12-29 12:03:30,402] {spark_submit.py:514} INFO - primaryResource         file:/opt/***/jobs/get_ads_per_county.py
[2021-12-29 12:03:30,409] {spark_submit.py:514} INFO - name                    scrap data
[2021-12-29 12:03:30,429] {spark_submit.py:514} INFO - childArgs               [laois]
[2021-12-29 12:03:30,432] {spark_submit.py:514} INFO - jars                    null
[2021-12-29 12:03:30,434] {spark_submit.py:514} INFO - packages                null
[2021-12-29 12:03:30,439] {spark_submit.py:514} INFO - packagesExclusions      null
[2021-12-29 12:03:30,441] {spark_submit.py:514} INFO - repositories            null
[2021-12-29 12:03:30,443] {spark_submit.py:514} INFO - verbose                 true
[2021-12-29 12:03:30,444] {spark_submit.py:514} INFO - 
[2021-12-29 12:03:30,446] {spark_submit.py:514} INFO - Spark properties used, including those specified through
[2021-12-29 12:03:30,448] {spark_submit.py:514} INFO - --conf and those from the properties file null:
[2021-12-29 12:03:30,449] {spark_submit.py:514} INFO - (spark.master,spark://spark:7077)
[2021-12-29 12:03:30,452] {spark_submit.py:514} INFO - 
[2021-12-29 12:03:30,454] {spark_submit.py:514} INFO - 
[2021-12-29 12:03:32,204] {spark_submit.py:514} INFO - Main class:
[2021-12-29 12:03:32,207] {spark_submit.py:514} INFO - org.apache.spark.deploy.PythonRunner
[2021-12-29 12:03:32,220] {spark_submit.py:514} INFO - Arguments:
[2021-12-29 12:03:32,222] {spark_submit.py:514} INFO - file:/opt/***/jobs/get_ads_per_county.py
[2021-12-29 12:03:32,230] {spark_submit.py:514} INFO - null
[2021-12-29 12:03:32,233] {spark_submit.py:514} INFO - laois
[2021-12-29 12:03:32,236] {spark_submit.py:514} INFO - --verbose
[2021-12-29 12:03:32,242] {spark_submit.py:514} INFO - Spark config:
[2021-12-29 12:03:32,244] {spark_submit.py:514} INFO - (spark.app.name,scrap data)
[2021-12-29 12:03:32,246] {spark_submit.py:514} INFO - (spark.master,spark://spark:7077)
[2021-12-29 12:03:32,248] {spark_submit.py:514} INFO - (spark.submit.pyFiles,)
[2021-12-29 12:03:32,250] {spark_submit.py:514} INFO - (spark.submit.deployMode,client)
[2021-12-29 12:03:32,251] {spark_submit.py:514} INFO - Classpath elements:
[2021-12-29 12:03:32,253] {spark_submit.py:514} INFO - 
[2021-12-29 12:03:32,254] {spark_submit.py:514} INFO - 
[2021-12-29 12:03:32,255] {spark_submit.py:514} INFO - 
[2021-12-29 12:03:44,917] {spark_submit.py:514} INFO - Using Spark's default log4j profile: org/apache/spark/log4j-defaults.properties
[2021-12-29 12:03:45,059] {spark_submit.py:514} INFO - 21/12/29 12:03:45 INFO SparkContext: Running Spark version 3.2.0
[2021-12-29 12:03:46,568] {spark_submit.py:514} INFO - 21/12/29 12:03:46 WARN NativeCodeLoader: Unable to load native-hadoop library for your platform... using builtin-java classes where applicable
[2021-12-29 12:03:48,103] {spark_submit.py:514} INFO - 21/12/29 12:03:48 INFO ResourceUtils: ==============================================================
[2021-12-29 12:03:48,105] {spark_submit.py:514} INFO - 21/12/29 12:03:48 INFO ResourceUtils: No custom resources configured for spark.driver.
[2021-12-29 12:03:48,121] {spark_submit.py:514} INFO - 21/12/29 12:03:48 INFO ResourceUtils: ==============================================================
[2021-12-29 12:03:48,123] {spark_submit.py:514} INFO - 21/12/29 12:03:48 INFO SparkContext: Submitted application: Get Ads per county
[2021-12-29 12:03:48,559] {spark_submit.py:514} INFO - 21/12/29 12:03:48 INFO ResourceProfile: Default ResourceProfile created, executor resources: Map(cores -> name: cores, amount: 1, script: , vendor: , memory -> name: memory, amount: 1024, script: , vendor: , offHeap -> name: offHeap, amount: 0, script: , vendor: ), task resources: Map(cpus -> name: cpus, amount: 1.0)
[2021-12-29 12:03:48,722] {spark_submit.py:514} INFO - 21/12/29 12:03:48 INFO ResourceProfile: Limiting resource is cpu
[2021-12-29 12:03:48,730] {spark_submit.py:514} INFO - 21/12/29 12:03:48 INFO ResourceProfileManager: Added ResourceProfile id: 0
[2021-12-29 12:03:49,466] {spark_submit.py:514} INFO - 21/12/29 12:03:49 INFO SecurityManager: Changing view acls to: ***
[2021-12-29 12:03:49,468] {spark_submit.py:514} INFO - 21/12/29 12:03:49 INFO SecurityManager: Changing modify acls to: ***
[2021-12-29 12:03:49,470] {spark_submit.py:514} INFO - 21/12/29 12:03:49 INFO SecurityManager: Changing view acls groups to:
[2021-12-29 12:03:49,476] {spark_submit.py:514} INFO - 21/12/29 12:03:49 INFO SecurityManager: Changing modify acls groups to:
[2021-12-29 12:03:49,478] {spark_submit.py:514} INFO - 21/12/29 12:03:49 INFO SecurityManager: SecurityManager: authentication disabled; ui acls disabled; users  with view permissions: Set(***); groups with view permissions: Set(); users  with modify permissions: Set(***); groups with modify permissions: Set()
[2021-12-29 12:03:52,870] {spark_submit.py:514} INFO - 21/12/29 12:03:52 INFO Utils: Successfully started service 'sparkDriver' on port 41381.
[2021-12-29 12:03:53,277] {spark_submit.py:514} INFO - 21/12/29 12:03:53 INFO SparkEnv: Registering MapOutputTracker
[2021-12-29 12:03:53,711] {spark_submit.py:514} INFO - 21/12/29 12:03:53 INFO SparkEnv: Registering BlockManagerMaster
[2021-12-29 12:03:53,759] {spark_submit.py:514} INFO - 21/12/29 12:03:53 INFO BlockManagerMasterEndpoint: Using org.apache.spark.storage.DefaultTopologyMapper for getting topology information
[2021-12-29 12:03:53,768] {spark_submit.py:514} INFO - 21/12/29 12:03:53 INFO BlockManagerMasterEndpoint: BlockManagerMasterEndpoint up
[2021-12-29 12:03:53,777] {spark_submit.py:514} INFO - 21/12/29 12:03:53 INFO SparkEnv: Registering BlockManagerMasterHeartbeat
[2021-12-29 12:03:53,874] {spark_submit.py:514} INFO - 21/12/29 12:03:53 INFO DiskBlockManager: Created local directory at /tmp/blockmgr-2179a801-98c6-48ce-8e48-fdf3be829764
[2021-12-29 12:03:54,076] {spark_submit.py:514} INFO - 21/12/29 12:03:54 INFO MemoryStore: MemoryStore started with capacity 434.4 MiB
[2021-12-29 12:03:54,289] {spark_submit.py:514} INFO - 21/12/29 12:03:54 INFO SparkEnv: Registering OutputCommitCoordinator
[2021-12-29 12:03:56,055] {spark_submit.py:514} INFO - 21/12/29 12:03:56 WARN Utils: Service 'SparkUI' could not bind on port 4040. Attempting port 4041.
[2021-12-29 12:03:56,070] {spark_submit.py:514} INFO - 21/12/29 12:03:56 WARN Utils: Service 'SparkUI' could not bind on port 4041. Attempting port 4042.
[2021-12-29 12:03:56,072] {spark_submit.py:514} INFO - 21/12/29 12:03:56 WARN Utils: Service 'SparkUI' could not bind on port 4042. Attempting port 4043.
[2021-12-29 12:03:56,074] {spark_submit.py:514} INFO - 21/12/29 12:03:56 WARN Utils: Service 'SparkUI' could not bind on port 4043. Attempting port 4044.
[2021-12-29 12:03:56,075] {spark_submit.py:514} INFO - 21/12/29 12:03:56 WARN Utils: Service 'SparkUI' could not bind on port 4044. Attempting port 4045.
[2021-12-29 12:03:56,077] {spark_submit.py:514} INFO - 21/12/29 12:03:56 WARN Utils: Service 'SparkUI' could not bind on port 4045. Attempting port 4046.
[2021-12-29 12:03:56,083] {spark_submit.py:514} INFO - 21/12/29 12:03:56 WARN Utils: Service 'SparkUI' could not bind on port 4046. Attempting port 4047.
[2021-12-29 12:03:56,165] {spark_submit.py:514} INFO - 21/12/29 12:03:56 INFO Utils: Successfully started service 'SparkUI' on port 4047.
[2021-12-29 12:03:56,587] {spark_submit.py:514} INFO - 21/12/29 12:03:56 INFO SparkUI: Bound SparkUI to 0.0.0.0, and started at http://6bdda4c19a85:4047
[2021-12-29 12:04:00,258] {spark_submit.py:514} INFO - 21/12/29 12:04:00 INFO StandaloneAppClient$ClientEndpoint: Connecting to master spark://spark:7077...
[2021-12-29 12:04:00,913] {spark_submit.py:514} INFO - 21/12/29 12:04:00 WARN StandaloneAppClient$ClientEndpoint: Failed to connect to master spark:7077
[2021-12-29 12:04:00,915] {spark_submit.py:514} INFO - org.apache.spark.SparkException: Exception thrown in awaitResult:
[2021-12-29 12:04:00,916] {spark_submit.py:514} INFO - at org.apache.spark.util.ThreadUtils$.awaitResult(ThreadUtils.scala:301)
[2021-12-29 12:04:00,918] {spark_submit.py:514} INFO - at org.apache.spark.rpc.RpcTimeout.awaitResult(RpcTimeout.scala:75)
[2021-12-29 12:04:00,919] {spark_submit.py:514} INFO - at org.apache.spark.rpc.RpcEnv.setupEndpointRefByURI(RpcEnv.scala:101)
[2021-12-29 12:04:00,920] {spark_submit.py:514} INFO - at org.apache.spark.rpc.RpcEnv.setupEndpointRef(RpcEnv.scala:109)
[2021-12-29 12:04:00,922] {spark_submit.py:514} INFO - at org.apache.spark.deploy.client.StandaloneAppClient$ClientEndpoint$$anon$1.run(StandaloneAppClient.scala:107)
[2021-12-29 12:04:00,923] {spark_submit.py:514} INFO - at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
[2021-12-29 12:04:00,925] {spark_submit.py:514} INFO - at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
[2021-12-29 12:04:00,926] {spark_submit.py:514} INFO - at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
[2021-12-29 12:04:00,929] {spark_submit.py:514} INFO - at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
[2021-12-29 12:04:00,930] {spark_submit.py:514} INFO - at java.base/java.lang.Thread.run(Thread.java:829)
[2021-12-29 12:04:00,931] {spark_submit.py:514} INFO - Caused by: java.io.IOException: Failed to connect to spark:7077
[2021-12-29 12:04:00,932] {spark_submit.py:514} INFO - at org.apache.spark.network.client.TransportClientFactory.createClient(TransportClientFactory.java:288)
[2021-12-29 12:04:00,933] {spark_submit.py:514} INFO - at org.apache.spark.network.client.TransportClientFactory.createClient(TransportClientFactory.java:218)
[2021-12-29 12:04:00,934] {spark_submit.py:514} INFO - at org.apache.spark.network.client.TransportClientFactory.createClient(TransportClientFactory.java:230)
[2021-12-29 12:04:00,936] {spark_submit.py:514} INFO - at org.apache.spark.rpc.netty.NettyRpcEnv.createClient(NettyRpcEnv.scala:204)
[2021-12-29 12:04:00,937] {spark_submit.py:514} INFO - at org.apache.spark.rpc.netty.Outbox$$anon$1.call(Outbox.scala:202)
[2021-12-29 12:04:00,939] {spark_submit.py:514} INFO - at org.apache.spark.rpc.netty.Outbox$$anon$1.call(Outbox.scala:198)
[2021-12-29 12:04:00,941] {spark_submit.py:514} INFO - ... 4 more
[2021-12-29 12:04:00,943] {spark_submit.py:514} INFO - Caused by: java.net.UnknownHostException: spark
[2021-12-29 12:04:00,945] {spark_submit.py:514} INFO - at java.base/java.net.InetAddress$CachedAddresses.get(InetAddress.java:797)
[2021-12-29 12:04:00,946] {spark_submit.py:514} INFO - at java.base/java.net.InetAddress.getAllByName0(InetAddress.java:1509)
[2021-12-29 12:04:00,947] {spark_submit.py:514} INFO - at java.base/java.net.InetAddress.getAllByName(InetAddress.java:1368)
[2021-12-29 12:04:00,948] {spark_submit.py:514} INFO - at java.base/java.net.InetAddress.getAllByName(InetAddress.java:1302)
[2021-12-29 12:04:00,949] {spark_submit.py:514} INFO - at java.base/java.net.InetAddress.getByName(InetAddress.java:1252)
[2021-12-29 12:04:00,950] {spark_submit.py:514} INFO - at io.netty.util.internal.SocketUtils$8.run(SocketUtils.java:156)
[2021-12-29 12:04:00,951] {spark_submit.py:514} INFO - at io.netty.util.internal.SocketUtils$8.run(SocketUtils.java:153)
[2021-12-29 12:04:00,954] {spark_submit.py:514} INFO - at java.base/java.security.AccessController.doPrivileged(Native Method)
[2021-12-29 12:04:00,955] {spark_submit.py:514} INFO - at io.netty.util.internal.SocketUtils.addressByName(SocketUtils.java:153)
[2021-12-29 12:04:00,956] {spark_submit.py:514} INFO - at io.netty.resolver.DefaultNameResolver.doResolve(DefaultNameResolver.java:41)
[2021-12-29 12:04:00,959] {spark_submit.py:514} INFO - at io.netty.resolver.SimpleNameResolver.resolve(SimpleNameResolver.java:61)
[2021-12-29 12:04:00,960] {spark_submit.py:514} INFO - at io.netty.resolver.SimpleNameResolver.resolve(SimpleNameResolver.java:53)
[2021-12-29 12:04:00,961] {spark_submit.py:514} INFO - at io.netty.resolver.InetSocketAddressResolver.doResolve(InetSocketAddressResolver.java:55)
[2021-12-29 12:04:00,963] {spark_submit.py:514} INFO - at io.netty.resolver.InetSocketAddressResolver.doResolve(InetSocketAddressResolver.java:31)
[2021-12-29 12:04:00,964] {spark_submit.py:514} INFO - at io.netty.resolver.AbstractAddressResolver.resolve(AbstractAddressResolver.java:106)
[2021-12-29 12:04:00,965] {spark_submit.py:514} INFO - at io.netty.bootstrap.Bootstrap.doResolveAndConnect0(Bootstrap.java:206)
[2021-12-29 12:04:00,966] {spark_submit.py:514} INFO - at io.netty.bootstrap.Bootstrap.access$000(Bootstrap.java:46)
[2021-12-29 12:04:00,967] {spark_submit.py:514} INFO - at io.netty.bootstrap.Bootstrap$1.operationComplete(Bootstrap.java:180)
[2021-12-29 12:04:00,968] {spark_submit.py:514} INFO - at io.netty.bootstrap.Bootstrap$1.operationComplete(Bootstrap.java:166)
[2021-12-29 12:04:00,970] {spark_submit.py:514} INFO - at io.netty.util.concurrent.DefaultPromise.notifyListener0(DefaultPromise.java:578)
[2021-12-29 12:04:00,971] {spark_submit.py:514} INFO - at io.netty.util.concurrent.DefaultPromise.notifyListenersNow(DefaultPromise.java:552)
[2021-12-29 12:04:00,972] {spark_submit.py:514} INFO - at io.netty.util.concurrent.DefaultPromise.notifyListeners(DefaultPromise.java:491)
[2021-12-29 12:04:00,973] {spark_submit.py:514} INFO - at io.netty.util.concurrent.DefaultPromise.setValue0(DefaultPromise.java:616)
[2021-12-29 12:04:00,974] {spark_submit.py:514} INFO - at io.netty.util.concurrent.DefaultPromise.setSuccess0(DefaultPromise.java:605)
[2021-12-29 12:04:00,975] {spark_submit.py:514} INFO - at io.netty.util.concurrent.DefaultPromise.trySuccess(DefaultPromise.java:104)
[2021-12-29 12:04:00,977] {spark_submit.py:514} INFO - at io.netty.channel.DefaultChannelPromise.trySuccess(DefaultChannelPromise.java:84)
[2021-12-29 12:04:00,978] {spark_submit.py:514} INFO - at io.netty.channel.AbstractChannel$AbstractUnsafe.safeSetSuccess(AbstractChannel.java:1008)
[2021-12-29 12:04:00,980] {spark_submit.py:514} INFO - at io.netty.channel.AbstractChannel$AbstractUnsafe.register0(AbstractChannel.java:516)
[2021-12-29 12:04:00,981] {spark_submit.py:514} INFO - at io.netty.channel.AbstractChannel$AbstractUnsafe.access$200(AbstractChannel.java:429)
[2021-12-29 12:04:00,982] {spark_submit.py:514} INFO - at io.netty.channel.AbstractChannel$AbstractUnsafe$1.run(AbstractChannel.java:486)
[2021-12-29 12:04:00,983] {spark_submit.py:514} INFO - at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:164)
[2021-12-29 12:04:00,985] {spark_submit.py:514} INFO - at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:469)
[2021-12-29 12:04:00,986] {spark_submit.py:514} INFO - at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:500)
[2021-12-29 12:04:00,988] {spark_submit.py:514} INFO - at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:986)
[2021-12-29 12:04:00,989] {spark_submit.py:514} INFO - at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
[2021-12-29 12:04:00,990] {spark_submit.py:514} INFO - at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
[2021-12-29 12:04:00,991] {spark_submit.py:514} INFO - ... 1 more
[2021-12-29 12:04:20,202] {spark_submit.py:514} INFO - 21/12/29 12:04:20 INFO StandaloneAppClient$ClientEndpoint: Connecting to master spark://spark:7077...
[2021-12-29 12:04:20,481] {spark_submit.py:514} INFO - 21/12/29 12:04:20 WARN StandaloneAppClient$ClientEndpoint: Failed to connect to master spark:7077
[2021-12-29 12:04:20,484] {spark_submit.py:514} INFO - org.apache.spark.SparkException: Exception thrown in awaitResult:
[2021-12-29 12:04:20,503] {spark_submit.py:514} INFO - at org.apache.spark.util.ThreadUtils$.awaitResult(ThreadUtils.scala:301)
[2021-12-29 12:04:20,507] {spark_submit.py:514} INFO - at org.apache.spark.rpc.RpcTimeout.awaitResult(RpcTimeout.scala:75)
[2021-12-29 12:04:20,515] {spark_submit.py:514} INFO - at org.apache.spark.rpc.RpcEnv.setupEndpointRefByURI(RpcEnv.scala:101)
[2021-12-29 12:04:20,517] {spark_submit.py:514} INFO - at org.apache.spark.rpc.RpcEnv.setupEndpointRef(RpcEnv.scala:109)
[2021-12-29 12:04:20,519] {spark_submit.py:514} INFO - at org.apache.spark.deploy.client.StandaloneAppClient$ClientEndpoint$$anon$1.run(StandaloneAppClient.scala:107)
[2021-12-29 12:04:20,523] {spark_submit.py:514} INFO - at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
[2021-12-29 12:04:20,529] {spark_submit.py:514} INFO - at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
[2021-12-29 12:04:20,531] {spark_submit.py:514} INFO - at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
[2021-12-29 12:04:20,533] {spark_submit.py:514} INFO - at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
[2021-12-29 12:04:20,534] {spark_submit.py:514} INFO - at java.base/java.lang.Thread.run(Thread.java:829)
[2021-12-29 12:04:20,536] {spark_submit.py:514} INFO - Caused by: java.io.IOException: Failed to connect to spark:7077
[2021-12-29 12:04:20,537] {spark_submit.py:514} INFO - at org.apache.spark.network.client.TransportClientFactory.createClient(TransportClientFactory.java:288)
[2021-12-29 12:04:20,539] {spark_submit.py:514} INFO - at org.apache.spark.network.client.TransportClientFactory.createClient(TransportClientFactory.java:218)
[2021-12-29 12:04:20,540] {spark_submit.py:514} INFO - at org.apache.spark.network.client.TransportClientFactory.createClient(TransportClientFactory.java:230)
[2021-12-29 12:04:20,541] {spark_submit.py:514} INFO - at org.apache.spark.rpc.netty.NettyRpcEnv.createClient(NettyRpcEnv.scala:204)
[2021-12-29 12:04:20,542] {spark_submit.py:514} INFO - at org.apache.spark.rpc.netty.Outbox$$anon$1.call(Outbox.scala:202)
[2021-12-29 12:04:20,543] {spark_submit.py:514} INFO - at org.apache.spark.rpc.netty.Outbox$$anon$1.call(Outbox.scala:198)
[2021-12-29 12:04:20,544] {spark_submit.py:514} INFO - ... 4 more
[2021-12-29 12:04:20,546] {spark_submit.py:514} INFO - Caused by: java.net.UnknownHostException: spark
[2021-12-29 12:04:20,547] {spark_submit.py:514} INFO - at java.base/java.net.InetAddress$CachedAddresses.get(InetAddress.java:797)
[2021-12-29 12:04:20,549] {spark_submit.py:514} INFO - at java.base/java.net.InetAddress.getAllByName0(InetAddress.java:1509)
[2021-12-29 12:04:20,550] {spark_submit.py:514} INFO - at java.base/java.net.InetAddress.getAllByName(InetAddress.java:1368)
[2021-12-29 12:04:20,551] {spark_submit.py:514} INFO - at java.base/java.net.InetAddress.getAllByName(InetAddress.java:1302)
[2021-12-29 12:04:20,553] {spark_submit.py:514} INFO - at java.base/java.net.InetAddress.getByName(InetAddress.java:1252)
[2021-12-29 12:04:20,554] {spark_submit.py:514} INFO - at io.netty.util.internal.SocketUtils$8.run(SocketUtils.java:156)
[2021-12-29 12:04:20,555] {spark_submit.py:514} INFO - at io.netty.util.internal.SocketUtils$8.run(SocketUtils.java:153)
[2021-12-29 12:04:20,557] {spark_submit.py:514} INFO - at java.base/java.security.AccessController.doPrivileged(Native Method)
[2021-12-29 12:04:20,558] {spark_submit.py:514} INFO - at io.netty.util.internal.SocketUtils.addressByName(SocketUtils.java:153)
[2021-12-29 12:04:20,559] {spark_submit.py:514} INFO - at io.netty.resolver.DefaultNameResolver.doResolve(DefaultNameResolver.java:41)
[2021-12-29 12:04:20,561] {spark_submit.py:514} INFO - at io.netty.resolver.SimpleNameResolver.resolve(SimpleNameResolver.java:61)
[2021-12-29 12:04:20,562] {spark_submit.py:514} INFO - at io.netty.resolver.SimpleNameResolver.resolve(SimpleNameResolver.java:53)
[2021-12-29 12:04:20,563] {spark_submit.py:514} INFO - at io.netty.resolver.InetSocketAddressResolver.doResolve(InetSocketAddressResolver.java:55)
[2021-12-29 12:04:20,566] {spark_submit.py:514} INFO - at io.netty.resolver.InetSocketAddressResolver.doResolve(InetSocketAddressResolver.java:31)
[2021-12-29 12:04:20,568] {spark_submit.py:514} INFO - at io.netty.resolver.AbstractAddressResolver.resolve(AbstractAddressResolver.java:106)
[2021-12-29 12:04:20,569] {spark_submit.py:514} INFO - at io.netty.bootstrap.Bootstrap.doResolveAndConnect0(Bootstrap.java:206)
[2021-12-29 12:04:20,571] {spark_submit.py:514} INFO - at io.netty.bootstrap.Bootstrap.access$000(Bootstrap.java:46)
[2021-12-29 12:04:20,577] {spark_submit.py:514} INFO - at io.netty.bootstrap.Bootstrap$1.operationComplete(Bootstrap.java:180)
[2021-12-29 12:04:20,582] {spark_submit.py:514} INFO - at io.netty.bootstrap.Bootstrap$1.operationComplete(Bootstrap.java:166)
[2021-12-29 12:04:20,587] {spark_submit.py:514} INFO - at io.netty.util.concurrent.DefaultPromise.notifyListener0(DefaultPromise.java:578)
[2021-12-29 12:04:20,589] {spark_submit.py:514} INFO - at io.netty.util.concurrent.DefaultPromise.notifyListenersNow(DefaultPromise.java:552)
[2021-12-29 12:04:20,591] {spark_submit.py:514} INFO - at io.netty.util.concurrent.DefaultPromise.notifyListeners(DefaultPromise.java:491)
[2021-12-29 12:04:20,592] {spark_submit.py:514} INFO - at io.netty.util.concurrent.DefaultPromise.setValue0(DefaultPromise.java:616)
[2021-12-29 12:04:20,593] {spark_submit.py:514} INFO - at io.netty.util.concurrent.DefaultPromise.setSuccess0(DefaultPromise.java:605)
[2021-12-29 12:04:20,594] {spark_submit.py:514} INFO - at io.netty.util.concurrent.DefaultPromise.trySuccess(DefaultPromise.java:104)
[2021-12-29 12:04:20,595] {spark_submit.py:514} INFO - at io.netty.channel.DefaultChannelPromise.trySuccess(DefaultChannelPromise.java:84)
[2021-12-29 12:04:20,596] {spark_submit.py:514} INFO - at io.netty.channel.AbstractChannel$AbstractUnsafe.safeSetSuccess(AbstractChannel.java:1008)
[2021-12-29 12:04:20,597] {spark_submit.py:514} INFO - at io.netty.channel.AbstractChannel$AbstractUnsafe.register0(AbstractChannel.java:516)
[2021-12-29 12:04:20,598] {spark_submit.py:514} INFO - at io.netty.channel.AbstractChannel$AbstractUnsafe.access$200(AbstractChannel.java:429)
[2021-12-29 12:04:20,600] {spark_submit.py:514} INFO - at io.netty.channel.AbstractChannel$AbstractUnsafe$1.run(AbstractChannel.java:486)
[2021-12-29 12:04:20,601] {spark_submit.py:514} INFO - at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:164)
[2021-12-29 12:04:20,602] {spark_submit.py:514} INFO - at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:469)
[2021-12-29 12:04:20,604] {spark_submit.py:514} INFO - at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:500)
[2021-12-29 12:04:20,605] {spark_submit.py:514} INFO - at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:986)
[2021-12-29 12:04:20,607] {spark_submit.py:514} INFO - at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
[2021-12-29 12:04:20,609] {spark_submit.py:514} INFO - at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
[2021-12-29 12:04:20,610] {spark_submit.py:514} INFO - ... 1 more
[2021-12-29 12:04:40,153] {spark_submit.py:514} INFO - 21/12/29 12:04:40 INFO StandaloneAppClient$ClientEndpoint: Connecting to master spark://spark:7077...
[2021-12-29 12:04:40,198] {spark_submit.py:514} INFO - 21/12/29 12:04:40 WARN StandaloneAppClient$ClientEndpoint: Failed to connect to master spark:7077
[2021-12-29 12:04:40,203] {spark_submit.py:514} INFO - org.apache.spark.SparkException: Exception thrown in awaitResult:
[2021-12-29 12:04:40,205] {spark_submit.py:514} INFO - at org.apache.spark.util.ThreadUtils$.awaitResult(ThreadUtils.scala:301)
[2021-12-29 12:04:40,210] {spark_submit.py:514} INFO - at org.apache.spark.rpc.RpcTimeout.awaitResult(RpcTimeout.scala:75)
[2021-12-29 12:04:40,214] {spark_submit.py:514} INFO - at org.apache.spark.rpc.RpcEnv.setupEndpointRefByURI(RpcEnv.scala:101)
[2021-12-29 12:04:40,224] {spark_submit.py:514} INFO - at org.apache.spark.rpc.RpcEnv.setupEndpointRef(RpcEnv.scala:109)
[2021-12-29 12:04:40,226] {spark_submit.py:514} INFO - at org.apache.spark.deploy.client.StandaloneAppClient$ClientEndpoint$$anon$1.run(StandaloneAppClient.scala:107)
[2021-12-29 12:04:40,227] {spark_submit.py:514} INFO - at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
[2021-12-29 12:04:40,228] {spark_submit.py:514} INFO - at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
[2021-12-29 12:04:40,230] {spark_submit.py:514} INFO - at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
[2021-12-29 12:04:40,231] {spark_submit.py:514} INFO - at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
[2021-12-29 12:04:40,232] {spark_submit.py:514} INFO - at java.base/java.lang.Thread.run(Thread.java:829)
[2021-12-29 12:04:40,233] {spark_submit.py:514} INFO - Caused by: java.io.IOException: Failed to connect to spark:7077
[2021-12-29 12:04:40,234] {spark_submit.py:514} INFO - at org.apache.spark.network.client.TransportClientFactory.createClient(TransportClientFactory.java:288)
[2021-12-29 12:04:40,235] {spark_submit.py:514} INFO - at org.apache.spark.network.client.TransportClientFactory.createClient(TransportClientFactory.java:218)
[2021-12-29 12:04:40,237] {spark_submit.py:514} INFO - at org.apache.spark.network.client.TransportClientFactory.createClient(TransportClientFactory.java:230)
[2021-12-29 12:04:40,238] {spark_submit.py:514} INFO - at org.apache.spark.rpc.netty.NettyRpcEnv.createClient(NettyRpcEnv.scala:204)
[2021-12-29 12:04:40,239] {spark_submit.py:514} INFO - at org.apache.spark.rpc.netty.Outbox$$anon$1.call(Outbox.scala:202)
[2021-12-29 12:04:40,240] {spark_submit.py:514} INFO - at org.apache.spark.rpc.netty.Outbox$$anon$1.call(Outbox.scala:198)
[2021-12-29 12:04:40,241] {spark_submit.py:514} INFO - ... 4 more
[2021-12-29 12:04:40,243] {spark_submit.py:514} INFO - Caused by: java.net.UnknownHostException: spark
[2021-12-29 12:04:40,244] {spark_submit.py:514} INFO - at java.base/java.net.InetAddress$CachedAddresses.get(InetAddress.java:797)
[2021-12-29 12:04:40,245] {spark_submit.py:514} INFO - at java.base/java.net.InetAddress.getAllByName0(InetAddress.java:1509)
[2021-12-29 12:04:40,246] {spark_submit.py:514} INFO - at java.base/java.net.InetAddress.getAllByName(InetAddress.java:1368)
[2021-12-29 12:04:40,247] {spark_submit.py:514} INFO - at java.base/java.net.InetAddress.getAllByName(InetAddress.java:1302)
[2021-12-29 12:04:40,248] {spark_submit.py:514} INFO - at java.base/java.net.InetAddress.getByName(InetAddress.java:1252)
[2021-12-29 12:04:40,249] {spark_submit.py:514} INFO - at io.netty.util.internal.SocketUtils$8.run(SocketUtils.java:156)
[2021-12-29 12:04:40,250] {spark_submit.py:514} INFO - at io.netty.util.internal.SocketUtils$8.run(SocketUtils.java:153)
[2021-12-29 12:04:40,251] {spark_submit.py:514} INFO - at java.base/java.security.AccessController.doPrivileged(Native Method)
[2021-12-29 12:04:40,252] {spark_submit.py:514} INFO - at io.netty.util.internal.SocketUtils.addressByName(SocketUtils.java:153)
[2021-12-29 12:04:40,253] {spark_submit.py:514} INFO - at io.netty.resolver.DefaultNameResolver.doResolve(DefaultNameResolver.java:41)
[2021-12-29 12:04:40,254] {spark_submit.py:514} INFO - at io.netty.resolver.SimpleNameResolver.resolve(SimpleNameResolver.java:61)
[2021-12-29 12:04:40,255] {spark_submit.py:514} INFO - at io.netty.resolver.SimpleNameResolver.resolve(SimpleNameResolver.java:53)
[2021-12-29 12:04:40,256] {spark_submit.py:514} INFO - at io.netty.resolver.InetSocketAddressResolver.doResolve(InetSocketAddressResolver.java:55)
[2021-12-29 12:04:40,257] {spark_submit.py:514} INFO - at io.netty.resolver.InetSocketAddressResolver.doResolve(InetSocketAddressResolver.java:31)
[2021-12-29 12:04:40,258] {spark_submit.py:514} INFO - at io.netty.resolver.AbstractAddressResolver.resolve(AbstractAddressResolver.java:106)
[2021-12-29 12:04:40,259] {spark_submit.py:514} INFO - at io.netty.bootstrap.Bootstrap.doResolveAndConnect0(Bootstrap.java:206)
[2021-12-29 12:04:40,261] {spark_submit.py:514} INFO - at io.netty.bootstrap.Bootstrap.access$000(Bootstrap.java:46)
[2021-12-29 12:04:40,262] {spark_submit.py:514} INFO - at io.netty.bootstrap.Bootstrap$1.operationComplete(Bootstrap.java:180)
[2021-12-29 12:04:40,263] {spark_submit.py:514} INFO - at io.netty.bootstrap.Bootstrap$1.operationComplete(Bootstrap.java:166)
[2021-12-29 12:04:40,264] {spark_submit.py:514} INFO - at io.netty.util.concurrent.DefaultPromise.notifyListener0(DefaultPromise.java:578)
[2021-12-29 12:04:40,265] {spark_submit.py:514} INFO - at io.netty.util.concurrent.DefaultPromise.notifyListenersNow(DefaultPromise.java:552)
[2021-12-29 12:04:40,266] {spark_submit.py:514} INFO - at io.netty.util.concurrent.DefaultPromise.notifyListeners(DefaultPromise.java:491)
[2021-12-29 12:04:40,267] {spark_submit.py:514} INFO - at io.netty.util.concurrent.DefaultPromise.setValue0(DefaultPromise.java:616)
[2021-12-29 12:04:40,268] {spark_submit.py:514} INFO - at io.netty.util.concurrent.DefaultPromise.setSuccess0(DefaultPromise.java:605)
[2021-12-29 12:04:40,269] {spark_submit.py:514} INFO - at io.netty.util.concurrent.DefaultPromise.trySuccess(DefaultPromise.java:104)
[2021-12-29 12:04:40,271] {spark_submit.py:514} INFO - at io.netty.channel.DefaultChannelPromise.trySuccess(DefaultChannelPromise.java:84)
[2021-12-29 12:04:40,272] {spark_submit.py:514} INFO - at io.netty.channel.AbstractChannel$AbstractUnsafe.safeSetSuccess(AbstractChannel.java:1008)
[2021-12-29 12:04:40,273] {spark_submit.py:514} INFO - at io.netty.channel.AbstractChannel$AbstractUnsafe.register0(AbstractChannel.java:516)
[2021-12-29 12:04:40,274] {spark_submit.py:514} INFO - at io.netty.channel.AbstractChannel$AbstractUnsafe.access$200(AbstractChannel.java:429)
[2021-12-29 12:04:40,276] {spark_submit.py:514} INFO - at io.netty.channel.AbstractChannel$AbstractUnsafe$1.run(AbstractChannel.java:486)
[2021-12-29 12:04:40,277] {spark_submit.py:514} INFO - at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:164)
[2021-12-29 12:04:40,278] {spark_submit.py:514} INFO - at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:469)
[2021-12-29 12:04:40,279] {spark_submit.py:514} INFO - at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:500)
[2021-12-29 12:04:40,280] {spark_submit.py:514} INFO - at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:986)
[2021-12-29 12:04:40,281] {spark_submit.py:514} INFO - at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
[2021-12-29 12:04:40,282] {spark_submit.py:514} INFO - at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
[2021-12-29 12:04:40,283] {spark_submit.py:514} INFO - ... 1 more
[2021-12-29 12:05:00,159] {spark_submit.py:514} INFO - 21/12/29 12:05:00 ERROR StandaloneSchedulerBackend: Application has been killed. Reason: All masters are unresponsive! Giving up.
[2021-12-29 12:05:00,173] {spark_submit.py:514} INFO - 21/12/29 12:05:00 WARN StandaloneSchedulerBackend: Application ID is not initialized yet.
[2021-12-29 12:05:00,249] {spark_submit.py:514} INFO - 21/12/29 12:05:00 INFO Utils: Successfully started service 'org.apache.spark.network.netty.NettyBlockTransferService' on port 41291.
[2021-12-29 12:05:00,252] {spark_submit.py:514} INFO - 21/12/29 12:05:00 INFO NettyBlockTransferService: Server created on 6bdda4c19a85:41291
[2021-12-29 12:05:00,255] {spark_submit.py:514} INFO - 21/12/29 12:05:00 INFO BlockManager: Using org.apache.spark.storage.RandomBlockReplicationPolicy for block replication policy
[2021-12-29 12:05:00,353] {spark_submit.py:514} INFO - 21/12/29 12:05:00 INFO SparkUI: Stopped Spark web UI at http://6bdda4c19a85:4047
[2021-12-29 12:05:00,362] {spark_submit.py:514} INFO - 21/12/29 12:05:00 INFO BlockManagerMaster: Registering BlockManager BlockManagerId(driver, 6bdda4c19a85, 41291, None)
[2021-12-29 12:05:00,379] {spark_submit.py:514} INFO - 21/12/29 12:05:00 INFO StandaloneSchedulerBackend: Shutting down all executors
[2021-12-29 12:05:00,397] {spark_submit.py:514} INFO - 21/12/29 12:05:00 INFO CoarseGrainedSchedulerBackend$DriverEndpoint: Asking each executor to shut down
[2021-12-29 12:05:00,400] {spark_submit.py:514} INFO - 21/12/29 12:05:00 INFO BlockManagerMasterEndpoint: Registering block manager 6bdda4c19a85:41291 with 434.4 MiB RAM, BlockManagerId(driver, 6bdda4c19a85, 41291, None)
[2021-12-29 12:05:00,412] {spark_submit.py:514} INFO - 21/12/29 12:05:00 INFO BlockManagerMaster: Registered BlockManager BlockManagerId(driver, 6bdda4c19a85, 41291, None)
[2021-12-29 12:05:00,427] {spark_submit.py:514} INFO - 21/12/29 12:05:00 INFO BlockManager: Initialized BlockManager: BlockManagerId(driver, 6bdda4c19a85, 41291, None)
[2021-12-29 12:05:00,461] {spark_submit.py:514} INFO - 21/12/29 12:05:00 WARN StandaloneAppClient$ClientEndpoint: Drop UnregisterApplication(null) because has not yet connected to master
[2021-12-29 12:05:00,719] {spark_submit.py:514} INFO - 21/12/29 12:05:00 INFO MapOutputTrackerMasterEndpoint: MapOutputTrackerMasterEndpoint stopped!
[2021-12-29 12:05:01,152] {spark_submit.py:514} INFO - 21/12/29 12:05:01 INFO MemoryStore: MemoryStore cleared
[2021-12-29 12:05:01,164] {spark_submit.py:514} INFO - 21/12/29 12:05:01 INFO BlockManager: BlockManager stopped
[2021-12-29 12:05:01,227] {spark_submit.py:514} INFO - 21/12/29 12:05:01 INFO BlockManagerMaster: BlockManagerMaster stopped
[2021-12-29 12:05:01,244] {spark_submit.py:514} INFO - 21/12/29 12:05:01 INFO OutputCommitCoordinator$OutputCommitCoordinatorEndpoint: OutputCommitCoordinator stopped!
[2021-12-29 12:05:01,434] {spark_submit.py:514} INFO - 21/12/29 12:05:01 INFO SparkContext: Successfully stopped SparkContext
[2021-12-29 12:05:02,022] {spark_submit.py:514} INFO - 21/12/29 12:05:02 ERROR SparkContext: Error initializing SparkContext.
[2021-12-29 12:05:02,024] {spark_submit.py:514} INFO - java.lang.IllegalArgumentException: requirement failed: Can only call getServletHandlers on a running MetricsSystem
[2021-12-29 12:05:02,025] {spark_submit.py:514} INFO - at scala.Predef$.require(Predef.scala:281)
[2021-12-29 12:05:02,027] {spark_submit.py:514} INFO - at org.apache.spark.metrics.MetricsSystem.getServletHandlers(MetricsSystem.scala:89)
[2021-12-29 12:05:02,028] {spark_submit.py:514} INFO - at org.apache.spark.SparkContext.<init>(SparkContext.scala:603)
[2021-12-29 12:05:02,029] {spark_submit.py:514} INFO - at org.apache.spark.api.java.JavaSparkContext.<init>(JavaSparkContext.scala:58)
[2021-12-29 12:05:02,030] {spark_submit.py:514} INFO - at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
[2021-12-29 12:05:02,032] {spark_submit.py:514} INFO - at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
[2021-12-29 12:05:02,033] {spark_submit.py:514} INFO - at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
[2021-12-29 12:05:02,035] {spark_submit.py:514} INFO - at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:490)
[2021-12-29 12:05:02,037] {spark_submit.py:514} INFO - at py4j.reflection.MethodInvoker.invoke(MethodInvoker.java:247)
[2021-12-29 12:05:02,038] {spark_submit.py:514} INFO - at py4j.reflection.ReflectionEngine.invoke(ReflectionEngine.java:357)
[2021-12-29 12:05:02,039] {spark_submit.py:514} INFO - at py4j.Gateway.invoke(Gateway.java:238)
[2021-12-29 12:05:02,041] {spark_submit.py:514} INFO - at py4j.commands.ConstructorCommand.invokeConstructor(ConstructorCommand.java:80)
[2021-12-29 12:05:02,043] {spark_submit.py:514} INFO - at py4j.commands.ConstructorCommand.execute(ConstructorCommand.java:69)
[2021-12-29 12:05:02,044] {spark_submit.py:514} INFO - at py4j.ClientServerConnection.waitForCommands(ClientServerConnection.java:182)
[2021-12-29 12:05:02,046] {spark_submit.py:514} INFO - at py4j.ClientServerConnection.run(ClientServerConnection.java:106)
[2021-12-29 12:05:02,048] {spark_submit.py:514} INFO - at java.base/java.lang.Thread.run(Thread.java:829)
[2021-12-29 12:05:02,050] {spark_submit.py:514} INFO - 21/12/29 12:05:02 INFO SparkContext: SparkContext already stopped.
[2021-12-29 12:05:02,052] {spark_submit.py:514} INFO - Traceback (most recent call last):
[2021-12-29 12:05:02,053] {spark_submit.py:514} INFO - File "/opt/***/jobs/get_ads_per_county.py", line 13, in <module>
[2021-12-29 12:05:02,054] {spark_submit.py:514} INFO - .appName("Get Ads per county") \
[2021-12-29 12:05:02,055] {spark_submit.py:514} INFO - File "/home/***/.local/lib/python3.6/site-packages/pyspark/python/lib/pyspark.zip/pyspark/sql/session.py", line 228, in getOrCreate
[2021-12-29 12:05:02,057] {spark_submit.py:514} INFO - File "/home/***/.local/lib/python3.6/site-packages/pyspark/python/lib/pyspark.zip/pyspark/context.py", line 392, in getOrCreate
[2021-12-29 12:05:02,060] {spark_submit.py:514} INFO - File "/home/***/.local/lib/python3.6/site-packages/pyspark/python/lib/pyspark.zip/pyspark/context.py", line 147, in __init__
[2021-12-29 12:05:02,068] {spark_submit.py:514} INFO - File "/home/***/.local/lib/python3.6/site-packages/pyspark/python/lib/pyspark.zip/pyspark/context.py", line 209, in _do_init
[2021-12-29 12:05:02,069] {spark_submit.py:514} INFO - File "/home/***/.local/lib/python3.6/site-packages/pyspark/python/lib/pyspark.zip/pyspark/context.py", line 329, in _initialize_context
[2021-12-29 12:05:02,070] {spark_submit.py:514} INFO - File "/home/***/.local/lib/python3.6/site-packages/pyspark/python/lib/py4j-0.10.9.2-src.zip/py4j/java_gateway.py", line 1574, in __call__
[2021-12-29 12:05:02,072] {spark_submit.py:514} INFO - File "/home/***/.local/lib/python3.6/site-packages/pyspark/python/lib/py4j-0.10.9.2-src.zip/py4j/protocol.py", line 328, in get_return_value
[2021-12-29 12:05:02,073] {spark_submit.py:514} INFO - py4j.protocol.Py4JJavaError: An error occurred while calling None.org.apache.spark.api.java.JavaSparkContext.
[2021-12-29 12:05:02,075] {spark_submit.py:514} INFO - : java.lang.IllegalArgumentException: requirement failed: Can only call getServletHandlers on a running MetricsSystem
[2021-12-29 12:05:02,077] {spark_submit.py:514} INFO - at scala.Predef$.require(Predef.scala:281)
[2021-12-29 12:05:02,080] {spark_submit.py:514} INFO - at org.apache.spark.metrics.MetricsSystem.getServletHandlers(MetricsSystem.scala:89)
[2021-12-29 12:05:02,082] {spark_submit.py:514} INFO - at org.apache.spark.SparkContext.<init>(SparkContext.scala:603)
[2021-12-29 12:05:02,085] {spark_submit.py:514} INFO - at org.apache.spark.api.java.JavaSparkContext.<init>(JavaSparkContext.scala:58)
[2021-12-29 12:05:02,086] {spark_submit.py:514} INFO - at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
[2021-12-29 12:05:02,087] {spark_submit.py:514} INFO - at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
[2021-12-29 12:05:02,089] {spark_submit.py:514} INFO - at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
[2021-12-29 12:05:02,091] {spark_submit.py:514} INFO - at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:490)
[2021-12-29 12:05:02,093] {spark_submit.py:514} INFO - at py4j.reflection.MethodInvoker.invoke(MethodInvoker.java:247)
[2021-12-29 12:05:02,093] {spark_submit.py:514} INFO - at py4j.reflection.ReflectionEngine.invoke(ReflectionEngine.java:357)
[2021-12-29 12:05:02,094] {spark_submit.py:514} INFO - at py4j.Gateway.invoke(Gateway.java:238)
[2021-12-29 12:05:02,096] {spark_submit.py:514} INFO - at py4j.commands.ConstructorCommand.invokeConstructor(ConstructorCommand.java:80)
[2021-12-29 12:05:02,097] {spark_submit.py:514} INFO - at py4j.commands.ConstructorCommand.execute(ConstructorCommand.java:69)
[2021-12-29 12:05:02,098] {spark_submit.py:514} INFO - at py4j.ClientServerConnection.waitForCommands(ClientServerConnection.java:182)
[2021-12-29 12:05:02,100] {spark_submit.py:514} INFO - at py4j.ClientServerConnection.run(ClientServerConnection.java:106)
[2021-12-29 12:05:02,103] {spark_submit.py:514} INFO - at java.base/java.lang.Thread.run(Thread.java:829)
[2021-12-29 12:05:02,105] {spark_submit.py:514} INFO - 
[2021-12-29 12:05:02,591] {spark_submit.py:514} INFO - 21/12/29 12:05:02 INFO ShutdownHookManager: Shutdown hook called
[2021-12-29 12:05:02,593] {spark_submit.py:514} INFO - 21/12/29 12:05:02 INFO ShutdownHookManager: Deleting directory /tmp/spark-0d38da62-a953-4659-b592-0c94f97bfc3a
[2021-12-29 12:05:02,606] {spark_submit.py:514} INFO - 21/12/29 12:05:02 INFO ShutdownHookManager: Deleting directory /tmp/spark-507ca988-227a-48a9-bf51-3de712ca7337
[2021-12-29 12:05:03,253] {taskinstance.py:1703} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 1332, in _run_raw_task
    self._execute_task_with_callbacks(context)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 1458, in _execute_task_with_callbacks
    result = self._execute_task(context, self.task)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 1514, in _execute_task
    result = execute_callable(context=context)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/providers/apache/spark/operators/spark_submit.py", line 179, in execute
    self._hook.submit(self._application)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/providers/apache/spark/hooks/spark_submit.py", line 446, in submit
    f"Cannot execute: {self._mask_cmd(spark_submit_cmd)}. Error code is: {returncode}."
airflow.exceptions.AirflowException: Cannot execute: spark-submit --master spark://spark:7077 --conf spark.master=spark://spark:7077 --name scrap data --verbose /opt/***/jobs/get_ads_per_county.py laois. Error code is: 1.
[2021-12-29 12:05:03,274] {taskinstance.py:1280} INFO - Marking task as UP_FOR_RETRY. dag_id=scraping_daft_laois, task_id=scrap_data, execution_date=20211228T095500, start_date=20211229T120315, end_date=20211229T120503
[2021-12-29 12:05:03,336] {standard_task_runner.py:91} ERROR - Failed to execute job 5348 for task scrap_data
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/task/task_runner/standard_task_runner.py", line 85, in _start_by_fork
    args.func(args, dag=self.dag)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/cli/cli_parser.py", line 48, in command
    return func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/utils/cli.py", line 92, in wrapper
    return f(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/cli/commands/task_command.py", line 292, in task_run
    _run_task_by_selected_method(args, dag, ti)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/cli/commands/task_command.py", line 107, in _run_task_by_selected_method
    _run_raw_task(args, ti)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/cli/commands/task_command.py", line 184, in _run_raw_task
    error_file=args.error_file,
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/utils/session.py", line 70, in wrapper
    return func(*args, session=session, **kwargs)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 1332, in _run_raw_task
    self._execute_task_with_callbacks(context)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 1458, in _execute_task_with_callbacks
    result = self._execute_task(context, self.task)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 1514, in _execute_task
    result = execute_callable(context=context)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/providers/apache/spark/operators/spark_submit.py", line 179, in execute
    self._hook.submit(self._application)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/providers/apache/spark/hooks/spark_submit.py", line 446, in submit
    f"Cannot execute: {self._mask_cmd(spark_submit_cmd)}. Error code is: {returncode}."
airflow.exceptions.AirflowException: Cannot execute: spark-submit --master spark://spark:7077 --conf spark.master=spark://spark:7077 --name scrap data --verbose /opt/***/jobs/get_ads_per_county.py laois. Error code is: 1.
[2021-12-29 12:05:03,399] {local_task_job.py:154} INFO - Task exited with return code 1
[2021-12-29 12:05:03,691] {local_task_job.py:264} INFO - 0 downstream tasks scheduled from follow-on schedule check
