[2021-12-20 10:32:53,430] {taskinstance.py:1035} INFO - Dependencies all met for <TaskInstance: scraping_daft_longford.scrap_data scheduled__2021-12-19T10:10:00+00:00 [queued]>
[2021-12-20 10:32:53,487] {taskinstance.py:1035} INFO - Dependencies all met for <TaskInstance: scraping_daft_longford.scrap_data scheduled__2021-12-19T10:10:00+00:00 [queued]>
[2021-12-20 10:32:53,489] {taskinstance.py:1241} INFO - 
--------------------------------------------------------------------------------
[2021-12-20 10:32:53,491] {taskinstance.py:1242} INFO - Starting attempt 2 of 4
[2021-12-20 10:32:53,493] {taskinstance.py:1243} INFO - 
--------------------------------------------------------------------------------
[2021-12-20 10:32:53,548] {taskinstance.py:1262} INFO - Executing <Task(SparkSubmitOperator): scrap_data> on 2021-12-19 10:10:00+00:00
[2021-12-20 10:32:53,589] {standard_task_runner.py:76} INFO - Running: ['***', 'tasks', 'run', 'scraping_daft_longford', 'scrap_data', 'scheduled__2021-12-19T10:10:00+00:00', '--job-id', '3408', '--raw', '--subdir', 'DAGS_FOLDER/scraping_daft_longford.py', '--cfg-path', '/tmp/tmpsj__6yek', '--error-file', '/tmp/tmptitrgbbj']
[2021-12-20 10:32:53,597] {standard_task_runner.py:77} INFO - Job 3408: Subtask scrap_data
[2021-12-20 10:32:53,582] {standard_task_runner.py:52} INFO - Started process 2325 to run task
[2021-12-20 10:32:53,814] {logging_mixin.py:109} INFO - Running <TaskInstance: scraping_daft_longford.scrap_data scheduled__2021-12-19T10:10:00+00:00 [running]> on host a35fe600e898
[2021-12-20 10:32:54,075] {taskinstance.py:1429} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_EMAIL=clement.liscoet@gmail.com
AIRFLOW_CTX_DAG_OWNER=clemoni
AIRFLOW_CTX_DAG_ID=scraping_daft_longford
AIRFLOW_CTX_TASK_ID=scrap_data
AIRFLOW_CTX_EXECUTION_DATE=2021-12-19T10:10:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2021-12-19T10:10:00+00:00
[2021-12-20 10:32:54,122] {base.py:79} INFO - Using connection to: id: spark_default. Host: spark://spark:7077, Port: None, Schema: , Login: ***, Password: ***, extra: {}
[2021-12-20 10:32:54,128] {spark_submit.py:360} INFO - Spark-Submit cmd: spark-submit --master spark://spark:7077 --conf spark.master=spark://spark:7077 --name scrap data --verbose /opt/***/jobs/get_ads_per_county.py longford
[2021-12-20 10:33:00,458] {spark_submit.py:514} INFO - Using properties file: null
[2021-12-20 10:33:00,753] {spark_submit.py:514} INFO - WARNING: An illegal reflective access operation has occurred
[2021-12-20 10:33:00,754] {spark_submit.py:514} INFO - WARNING: Illegal reflective access by org.apache.spark.unsafe.Platform (file:/home/***/.local/lib/python3.6/site-packages/pyspark/jars/spark-unsafe_2.12-3.2.0.jar) to constructor java.nio.DirectByteBuffer(long,int)
[2021-12-20 10:33:00,755] {spark_submit.py:514} INFO - WARNING: Please consider reporting this to the maintainers of org.apache.spark.unsafe.Platform
[2021-12-20 10:33:00,756] {spark_submit.py:514} INFO - WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
[2021-12-20 10:33:00,757] {spark_submit.py:514} INFO - WARNING: All illegal access operations will be denied in a future release
[2021-12-20 10:33:01,014] {spark_submit.py:514} INFO - Parsed arguments:
[2021-12-20 10:33:01,016] {spark_submit.py:514} INFO - master                  spark://spark:7077
[2021-12-20 10:33:01,017] {spark_submit.py:514} INFO - deployMode              null
[2021-12-20 10:33:01,018] {spark_submit.py:514} INFO - executorMemory          null
[2021-12-20 10:33:01,019] {spark_submit.py:514} INFO - executorCores           null
[2021-12-20 10:33:01,020] {spark_submit.py:514} INFO - totalExecutorCores      null
[2021-12-20 10:33:01,021] {spark_submit.py:514} INFO - propertiesFile          null
[2021-12-20 10:33:01,022] {spark_submit.py:514} INFO - driverMemory            null
[2021-12-20 10:33:01,023] {spark_submit.py:514} INFO - driverCores             null
[2021-12-20 10:33:01,024] {spark_submit.py:514} INFO - driverExtraClassPath    null
[2021-12-20 10:33:01,025] {spark_submit.py:514} INFO - driverExtraLibraryPath  null
[2021-12-20 10:33:01,027] {spark_submit.py:514} INFO - driverExtraJavaOptions  null
[2021-12-20 10:33:01,028] {spark_submit.py:514} INFO - supervise               false
[2021-12-20 10:33:01,029] {spark_submit.py:514} INFO - queue                   null
[2021-12-20 10:33:01,029] {spark_submit.py:514} INFO - numExecutors            null
[2021-12-20 10:33:01,030] {spark_submit.py:514} INFO - files                   null
[2021-12-20 10:33:01,031] {spark_submit.py:514} INFO - pyFiles                 null
[2021-12-20 10:33:01,032] {spark_submit.py:514} INFO - archives                null
[2021-12-20 10:33:01,033] {spark_submit.py:514} INFO - mainClass               null
[2021-12-20 10:33:01,034] {spark_submit.py:514} INFO - primaryResource         file:/opt/***/jobs/get_ads_per_county.py
[2021-12-20 10:33:01,035] {spark_submit.py:514} INFO - name                    scrap data
[2021-12-20 10:33:01,037] {spark_submit.py:514} INFO - childArgs               [longford]
[2021-12-20 10:33:01,038] {spark_submit.py:514} INFO - jars                    null
[2021-12-20 10:33:01,039] {spark_submit.py:514} INFO - packages                null
[2021-12-20 10:33:01,040] {spark_submit.py:514} INFO - packagesExclusions      null
[2021-12-20 10:33:01,044] {spark_submit.py:514} INFO - repositories            null
[2021-12-20 10:33:01,045] {spark_submit.py:514} INFO - verbose                 true
[2021-12-20 10:33:01,046] {spark_submit.py:514} INFO - 
[2021-12-20 10:33:01,047] {spark_submit.py:514} INFO - Spark properties used, including those specified through
[2021-12-20 10:33:01,048] {spark_submit.py:514} INFO - --conf and those from the properties file null:
[2021-12-20 10:33:01,049] {spark_submit.py:514} INFO - (spark.master,spark://spark:7077)
[2021-12-20 10:33:01,050] {spark_submit.py:514} INFO - 
[2021-12-20 10:33:01,051] {spark_submit.py:514} INFO - 
[2021-12-20 10:33:02,798] {spark_submit.py:514} INFO - Main class:
[2021-12-20 10:33:02,803] {spark_submit.py:514} INFO - org.apache.spark.deploy.PythonRunner
[2021-12-20 10:33:02,808] {spark_submit.py:514} INFO - Arguments:
[2021-12-20 10:33:02,813] {spark_submit.py:514} INFO - file:/opt/***/jobs/get_ads_per_county.py
[2021-12-20 10:33:02,818] {spark_submit.py:514} INFO - null
[2021-12-20 10:33:02,823] {spark_submit.py:514} INFO - longford
[2021-12-20 10:33:02,827] {spark_submit.py:514} INFO - --verbose
[2021-12-20 10:33:02,832] {spark_submit.py:514} INFO - Spark config:
[2021-12-20 10:33:02,833] {spark_submit.py:514} INFO - (spark.app.name,scrap data)
[2021-12-20 10:33:02,834] {spark_submit.py:514} INFO - (spark.master,spark://spark:7077)
[2021-12-20 10:33:02,835] {spark_submit.py:514} INFO - (spark.submit.pyFiles,)
[2021-12-20 10:33:02,836] {spark_submit.py:514} INFO - (spark.submit.deployMode,client)
[2021-12-20 10:33:02,837] {spark_submit.py:514} INFO - Classpath elements:
[2021-12-20 10:33:02,841] {spark_submit.py:514} INFO - 
[2021-12-20 10:33:02,842] {spark_submit.py:514} INFO - 
[2021-12-20 10:33:02,843] {spark_submit.py:514} INFO - 
[2021-12-20 10:33:05,068] {spark_submit.py:514} INFO - Using Spark's default log4j profile: org/apache/spark/log4j-defaults.properties
[2021-12-20 10:33:05,097] {spark_submit.py:514} INFO - 21/12/20 10:33:05 INFO SparkContext: Running Spark version 3.2.0
[2021-12-20 10:33:05,389] {spark_submit.py:514} INFO - 21/12/20 10:33:05 WARN NativeCodeLoader: Unable to load native-hadoop library for your platform... using builtin-java classes where applicable
[2021-12-20 10:33:05,937] {spark_submit.py:514} INFO - 21/12/20 10:33:05 INFO ResourceUtils: ==============================================================
[2021-12-20 10:33:05,941] {spark_submit.py:514} INFO - 21/12/20 10:33:05 INFO ResourceUtils: No custom resources configured for spark.driver.
[2021-12-20 10:33:05,944] {spark_submit.py:514} INFO - 21/12/20 10:33:05 INFO ResourceUtils: ==============================================================
[2021-12-20 10:33:05,946] {spark_submit.py:514} INFO - 21/12/20 10:33:05 INFO SparkContext: Submitted application: Get Ads per county
[2021-12-20 10:33:06,094] {spark_submit.py:514} INFO - 21/12/20 10:33:06 INFO ResourceProfile: Default ResourceProfile created, executor resources: Map(cores -> name: cores, amount: 1, script: , vendor: , memory -> name: memory, amount: 1024, script: , vendor: , offHeap -> name: offHeap, amount: 0, script: , vendor: ), task resources: Map(cpus -> name: cpus, amount: 1.0)
[2021-12-20 10:33:06,145] {spark_submit.py:514} INFO - 21/12/20 10:33:06 INFO ResourceProfile: Limiting resource is cpu
[2021-12-20 10:33:06,153] {spark_submit.py:514} INFO - 21/12/20 10:33:06 INFO ResourceProfileManager: Added ResourceProfile id: 0
[2021-12-20 10:33:06,314] {spark_submit.py:514} INFO - 21/12/20 10:33:06 INFO SecurityManager: Changing view acls to: ***
[2021-12-20 10:33:06,316] {spark_submit.py:514} INFO - 21/12/20 10:33:06 INFO SecurityManager: Changing modify acls to: ***
[2021-12-20 10:33:06,318] {spark_submit.py:514} INFO - 21/12/20 10:33:06 INFO SecurityManager: Changing view acls groups to:
[2021-12-20 10:33:06,319] {spark_submit.py:514} INFO - 21/12/20 10:33:06 INFO SecurityManager: Changing modify acls groups to:
[2021-12-20 10:33:06,320] {spark_submit.py:514} INFO - 21/12/20 10:33:06 INFO SecurityManager: SecurityManager: authentication disabled; ui acls disabled; users  with view permissions: Set(***); groups with view permissions: Set(); users  with modify permissions: Set(***); groups with modify permissions: Set()
[2021-12-20 10:33:07,420] {spark_submit.py:514} INFO - 21/12/20 10:33:07 INFO Utils: Successfully started service 'sparkDriver' on port 41081.
[2021-12-20 10:33:07,516] {spark_submit.py:514} INFO - 21/12/20 10:33:07 INFO SparkEnv: Registering MapOutputTracker
[2021-12-20 10:33:07,613] {spark_submit.py:514} INFO - 21/12/20 10:33:07 INFO SparkEnv: Registering BlockManagerMaster
[2021-12-20 10:33:07,651] {spark_submit.py:514} INFO - 21/12/20 10:33:07 INFO BlockManagerMasterEndpoint: Using org.apache.spark.storage.DefaultTopologyMapper for getting topology information
[2021-12-20 10:33:07,652] {spark_submit.py:514} INFO - 21/12/20 10:33:07 INFO BlockManagerMasterEndpoint: BlockManagerMasterEndpoint up
[2021-12-20 10:33:07,665] {spark_submit.py:514} INFO - 21/12/20 10:33:07 INFO SparkEnv: Registering BlockManagerMasterHeartbeat
[2021-12-20 10:33:07,732] {spark_submit.py:514} INFO - 21/12/20 10:33:07 INFO DiskBlockManager: Created local directory at /tmp/blockmgr-1c10f8e6-6686-4e16-8b26-9839918ac418
[2021-12-20 10:33:07,776] {spark_submit.py:514} INFO - 21/12/20 10:33:07 INFO MemoryStore: MemoryStore started with capacity 434.4 MiB
[2021-12-20 10:33:07,824] {spark_submit.py:514} INFO - 21/12/20 10:33:07 INFO SparkEnv: Registering OutputCommitCoordinator
[2021-12-20 10:33:08,291] {spark_submit.py:514} INFO - 21/12/20 10:33:08 WARN Utils: Service 'SparkUI' could not bind on port 4040. Attempting port 4041.
[2021-12-20 10:33:08,292] {spark_submit.py:514} INFO - 21/12/20 10:33:08 WARN Utils: Service 'SparkUI' could not bind on port 4041. Attempting port 4042.
[2021-12-20 10:33:08,294] {spark_submit.py:514} INFO - 21/12/20 10:33:08 WARN Utils: Service 'SparkUI' could not bind on port 4042. Attempting port 4043.
[2021-12-20 10:33:08,295] {spark_submit.py:514} INFO - 21/12/20 10:33:08 WARN Utils: Service 'SparkUI' could not bind on port 4043. Attempting port 4044.
[2021-12-20 10:33:08,296] {spark_submit.py:514} INFO - 21/12/20 10:33:08 WARN Utils: Service 'SparkUI' could not bind on port 4044. Attempting port 4045.
[2021-12-20 10:33:08,297] {spark_submit.py:514} INFO - 21/12/20 10:33:08 WARN Utils: Service 'SparkUI' could not bind on port 4045. Attempting port 4046.
[2021-12-20 10:33:08,298] {spark_submit.py:514} INFO - 21/12/20 10:33:08 WARN Utils: Service 'SparkUI' could not bind on port 4046. Attempting port 4047.
[2021-12-20 10:33:08,310] {spark_submit.py:514} INFO - 21/12/20 10:33:08 INFO Utils: Successfully started service 'SparkUI' on port 4047.
[2021-12-20 10:33:08,419] {spark_submit.py:514} INFO - 21/12/20 10:33:08 INFO SparkUI: Bound SparkUI to 0.0.0.0, and started at http://a35fe600e898:4047
[2021-12-20 10:33:08,839] {spark_submit.py:514} INFO - 21/12/20 10:33:08 INFO StandaloneAppClient$ClientEndpoint: Connecting to master spark://spark:7077...
[2021-12-20 10:33:09,004] {spark_submit.py:514} INFO - 21/12/20 10:33:08 WARN StandaloneAppClient$ClientEndpoint: Failed to connect to master spark:7077
[2021-12-20 10:33:09,005] {spark_submit.py:514} INFO - org.apache.spark.SparkException: Exception thrown in awaitResult:
[2021-12-20 10:33:09,007] {spark_submit.py:514} INFO - at org.apache.spark.util.ThreadUtils$.awaitResult(ThreadUtils.scala:301)
[2021-12-20 10:33:09,008] {spark_submit.py:514} INFO - at org.apache.spark.rpc.RpcTimeout.awaitResult(RpcTimeout.scala:75)
[2021-12-20 10:33:09,009] {spark_submit.py:514} INFO - at org.apache.spark.rpc.RpcEnv.setupEndpointRefByURI(RpcEnv.scala:101)
[2021-12-20 10:33:09,009] {spark_submit.py:514} INFO - at org.apache.spark.rpc.RpcEnv.setupEndpointRef(RpcEnv.scala:109)
[2021-12-20 10:33:09,011] {spark_submit.py:514} INFO - at org.apache.spark.deploy.client.StandaloneAppClient$ClientEndpoint$$anon$1.run(StandaloneAppClient.scala:107)
[2021-12-20 10:33:09,012] {spark_submit.py:514} INFO - at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
[2021-12-20 10:33:09,013] {spark_submit.py:514} INFO - at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
[2021-12-20 10:33:09,014] {spark_submit.py:514} INFO - at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
[2021-12-20 10:33:09,015] {spark_submit.py:514} INFO - at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
[2021-12-20 10:33:09,016] {spark_submit.py:514} INFO - at java.base/java.lang.Thread.run(Thread.java:829)
[2021-12-20 10:33:09,017] {spark_submit.py:514} INFO - Caused by: java.io.IOException: Failed to connect to spark:7077
[2021-12-20 10:33:09,019] {spark_submit.py:514} INFO - at org.apache.spark.network.client.TransportClientFactory.createClient(TransportClientFactory.java:288)
[2021-12-20 10:33:09,019] {spark_submit.py:514} INFO - at org.apache.spark.network.client.TransportClientFactory.createClient(TransportClientFactory.java:218)
[2021-12-20 10:33:09,020] {spark_submit.py:514} INFO - at org.apache.spark.network.client.TransportClientFactory.createClient(TransportClientFactory.java:230)
[2021-12-20 10:33:09,021] {spark_submit.py:514} INFO - at org.apache.spark.rpc.netty.NettyRpcEnv.createClient(NettyRpcEnv.scala:204)
[2021-12-20 10:33:09,023] {spark_submit.py:514} INFO - at org.apache.spark.rpc.netty.Outbox$$anon$1.call(Outbox.scala:202)
[2021-12-20 10:33:09,023] {spark_submit.py:514} INFO - at org.apache.spark.rpc.netty.Outbox$$anon$1.call(Outbox.scala:198)
[2021-12-20 10:33:09,024] {spark_submit.py:514} INFO - ... 4 more
[2021-12-20 10:33:09,025] {spark_submit.py:514} INFO - Caused by: java.net.UnknownHostException: spark
[2021-12-20 10:33:09,026] {spark_submit.py:514} INFO - at java.base/java.net.InetAddress$CachedAddresses.get(InetAddress.java:797)
[2021-12-20 10:33:09,027] {spark_submit.py:514} INFO - at java.base/java.net.InetAddress.getAllByName0(InetAddress.java:1509)
[2021-12-20 10:33:09,028] {spark_submit.py:514} INFO - at java.base/java.net.InetAddress.getAllByName(InetAddress.java:1368)
[2021-12-20 10:33:09,029] {spark_submit.py:514} INFO - at java.base/java.net.InetAddress.getAllByName(InetAddress.java:1302)
[2021-12-20 10:33:09,030] {spark_submit.py:514} INFO - at java.base/java.net.InetAddress.getByName(InetAddress.java:1252)
[2021-12-20 10:33:09,031] {spark_submit.py:514} INFO - at io.netty.util.internal.SocketUtils$8.run(SocketUtils.java:156)
[2021-12-20 10:33:09,033] {spark_submit.py:514} INFO - at io.netty.util.internal.SocketUtils$8.run(SocketUtils.java:153)
[2021-12-20 10:33:09,033] {spark_submit.py:514} INFO - at java.base/java.security.AccessController.doPrivileged(Native Method)
[2021-12-20 10:33:09,034] {spark_submit.py:514} INFO - at io.netty.util.internal.SocketUtils.addressByName(SocketUtils.java:153)
[2021-12-20 10:33:09,035] {spark_submit.py:514} INFO - at io.netty.resolver.DefaultNameResolver.doResolve(DefaultNameResolver.java:41)
[2021-12-20 10:33:09,037] {spark_submit.py:514} INFO - at io.netty.resolver.SimpleNameResolver.resolve(SimpleNameResolver.java:61)
[2021-12-20 10:33:09,038] {spark_submit.py:514} INFO - at io.netty.resolver.SimpleNameResolver.resolve(SimpleNameResolver.java:53)
[2021-12-20 10:33:09,039] {spark_submit.py:514} INFO - at io.netty.resolver.InetSocketAddressResolver.doResolve(InetSocketAddressResolver.java:55)
[2021-12-20 10:33:09,040] {spark_submit.py:514} INFO - at io.netty.resolver.InetSocketAddressResolver.doResolve(InetSocketAddressResolver.java:31)
[2021-12-20 10:33:09,040] {spark_submit.py:514} INFO - at io.netty.resolver.AbstractAddressResolver.resolve(AbstractAddressResolver.java:106)
[2021-12-20 10:33:09,041] {spark_submit.py:514} INFO - at io.netty.bootstrap.Bootstrap.doResolveAndConnect0(Bootstrap.java:206)
[2021-12-20 10:33:09,042] {spark_submit.py:514} INFO - at io.netty.bootstrap.Bootstrap.access$000(Bootstrap.java:46)
[2021-12-20 10:33:09,042] {spark_submit.py:514} INFO - at io.netty.bootstrap.Bootstrap$1.operationComplete(Bootstrap.java:180)
[2021-12-20 10:33:09,043] {spark_submit.py:514} INFO - at io.netty.bootstrap.Bootstrap$1.operationComplete(Bootstrap.java:166)
[2021-12-20 10:33:09,044] {spark_submit.py:514} INFO - at io.netty.util.concurrent.DefaultPromise.notifyListener0(DefaultPromise.java:578)
[2021-12-20 10:33:09,047] {spark_submit.py:514} INFO - at io.netty.util.concurrent.DefaultPromise.notifyListenersNow(DefaultPromise.java:552)
[2021-12-20 10:33:09,049] {spark_submit.py:514} INFO - at io.netty.util.concurrent.DefaultPromise.notifyListeners(DefaultPromise.java:491)
[2021-12-20 10:33:09,050] {spark_submit.py:514} INFO - at io.netty.util.concurrent.DefaultPromise.setValue0(DefaultPromise.java:616)
[2021-12-20 10:33:09,051] {spark_submit.py:514} INFO - at io.netty.util.concurrent.DefaultPromise.setSuccess0(DefaultPromise.java:605)
[2021-12-20 10:33:09,052] {spark_submit.py:514} INFO - at io.netty.util.concurrent.DefaultPromise.trySuccess(DefaultPromise.java:104)
[2021-12-20 10:33:09,053] {spark_submit.py:514} INFO - at io.netty.channel.DefaultChannelPromise.trySuccess(DefaultChannelPromise.java:84)
[2021-12-20 10:33:09,054] {spark_submit.py:514} INFO - at io.netty.channel.AbstractChannel$AbstractUnsafe.safeSetSuccess(AbstractChannel.java:1008)
[2021-12-20 10:33:09,055] {spark_submit.py:514} INFO - at io.netty.channel.AbstractChannel$AbstractUnsafe.register0(AbstractChannel.java:516)
[2021-12-20 10:33:09,055] {spark_submit.py:514} INFO - at io.netty.channel.AbstractChannel$AbstractUnsafe.access$200(AbstractChannel.java:429)
[2021-12-20 10:33:09,056] {spark_submit.py:514} INFO - at io.netty.channel.AbstractChannel$AbstractUnsafe$1.run(AbstractChannel.java:486)
[2021-12-20 10:33:09,057] {spark_submit.py:514} INFO - at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:164)
[2021-12-20 10:33:09,059] {spark_submit.py:514} INFO - at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:469)
[2021-12-20 10:33:09,059] {spark_submit.py:514} INFO - at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:500)
[2021-12-20 10:33:09,060] {spark_submit.py:514} INFO - at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:986)
[2021-12-20 10:33:09,061] {spark_submit.py:514} INFO - at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
[2021-12-20 10:33:09,062] {spark_submit.py:514} INFO - at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
[2021-12-20 10:33:09,063] {spark_submit.py:514} INFO - ... 1 more
[2021-12-20 10:33:28,837] {spark_submit.py:514} INFO - 21/12/20 10:33:28 INFO StandaloneAppClient$ClientEndpoint: Connecting to master spark://spark:7077...
[2021-12-20 10:33:28,850] {spark_submit.py:514} INFO - 21/12/20 10:33:28 WARN StandaloneAppClient$ClientEndpoint: Failed to connect to master spark:7077
[2021-12-20 10:33:28,851] {spark_submit.py:514} INFO - org.apache.spark.SparkException: Exception thrown in awaitResult:
[2021-12-20 10:33:28,853] {spark_submit.py:514} INFO - at org.apache.spark.util.ThreadUtils$.awaitResult(ThreadUtils.scala:301)
[2021-12-20 10:33:28,854] {spark_submit.py:514} INFO - at org.apache.spark.rpc.RpcTimeout.awaitResult(RpcTimeout.scala:75)
[2021-12-20 10:33:28,854] {spark_submit.py:514} INFO - at org.apache.spark.rpc.RpcEnv.setupEndpointRefByURI(RpcEnv.scala:101)
[2021-12-20 10:33:28,855] {spark_submit.py:514} INFO - at org.apache.spark.rpc.RpcEnv.setupEndpointRef(RpcEnv.scala:109)
[2021-12-20 10:33:28,856] {spark_submit.py:514} INFO - at org.apache.spark.deploy.client.StandaloneAppClient$ClientEndpoint$$anon$1.run(StandaloneAppClient.scala:107)
[2021-12-20 10:33:28,857] {spark_submit.py:514} INFO - at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
[2021-12-20 10:33:28,858] {spark_submit.py:514} INFO - at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
[2021-12-20 10:33:28,858] {spark_submit.py:514} INFO - at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
[2021-12-20 10:33:28,859] {spark_submit.py:514} INFO - at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
[2021-12-20 10:33:28,860] {spark_submit.py:514} INFO - at java.base/java.lang.Thread.run(Thread.java:829)
[2021-12-20 10:33:28,861] {spark_submit.py:514} INFO - Caused by: java.io.IOException: Failed to connect to spark:7077
[2021-12-20 10:33:28,862] {spark_submit.py:514} INFO - at org.apache.spark.network.client.TransportClientFactory.createClient(TransportClientFactory.java:288)
[2021-12-20 10:33:28,862] {spark_submit.py:514} INFO - at org.apache.spark.network.client.TransportClientFactory.createClient(TransportClientFactory.java:218)
[2021-12-20 10:33:28,863] {spark_submit.py:514} INFO - at org.apache.spark.network.client.TransportClientFactory.createClient(TransportClientFactory.java:230)
[2021-12-20 10:33:28,864] {spark_submit.py:514} INFO - at org.apache.spark.rpc.netty.NettyRpcEnv.createClient(NettyRpcEnv.scala:204)
[2021-12-20 10:33:28,865] {spark_submit.py:514} INFO - at org.apache.spark.rpc.netty.Outbox$$anon$1.call(Outbox.scala:202)
[2021-12-20 10:33:28,865] {spark_submit.py:514} INFO - at org.apache.spark.rpc.netty.Outbox$$anon$1.call(Outbox.scala:198)
[2021-12-20 10:33:28,866] {spark_submit.py:514} INFO - ... 4 more
[2021-12-20 10:33:28,867] {spark_submit.py:514} INFO - Caused by: java.net.UnknownHostException: spark
[2021-12-20 10:33:28,868] {spark_submit.py:514} INFO - at java.base/java.net.InetAddress$CachedAddresses.get(InetAddress.java:797)
[2021-12-20 10:33:28,868] {spark_submit.py:514} INFO - at java.base/java.net.InetAddress.getAllByName0(InetAddress.java:1509)
[2021-12-20 10:33:28,869] {spark_submit.py:514} INFO - at java.base/java.net.InetAddress.getAllByName(InetAddress.java:1368)
[2021-12-20 10:33:28,870] {spark_submit.py:514} INFO - at java.base/java.net.InetAddress.getAllByName(InetAddress.java:1302)
[2021-12-20 10:33:28,871] {spark_submit.py:514} INFO - at java.base/java.net.InetAddress.getByName(InetAddress.java:1252)
[2021-12-20 10:33:28,872] {spark_submit.py:514} INFO - at io.netty.util.internal.SocketUtils$8.run(SocketUtils.java:156)
[2021-12-20 10:33:28,872] {spark_submit.py:514} INFO - at io.netty.util.internal.SocketUtils$8.run(SocketUtils.java:153)
[2021-12-20 10:33:28,873] {spark_submit.py:514} INFO - at java.base/java.security.AccessController.doPrivileged(Native Method)
[2021-12-20 10:33:28,874] {spark_submit.py:514} INFO - at io.netty.util.internal.SocketUtils.addressByName(SocketUtils.java:153)
[2021-12-20 10:33:28,875] {spark_submit.py:514} INFO - at io.netty.resolver.DefaultNameResolver.doResolve(DefaultNameResolver.java:41)
[2021-12-20 10:33:28,876] {spark_submit.py:514} INFO - at io.netty.resolver.SimpleNameResolver.resolve(SimpleNameResolver.java:61)
[2021-12-20 10:33:28,876] {spark_submit.py:514} INFO - at io.netty.resolver.SimpleNameResolver.resolve(SimpleNameResolver.java:53)
[2021-12-20 10:33:28,877] {spark_submit.py:514} INFO - at io.netty.resolver.InetSocketAddressResolver.doResolve(InetSocketAddressResolver.java:55)
[2021-12-20 10:33:28,878] {spark_submit.py:514} INFO - at io.netty.resolver.InetSocketAddressResolver.doResolve(InetSocketAddressResolver.java:31)
[2021-12-20 10:33:28,879] {spark_submit.py:514} INFO - at io.netty.resolver.AbstractAddressResolver.resolve(AbstractAddressResolver.java:106)
[2021-12-20 10:33:28,880] {spark_submit.py:514} INFO - at io.netty.bootstrap.Bootstrap.doResolveAndConnect0(Bootstrap.java:206)
[2021-12-20 10:33:28,881] {spark_submit.py:514} INFO - at io.netty.bootstrap.Bootstrap.access$000(Bootstrap.java:46)
[2021-12-20 10:33:28,882] {spark_submit.py:514} INFO - at io.netty.bootstrap.Bootstrap$1.operationComplete(Bootstrap.java:180)
[2021-12-20 10:33:28,882] {spark_submit.py:514} INFO - at io.netty.bootstrap.Bootstrap$1.operationComplete(Bootstrap.java:166)
[2021-12-20 10:33:28,883] {spark_submit.py:514} INFO - at io.netty.util.concurrent.DefaultPromise.notifyListener0(DefaultPromise.java:578)
[2021-12-20 10:33:28,884] {spark_submit.py:514} INFO - at io.netty.util.concurrent.DefaultPromise.notifyListenersNow(DefaultPromise.java:552)
[2021-12-20 10:33:28,885] {spark_submit.py:514} INFO - at io.netty.util.concurrent.DefaultPromise.notifyListeners(DefaultPromise.java:491)
[2021-12-20 10:33:28,885] {spark_submit.py:514} INFO - at io.netty.util.concurrent.DefaultPromise.setValue0(DefaultPromise.java:616)
[2021-12-20 10:33:28,886] {spark_submit.py:514} INFO - at io.netty.util.concurrent.DefaultPromise.setSuccess0(DefaultPromise.java:605)
[2021-12-20 10:33:28,887] {spark_submit.py:514} INFO - at io.netty.util.concurrent.DefaultPromise.trySuccess(DefaultPromise.java:104)
[2021-12-20 10:33:28,888] {spark_submit.py:514} INFO - at io.netty.channel.DefaultChannelPromise.trySuccess(DefaultChannelPromise.java:84)
[2021-12-20 10:33:28,888] {spark_submit.py:514} INFO - at io.netty.channel.AbstractChannel$AbstractUnsafe.safeSetSuccess(AbstractChannel.java:1008)
[2021-12-20 10:33:28,889] {spark_submit.py:514} INFO - at io.netty.channel.AbstractChannel$AbstractUnsafe.register0(AbstractChannel.java:516)
[2021-12-20 10:33:28,890] {spark_submit.py:514} INFO - at io.netty.channel.AbstractChannel$AbstractUnsafe.access$200(AbstractChannel.java:429)
[2021-12-20 10:33:28,891] {spark_submit.py:514} INFO - at io.netty.channel.AbstractChannel$AbstractUnsafe$1.run(AbstractChannel.java:486)
[2021-12-20 10:33:28,893] {spark_submit.py:514} INFO - at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:164)
[2021-12-20 10:33:28,894] {spark_submit.py:514} INFO - at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:469)
[2021-12-20 10:33:28,894] {spark_submit.py:514} INFO - at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:500)
[2021-12-20 10:33:28,896] {spark_submit.py:514} INFO - at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:986)
[2021-12-20 10:33:28,896] {spark_submit.py:514} INFO - at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
[2021-12-20 10:33:28,898] {spark_submit.py:514} INFO - at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
[2021-12-20 10:33:28,900] {spark_submit.py:514} INFO - ... 1 more
[2021-12-20 10:33:48,804] {spark_submit.py:514} INFO - 21/12/20 10:33:48 INFO StandaloneAppClient$ClientEndpoint: Connecting to master spark://spark:7077...
[2021-12-20 10:33:48,822] {spark_submit.py:514} INFO - 21/12/20 10:33:48 WARN StandaloneAppClient$ClientEndpoint: Failed to connect to master spark:7077
[2021-12-20 10:33:48,824] {spark_submit.py:514} INFO - org.apache.spark.SparkException: Exception thrown in awaitResult:
[2021-12-20 10:33:48,826] {spark_submit.py:514} INFO - at org.apache.spark.util.ThreadUtils$.awaitResult(ThreadUtils.scala:301)
[2021-12-20 10:33:48,828] {spark_submit.py:514} INFO - at org.apache.spark.rpc.RpcTimeout.awaitResult(RpcTimeout.scala:75)
[2021-12-20 10:33:48,830] {spark_submit.py:514} INFO - at org.apache.spark.rpc.RpcEnv.setupEndpointRefByURI(RpcEnv.scala:101)
[2021-12-20 10:33:48,832] {spark_submit.py:514} INFO - at org.apache.spark.rpc.RpcEnv.setupEndpointRef(RpcEnv.scala:109)
[2021-12-20 10:33:48,833] {spark_submit.py:514} INFO - at org.apache.spark.deploy.client.StandaloneAppClient$ClientEndpoint$$anon$1.run(StandaloneAppClient.scala:107)
[2021-12-20 10:33:48,834] {spark_submit.py:514} INFO - at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
[2021-12-20 10:33:48,835] {spark_submit.py:514} INFO - at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
[2021-12-20 10:33:48,836] {spark_submit.py:514} INFO - at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
[2021-12-20 10:33:48,838] {spark_submit.py:514} INFO - at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
[2021-12-20 10:33:48,839] {spark_submit.py:514} INFO - at java.base/java.lang.Thread.run(Thread.java:829)
[2021-12-20 10:33:48,841] {spark_submit.py:514} INFO - Caused by: java.io.IOException: Failed to connect to spark:7077
[2021-12-20 10:33:48,843] {spark_submit.py:514} INFO - at org.apache.spark.network.client.TransportClientFactory.createClient(TransportClientFactory.java:288)
[2021-12-20 10:33:48,844] {spark_submit.py:514} INFO - at org.apache.spark.network.client.TransportClientFactory.createClient(TransportClientFactory.java:218)
[2021-12-20 10:33:48,845] {spark_submit.py:514} INFO - at org.apache.spark.network.client.TransportClientFactory.createClient(TransportClientFactory.java:230)
[2021-12-20 10:33:48,846] {spark_submit.py:514} INFO - at org.apache.spark.rpc.netty.NettyRpcEnv.createClient(NettyRpcEnv.scala:204)
[2021-12-20 10:33:48,847] {spark_submit.py:514} INFO - at org.apache.spark.rpc.netty.Outbox$$anon$1.call(Outbox.scala:202)
[2021-12-20 10:33:48,848] {spark_submit.py:514} INFO - at org.apache.spark.rpc.netty.Outbox$$anon$1.call(Outbox.scala:198)
[2021-12-20 10:33:48,849] {spark_submit.py:514} INFO - ... 4 more
[2021-12-20 10:33:48,850] {spark_submit.py:514} INFO - Caused by: java.net.UnknownHostException: spark
[2021-12-20 10:33:48,851] {spark_submit.py:514} INFO - at java.base/java.net.InetAddress$CachedAddresses.get(InetAddress.java:797)
[2021-12-20 10:33:48,852] {spark_submit.py:514} INFO - at java.base/java.net.InetAddress.getAllByName0(InetAddress.java:1509)
[2021-12-20 10:33:48,853] {spark_submit.py:514} INFO - at java.base/java.net.InetAddress.getAllByName(InetAddress.java:1368)
[2021-12-20 10:33:48,855] {spark_submit.py:514} INFO - at java.base/java.net.InetAddress.getAllByName(InetAddress.java:1302)
[2021-12-20 10:33:48,856] {spark_submit.py:514} INFO - at java.base/java.net.InetAddress.getByName(InetAddress.java:1252)
[2021-12-20 10:33:48,857] {spark_submit.py:514} INFO - at io.netty.util.internal.SocketUtils$8.run(SocketUtils.java:156)
[2021-12-20 10:33:48,858] {spark_submit.py:514} INFO - at io.netty.util.internal.SocketUtils$8.run(SocketUtils.java:153)
[2021-12-20 10:33:48,859] {spark_submit.py:514} INFO - at java.base/java.security.AccessController.doPrivileged(Native Method)
[2021-12-20 10:33:48,860] {spark_submit.py:514} INFO - at io.netty.util.internal.SocketUtils.addressByName(SocketUtils.java:153)
[2021-12-20 10:33:48,861] {spark_submit.py:514} INFO - at io.netty.resolver.DefaultNameResolver.doResolve(DefaultNameResolver.java:41)
[2021-12-20 10:33:48,862] {spark_submit.py:514} INFO - at io.netty.resolver.SimpleNameResolver.resolve(SimpleNameResolver.java:61)
[2021-12-20 10:33:48,862] {spark_submit.py:514} INFO - at io.netty.resolver.SimpleNameResolver.resolve(SimpleNameResolver.java:53)
[2021-12-20 10:33:48,863] {spark_submit.py:514} INFO - at io.netty.resolver.InetSocketAddressResolver.doResolve(InetSocketAddressResolver.java:55)
[2021-12-20 10:33:48,864] {spark_submit.py:514} INFO - at io.netty.resolver.InetSocketAddressResolver.doResolve(InetSocketAddressResolver.java:31)
[2021-12-20 10:33:48,865] {spark_submit.py:514} INFO - at io.netty.resolver.AbstractAddressResolver.resolve(AbstractAddressResolver.java:106)
[2021-12-20 10:33:48,866] {spark_submit.py:514} INFO - at io.netty.bootstrap.Bootstrap.doResolveAndConnect0(Bootstrap.java:206)
[2021-12-20 10:33:48,868] {spark_submit.py:514} INFO - at io.netty.bootstrap.Bootstrap.access$000(Bootstrap.java:46)
[2021-12-20 10:33:48,869] {spark_submit.py:514} INFO - at io.netty.bootstrap.Bootstrap$1.operationComplete(Bootstrap.java:180)
[2021-12-20 10:33:48,870] {spark_submit.py:514} INFO - at io.netty.bootstrap.Bootstrap$1.operationComplete(Bootstrap.java:166)
[2021-12-20 10:33:48,871] {spark_submit.py:514} INFO - at io.netty.util.concurrent.DefaultPromise.notifyListener0(DefaultPromise.java:578)
[2021-12-20 10:33:48,871] {spark_submit.py:514} INFO - at io.netty.util.concurrent.DefaultPromise.notifyListenersNow(DefaultPromise.java:552)
[2021-12-20 10:33:48,872] {spark_submit.py:514} INFO - at io.netty.util.concurrent.DefaultPromise.notifyListeners(DefaultPromise.java:491)
[2021-12-20 10:33:48,873] {spark_submit.py:514} INFO - at io.netty.util.concurrent.DefaultPromise.setValue0(DefaultPromise.java:616)
[2021-12-20 10:33:48,873] {spark_submit.py:514} INFO - at io.netty.util.concurrent.DefaultPromise.setSuccess0(DefaultPromise.java:605)
[2021-12-20 10:33:48,874] {spark_submit.py:514} INFO - at io.netty.util.concurrent.DefaultPromise.trySuccess(DefaultPromise.java:104)
[2021-12-20 10:33:48,874] {spark_submit.py:514} INFO - at io.netty.channel.DefaultChannelPromise.trySuccess(DefaultChannelPromise.java:84)
[2021-12-20 10:33:48,875] {spark_submit.py:514} INFO - at io.netty.channel.AbstractChannel$AbstractUnsafe.safeSetSuccess(AbstractChannel.java:1008)
[2021-12-20 10:33:48,876] {spark_submit.py:514} INFO - at io.netty.channel.AbstractChannel$AbstractUnsafe.register0(AbstractChannel.java:516)
[2021-12-20 10:33:48,876] {spark_submit.py:514} INFO - at io.netty.channel.AbstractChannel$AbstractUnsafe.access$200(AbstractChannel.java:429)
[2021-12-20 10:33:48,877] {spark_submit.py:514} INFO - at io.netty.channel.AbstractChannel$AbstractUnsafe$1.run(AbstractChannel.java:486)
[2021-12-20 10:33:48,878] {spark_submit.py:514} INFO - at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:164)
[2021-12-20 10:33:48,878] {spark_submit.py:514} INFO - at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:469)
[2021-12-20 10:33:48,879] {spark_submit.py:514} INFO - at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:500)
[2021-12-20 10:33:48,879] {spark_submit.py:514} INFO - at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:986)
[2021-12-20 10:33:48,880] {spark_submit.py:514} INFO - at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
[2021-12-20 10:33:48,881] {spark_submit.py:514} INFO - at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
[2021-12-20 10:33:48,883] {spark_submit.py:514} INFO - ... 1 more
[2021-12-20 10:34:08,771] {spark_submit.py:514} INFO - 21/12/20 10:34:08 ERROR StandaloneSchedulerBackend: Application has been killed. Reason: All masters are unresponsive! Giving up.
[2021-12-20 10:34:08,773] {spark_submit.py:514} INFO - 21/12/20 10:34:08 WARN StandaloneSchedulerBackend: Application ID is not initialized yet.
[2021-12-20 10:34:08,793] {spark_submit.py:514} INFO - 21/12/20 10:34:08 INFO Utils: Successfully started service 'org.apache.spark.network.netty.NettyBlockTransferService' on port 35553.
[2021-12-20 10:34:08,794] {spark_submit.py:514} INFO - 21/12/20 10:34:08 INFO NettyBlockTransferService: Server created on a35fe600e898:35553
[2021-12-20 10:34:08,796] {spark_submit.py:514} INFO - 21/12/20 10:34:08 INFO BlockManager: Using org.apache.spark.storage.RandomBlockReplicationPolicy for block replication policy
[2021-12-20 10:34:08,813] {spark_submit.py:514} INFO - 21/12/20 10:34:08 INFO SparkUI: Stopped Spark web UI at http://a35fe600e898:4047
[2021-12-20 10:34:08,814] {spark_submit.py:514} INFO - 21/12/20 10:34:08 INFO BlockManagerMaster: Registering BlockManager BlockManagerId(driver, a35fe600e898, 35553, None)
[2021-12-20 10:34:08,822] {spark_submit.py:514} INFO - 21/12/20 10:34:08 INFO BlockManagerMasterEndpoint: Registering block manager a35fe600e898:35553 with 434.4 MiB RAM, BlockManagerId(driver, a35fe600e898, 35553, None)
[2021-12-20 10:34:08,827] {spark_submit.py:514} INFO - 21/12/20 10:34:08 INFO StandaloneSchedulerBackend: Shutting down all executors
[2021-12-20 10:34:08,830] {spark_submit.py:514} INFO - 21/12/20 10:34:08 INFO BlockManagerMaster: Registered BlockManager BlockManagerId(driver, a35fe600e898, 35553, None)
[2021-12-20 10:34:08,831] {spark_submit.py:514} INFO - 21/12/20 10:34:08 INFO BlockManager: Initialized BlockManager: BlockManagerId(driver, a35fe600e898, 35553, None)
[2021-12-20 10:34:08,835] {spark_submit.py:514} INFO - 21/12/20 10:34:08 INFO CoarseGrainedSchedulerBackend$DriverEndpoint: Asking each executor to shut down
[2021-12-20 10:34:08,846] {spark_submit.py:514} INFO - 21/12/20 10:34:08 WARN StandaloneAppClient$ClientEndpoint: Drop UnregisterApplication(null) because has not yet connected to master
[2021-12-20 10:34:08,869] {spark_submit.py:514} INFO - 21/12/20 10:34:08 INFO MapOutputTrackerMasterEndpoint: MapOutputTrackerMasterEndpoint stopped!
[2021-12-20 10:34:08,902] {spark_submit.py:514} INFO - 21/12/20 10:34:08 INFO MemoryStore: MemoryStore cleared
[2021-12-20 10:34:08,904] {spark_submit.py:514} INFO - 21/12/20 10:34:08 INFO BlockManager: BlockManager stopped
[2021-12-20 10:34:08,915] {spark_submit.py:514} INFO - 21/12/20 10:34:08 INFO BlockManagerMaster: BlockManagerMaster stopped
[2021-12-20 10:34:08,920] {spark_submit.py:514} INFO - 21/12/20 10:34:08 INFO OutputCommitCoordinator$OutputCommitCoordinatorEndpoint: OutputCommitCoordinator stopped!
[2021-12-20 10:34:08,956] {spark_submit.py:514} INFO - 21/12/20 10:34:08 INFO SparkContext: Successfully stopped SparkContext
[2021-12-20 10:34:09,179] {spark_submit.py:514} INFO - 21/12/20 10:34:09 ERROR SparkContext: Error initializing SparkContext.
[2021-12-20 10:34:09,181] {spark_submit.py:514} INFO - java.lang.IllegalArgumentException: requirement failed: Can only call getServletHandlers on a running MetricsSystem
[2021-12-20 10:34:09,182] {spark_submit.py:514} INFO - at scala.Predef$.require(Predef.scala:281)
[2021-12-20 10:34:09,184] {spark_submit.py:514} INFO - at org.apache.spark.metrics.MetricsSystem.getServletHandlers(MetricsSystem.scala:89)
[2021-12-20 10:34:09,185] {spark_submit.py:514} INFO - at org.apache.spark.SparkContext.<init>(SparkContext.scala:603)
[2021-12-20 10:34:09,187] {spark_submit.py:514} INFO - at org.apache.spark.api.java.JavaSparkContext.<init>(JavaSparkContext.scala:58)
[2021-12-20 10:34:09,188] {spark_submit.py:514} INFO - at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
[2021-12-20 10:34:09,189] {spark_submit.py:514} INFO - at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
[2021-12-20 10:34:09,190] {spark_submit.py:514} INFO - at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
[2021-12-20 10:34:09,193] {spark_submit.py:514} INFO - at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:490)
[2021-12-20 10:34:09,194] {spark_submit.py:514} INFO - at py4j.reflection.MethodInvoker.invoke(MethodInvoker.java:247)
[2021-12-20 10:34:09,195] {spark_submit.py:514} INFO - at py4j.reflection.ReflectionEngine.invoke(ReflectionEngine.java:357)
[2021-12-20 10:34:09,196] {spark_submit.py:514} INFO - at py4j.Gateway.invoke(Gateway.java:238)
[2021-12-20 10:34:09,197] {spark_submit.py:514} INFO - at py4j.commands.ConstructorCommand.invokeConstructor(ConstructorCommand.java:80)
[2021-12-20 10:34:09,199] {spark_submit.py:514} INFO - at py4j.commands.ConstructorCommand.execute(ConstructorCommand.java:69)
[2021-12-20 10:34:09,200] {spark_submit.py:514} INFO - at py4j.ClientServerConnection.waitForCommands(ClientServerConnection.java:182)
[2021-12-20 10:34:09,201] {spark_submit.py:514} INFO - at py4j.ClientServerConnection.run(ClientServerConnection.java:106)
[2021-12-20 10:34:09,203] {spark_submit.py:514} INFO - at java.base/java.lang.Thread.run(Thread.java:829)
[2021-12-20 10:34:09,204] {spark_submit.py:514} INFO - 21/12/20 10:34:09 INFO SparkContext: SparkContext already stopped.
[2021-12-20 10:34:09,205] {spark_submit.py:514} INFO - Traceback (most recent call last):
[2021-12-20 10:34:09,206] {spark_submit.py:514} INFO - File "/opt/***/jobs/get_ads_per_county.py", line 13, in <module>
[2021-12-20 10:34:09,207] {spark_submit.py:514} INFO - .appName("Get Ads per county") \
[2021-12-20 10:34:09,208] {spark_submit.py:514} INFO - File "/home/***/.local/lib/python3.6/site-packages/pyspark/python/lib/pyspark.zip/pyspark/sql/session.py", line 228, in getOrCreate
[2021-12-20 10:34:09,209] {spark_submit.py:514} INFO - File "/home/***/.local/lib/python3.6/site-packages/pyspark/python/lib/pyspark.zip/pyspark/context.py", line 392, in getOrCreate
[2021-12-20 10:34:09,210] {spark_submit.py:514} INFO - File "/home/***/.local/lib/python3.6/site-packages/pyspark/python/lib/pyspark.zip/pyspark/context.py", line 147, in __init__
[2021-12-20 10:34:09,211] {spark_submit.py:514} INFO - File "/home/***/.local/lib/python3.6/site-packages/pyspark/python/lib/pyspark.zip/pyspark/context.py", line 209, in _do_init
[2021-12-20 10:34:09,212] {spark_submit.py:514} INFO - File "/home/***/.local/lib/python3.6/site-packages/pyspark/python/lib/pyspark.zip/pyspark/context.py", line 329, in _initialize_context
[2021-12-20 10:34:09,213] {spark_submit.py:514} INFO - File "/home/***/.local/lib/python3.6/site-packages/pyspark/python/lib/py4j-0.10.9.2-src.zip/py4j/java_gateway.py", line 1574, in __call__
[2021-12-20 10:34:09,214] {spark_submit.py:514} INFO - File "/home/***/.local/lib/python3.6/site-packages/pyspark/python/lib/py4j-0.10.9.2-src.zip/py4j/protocol.py", line 328, in get_return_value
[2021-12-20 10:34:09,215] {spark_submit.py:514} INFO - py4j.protocol.Py4JJavaError: An error occurred while calling None.org.apache.spark.api.java.JavaSparkContext.
[2021-12-20 10:34:09,216] {spark_submit.py:514} INFO - : java.lang.IllegalArgumentException: requirement failed: Can only call getServletHandlers on a running MetricsSystem
[2021-12-20 10:34:09,217] {spark_submit.py:514} INFO - at scala.Predef$.require(Predef.scala:281)
[2021-12-20 10:34:09,218] {spark_submit.py:514} INFO - at org.apache.spark.metrics.MetricsSystem.getServletHandlers(MetricsSystem.scala:89)
[2021-12-20 10:34:09,219] {spark_submit.py:514} INFO - at org.apache.spark.SparkContext.<init>(SparkContext.scala:603)
[2021-12-20 10:34:09,220] {spark_submit.py:514} INFO - at org.apache.spark.api.java.JavaSparkContext.<init>(JavaSparkContext.scala:58)
[2021-12-20 10:34:09,221] {spark_submit.py:514} INFO - at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
[2021-12-20 10:34:09,222] {spark_submit.py:514} INFO - at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
[2021-12-20 10:34:09,223] {spark_submit.py:514} INFO - at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
[2021-12-20 10:34:09,224] {spark_submit.py:514} INFO - at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:490)
[2021-12-20 10:34:09,225] {spark_submit.py:514} INFO - at py4j.reflection.MethodInvoker.invoke(MethodInvoker.java:247)
[2021-12-20 10:34:09,226] {spark_submit.py:514} INFO - at py4j.reflection.ReflectionEngine.invoke(ReflectionEngine.java:357)
[2021-12-20 10:34:09,228] {spark_submit.py:514} INFO - at py4j.Gateway.invoke(Gateway.java:238)
[2021-12-20 10:34:09,229] {spark_submit.py:514} INFO - at py4j.commands.ConstructorCommand.invokeConstructor(ConstructorCommand.java:80)
[2021-12-20 10:34:09,230] {spark_submit.py:514} INFO - at py4j.commands.ConstructorCommand.execute(ConstructorCommand.java:69)
[2021-12-20 10:34:09,231] {spark_submit.py:514} INFO - at py4j.ClientServerConnection.waitForCommands(ClientServerConnection.java:182)
[2021-12-20 10:34:09,232] {spark_submit.py:514} INFO - at py4j.ClientServerConnection.run(ClientServerConnection.java:106)
[2021-12-20 10:34:09,234] {spark_submit.py:514} INFO - at java.base/java.lang.Thread.run(Thread.java:829)
[2021-12-20 10:34:09,236] {spark_submit.py:514} INFO - 
[2021-12-20 10:34:09,343] {spark_submit.py:514} INFO - 21/12/20 10:34:09 INFO ShutdownHookManager: Shutdown hook called
[2021-12-20 10:34:09,344] {spark_submit.py:514} INFO - 21/12/20 10:34:09 INFO ShutdownHookManager: Deleting directory /tmp/spark-46189c68-21af-4a4d-a492-8e49d1467703
[2021-12-20 10:34:09,349] {spark_submit.py:514} INFO - 21/12/20 10:34:09 INFO ShutdownHookManager: Deleting directory /tmp/spark-6b4f8b2c-1641-41be-837e-0080d18d4062
[2021-12-20 10:34:09,513] {taskinstance.py:1703} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 1332, in _run_raw_task
    self._execute_task_with_callbacks(context)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 1458, in _execute_task_with_callbacks
    result = self._execute_task(context, self.task)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 1514, in _execute_task
    result = execute_callable(context=context)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/providers/apache/spark/operators/spark_submit.py", line 179, in execute
    self._hook.submit(self._application)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/providers/apache/spark/hooks/spark_submit.py", line 446, in submit
    f"Cannot execute: {self._mask_cmd(spark_submit_cmd)}. Error code is: {returncode}."
airflow.exceptions.AirflowException: Cannot execute: spark-submit --master spark://spark:7077 --conf spark.master=spark://spark:7077 --name scrap data --verbose /opt/***/jobs/get_ads_per_county.py longford. Error code is: 1.
[2021-12-20 10:34:09,534] {taskinstance.py:1280} INFO - Marking task as UP_FOR_RETRY. dag_id=scraping_daft_longford, task_id=scrap_data, execution_date=20211219T101000, start_date=20211220T103253, end_date=20211220T103409
[2021-12-20 10:34:09,568] {standard_task_runner.py:91} ERROR - Failed to execute job 3408 for task scrap_data
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/task/task_runner/standard_task_runner.py", line 85, in _start_by_fork
    args.func(args, dag=self.dag)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/cli/cli_parser.py", line 48, in command
    return func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/utils/cli.py", line 92, in wrapper
    return f(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/cli/commands/task_command.py", line 292, in task_run
    _run_task_by_selected_method(args, dag, ti)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/cli/commands/task_command.py", line 107, in _run_task_by_selected_method
    _run_raw_task(args, ti)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/cli/commands/task_command.py", line 184, in _run_raw_task
    error_file=args.error_file,
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/utils/session.py", line 70, in wrapper
    return func(*args, session=session, **kwargs)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 1332, in _run_raw_task
    self._execute_task_with_callbacks(context)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 1458, in _execute_task_with_callbacks
    result = self._execute_task(context, self.task)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 1514, in _execute_task
    result = execute_callable(context=context)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/providers/apache/spark/operators/spark_submit.py", line 179, in execute
    self._hook.submit(self._application)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/providers/apache/spark/hooks/spark_submit.py", line 446, in submit
    f"Cannot execute: {self._mask_cmd(spark_submit_cmd)}. Error code is: {returncode}."
airflow.exceptions.AirflowException: Cannot execute: spark-submit --master spark://spark:7077 --conf spark.master=spark://spark:7077 --name scrap data --verbose /opt/***/jobs/get_ads_per_county.py longford. Error code is: 1.
[2021-12-20 10:34:09,600] {local_task_job.py:154} INFO - Task exited with return code 1
[2021-12-20 10:34:09,718] {local_task_job.py:264} INFO - 0 downstream tasks scheduled from follow-on schedule check
