[2021-12-20 11:22:47,750] {taskinstance.py:1035} INFO - Dependencies all met for <TaskInstance: scraping_daft_westmeath.scrap_data scheduled__2021-12-19T11:00:00+00:00 [queued]>
[2021-12-20 11:22:48,127] {taskinstance.py:1035} INFO - Dependencies all met for <TaskInstance: scraping_daft_westmeath.scrap_data scheduled__2021-12-19T11:00:00+00:00 [queued]>
[2021-12-20 11:22:48,139] {taskinstance.py:1241} INFO - 
--------------------------------------------------------------------------------
[2021-12-20 11:22:48,140] {taskinstance.py:1242} INFO - Starting attempt 1 of 4
[2021-12-20 11:22:48,142] {taskinstance.py:1243} INFO - 
--------------------------------------------------------------------------------
[2021-12-20 11:22:48,414] {taskinstance.py:1262} INFO - Executing <Task(SparkSubmitOperator): scrap_data> on 2021-12-19 11:00:00+00:00
[2021-12-20 11:22:48,541] {standard_task_runner.py:76} INFO - Running: ['***', 'tasks', 'run', 'scraping_daft_westmeath', 'scrap_data', 'scheduled__2021-12-19T11:00:00+00:00', '--job-id', '3445', '--raw', '--subdir', 'DAGS_FOLDER/scraping_daft_westmeath.py', '--cfg-path', '/tmp/tmpxeq4l85i', '--error-file', '/tmp/tmpxjb4y2zd']
[2021-12-20 11:22:48,543] {standard_task_runner.py:77} INFO - Job 3445: Subtask scrap_data
[2021-12-20 11:22:48,530] {standard_task_runner.py:52} INFO - Started process 6150 to run task
[2021-12-20 11:22:48,738] {logging_mixin.py:109} INFO - Running <TaskInstance: scraping_daft_westmeath.scrap_data scheduled__2021-12-19T11:00:00+00:00 [running]> on host a35fe600e898
[2021-12-20 11:22:49,571] {taskinstance.py:1429} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_EMAIL=clement.liscoet@gmail.com
AIRFLOW_CTX_DAG_OWNER=clemoni
AIRFLOW_CTX_DAG_ID=scraping_daft_westmeath
AIRFLOW_CTX_TASK_ID=scrap_data
AIRFLOW_CTX_EXECUTION_DATE=2021-12-19T11:00:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2021-12-19T11:00:00+00:00
[2021-12-20 11:22:49,649] {base.py:79} INFO - Using connection to: id: spark_default. Host: spark://spark:7077, Port: None, Schema: , Login: ***, Password: ***, extra: {}
[2021-12-20 11:22:49,666] {spark_submit.py:360} INFO - Spark-Submit cmd: spark-submit --master spark://spark:7077 --conf spark.master=spark://spark:7077 --name scrap data --verbose /opt/***/jobs/get_ads_per_county.py westmeath
[2021-12-20 11:23:30,539] {spark_submit.py:514} INFO - Using properties file: null
[2021-12-20 11:23:33,496] {spark_submit.py:514} INFO - WARNING: An illegal reflective access operation has occurred
[2021-12-20 11:23:33,497] {spark_submit.py:514} INFO - WARNING: Illegal reflective access by org.apache.spark.unsafe.Platform (file:/home/***/.local/lib/python3.6/site-packages/pyspark/jars/spark-unsafe_2.12-3.2.0.jar) to constructor java.nio.DirectByteBuffer(long,int)
[2021-12-20 11:23:33,501] {spark_submit.py:514} INFO - WARNING: Please consider reporting this to the maintainers of org.apache.spark.unsafe.Platform
[2021-12-20 11:23:33,503] {spark_submit.py:514} INFO - WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
[2021-12-20 11:23:33,505] {spark_submit.py:514} INFO - WARNING: All illegal access operations will be denied in a future release
[2021-12-20 11:23:37,099] {spark_submit.py:514} INFO - Parsed arguments:
[2021-12-20 11:23:37,113] {spark_submit.py:514} INFO - master                  spark://spark:7077
[2021-12-20 11:23:37,153] {spark_submit.py:514} INFO - deployMode              null
[2021-12-20 11:23:37,155] {spark_submit.py:514} INFO - executorMemory          null
[2021-12-20 11:23:37,168] {spark_submit.py:514} INFO - executorCores           null
[2021-12-20 11:23:37,171] {spark_submit.py:514} INFO - totalExecutorCores      null
[2021-12-20 11:23:37,175] {spark_submit.py:514} INFO - propertiesFile          null
[2021-12-20 11:23:37,177] {spark_submit.py:514} INFO - driverMemory            null
[2021-12-20 11:23:37,181] {spark_submit.py:514} INFO - driverCores             null
[2021-12-20 11:23:37,184] {spark_submit.py:514} INFO - driverExtraClassPath    null
[2021-12-20 11:23:37,191] {spark_submit.py:514} INFO - driverExtraLibraryPath  null
[2021-12-20 11:23:37,195] {spark_submit.py:514} INFO - driverExtraJavaOptions  null
[2021-12-20 11:23:37,199] {spark_submit.py:514} INFO - supervise               false
[2021-12-20 11:23:37,201] {spark_submit.py:514} INFO - queue                   null
[2021-12-20 11:23:37,203] {spark_submit.py:514} INFO - numExecutors            null
[2021-12-20 11:23:37,205] {spark_submit.py:514} INFO - files                   null
[2021-12-20 11:23:37,208] {spark_submit.py:514} INFO - pyFiles                 null
[2021-12-20 11:23:37,210] {spark_submit.py:514} INFO - archives                null
[2021-12-20 11:23:37,213] {spark_submit.py:514} INFO - mainClass               null
[2021-12-20 11:23:37,218] {spark_submit.py:514} INFO - primaryResource         file:/opt/***/jobs/get_ads_per_county.py
[2021-12-20 11:23:37,220] {spark_submit.py:514} INFO - name                    scrap data
[2021-12-20 11:23:37,229] {spark_submit.py:514} INFO - childArgs               [westmeath]
[2021-12-20 11:23:37,231] {spark_submit.py:514} INFO - jars                    null
[2021-12-20 11:23:37,233] {spark_submit.py:514} INFO - packages                null
[2021-12-20 11:23:37,242] {spark_submit.py:514} INFO - packagesExclusions      null
[2021-12-20 11:23:37,244] {spark_submit.py:514} INFO - repositories            null
[2021-12-20 11:23:37,246] {spark_submit.py:514} INFO - verbose                 true
[2021-12-20 11:23:37,248] {spark_submit.py:514} INFO - 
[2021-12-20 11:23:37,249] {spark_submit.py:514} INFO - Spark properties used, including those specified through
[2021-12-20 11:23:37,252] {spark_submit.py:514} INFO - --conf and those from the properties file null:
[2021-12-20 11:23:37,254] {spark_submit.py:514} INFO - (spark.master,spark://spark:7077)
[2021-12-20 11:23:37,256] {spark_submit.py:514} INFO - 
[2021-12-20 11:23:37,260] {spark_submit.py:514} INFO - 
[2021-12-20 11:23:41,829] {spark_submit.py:514} INFO - Main class:
[2021-12-20 11:23:41,830] {spark_submit.py:514} INFO - org.apache.spark.deploy.PythonRunner
[2021-12-20 11:23:41,832] {spark_submit.py:514} INFO - Arguments:
[2021-12-20 11:23:41,834] {spark_submit.py:514} INFO - file:/opt/***/jobs/get_ads_per_county.py
[2021-12-20 11:23:41,835] {spark_submit.py:514} INFO - null
[2021-12-20 11:23:41,836] {spark_submit.py:514} INFO - westmeath
[2021-12-20 11:23:41,837] {spark_submit.py:514} INFO - --verbose
[2021-12-20 11:23:41,857] {spark_submit.py:514} INFO - Spark config:
[2021-12-20 11:23:41,858] {spark_submit.py:514} INFO - (spark.app.name,scrap data)
[2021-12-20 11:23:41,859] {spark_submit.py:514} INFO - (spark.master,spark://spark:7077)
[2021-12-20 11:23:41,860] {spark_submit.py:514} INFO - (spark.submit.pyFiles,)
[2021-12-20 11:23:41,861] {spark_submit.py:514} INFO - (spark.submit.deployMode,client)
[2021-12-20 11:23:41,870] {spark_submit.py:514} INFO - Classpath elements:
[2021-12-20 11:23:41,873] {spark_submit.py:514} INFO - 
[2021-12-20 11:23:41,877] {spark_submit.py:514} INFO - 
[2021-12-20 11:23:41,878] {spark_submit.py:514} INFO - 
[2021-12-20 11:23:50,286] {spark_submit.py:514} INFO - Using Spark's default log4j profile: org/apache/spark/log4j-defaults.properties
[2021-12-20 11:23:50,331] {spark_submit.py:514} INFO - 21/12/20 11:23:50 INFO SparkContext: Running Spark version 3.2.0
[2021-12-20 11:23:50,880] {spark_submit.py:514} INFO - 21/12/20 11:23:50 WARN NativeCodeLoader: Unable to load native-hadoop library for your platform... using builtin-java classes where applicable
[2021-12-20 11:23:52,441] {spark_submit.py:514} INFO - 21/12/20 11:23:52 INFO ResourceUtils: ==============================================================
[2021-12-20 11:23:52,445] {spark_submit.py:514} INFO - 21/12/20 11:23:52 INFO ResourceUtils: No custom resources configured for spark.driver.
[2021-12-20 11:23:52,489] {spark_submit.py:514} INFO - 21/12/20 11:23:52 INFO ResourceUtils: ==============================================================
[2021-12-20 11:23:52,520] {spark_submit.py:514} INFO - 21/12/20 11:23:52 INFO SparkContext: Submitted application: Get Ads per county
[2021-12-20 11:23:53,011] {spark_submit.py:514} INFO - 21/12/20 11:23:53 INFO ResourceProfile: Default ResourceProfile created, executor resources: Map(cores -> name: cores, amount: 1, script: , vendor: , memory -> name: memory, amount: 1024, script: , vendor: , offHeap -> name: offHeap, amount: 0, script: , vendor: ), task resources: Map(cpus -> name: cpus, amount: 1.0)
[2021-12-20 11:23:53,240] {spark_submit.py:514} INFO - 21/12/20 11:23:53 INFO ResourceProfile: Limiting resource is cpu
[2021-12-20 11:23:53,244] {spark_submit.py:514} INFO - 21/12/20 11:23:53 INFO ResourceProfileManager: Added ResourceProfile id: 0
[2021-12-20 11:23:54,111] {spark_submit.py:514} INFO - 21/12/20 11:23:54 INFO SecurityManager: Changing view acls to: ***
[2021-12-20 11:23:54,121] {spark_submit.py:514} INFO - 21/12/20 11:23:54 INFO SecurityManager: Changing modify acls to: ***
[2021-12-20 11:23:54,129] {spark_submit.py:514} INFO - 21/12/20 11:23:54 INFO SecurityManager: Changing view acls groups to:
[2021-12-20 11:23:54,136] {spark_submit.py:514} INFO - 21/12/20 11:23:54 INFO SecurityManager: Changing modify acls groups to:
[2021-12-20 11:23:54,188] {spark_submit.py:514} INFO - 21/12/20 11:23:54 INFO SecurityManager: SecurityManager: authentication disabled; ui acls disabled; users  with view permissions: Set(***); groups with view permissions: Set(); users  with modify permissions: Set(***); groups with modify permissions: Set()
[2021-12-20 11:23:57,143] {spark_submit.py:514} INFO - 21/12/20 11:23:57 INFO Utils: Successfully started service 'sparkDriver' on port 34481.
[2021-12-20 11:23:57,510] {spark_submit.py:514} INFO - 21/12/20 11:23:57 INFO SparkEnv: Registering MapOutputTracker
[2021-12-20 11:23:58,609] {spark_submit.py:514} INFO - 21/12/20 11:23:58 INFO SparkEnv: Registering BlockManagerMaster
[2021-12-20 11:23:59,085] {spark_submit.py:514} INFO - 21/12/20 11:23:59 INFO BlockManagerMasterEndpoint: Using org.apache.spark.storage.DefaultTopologyMapper for getting topology information
[2021-12-20 11:23:59,091] {spark_submit.py:514} INFO - 21/12/20 11:23:59 INFO BlockManagerMasterEndpoint: BlockManagerMasterEndpoint up
[2021-12-20 11:23:59,117] {spark_submit.py:514} INFO - 21/12/20 11:23:59 INFO SparkEnv: Registering BlockManagerMasterHeartbeat
[2021-12-20 11:23:59,247] {spark_submit.py:514} INFO - 21/12/20 11:23:59 INFO DiskBlockManager: Created local directory at /tmp/blockmgr-342b76c0-9410-46c9-a7f4-57ccb77f00c5
[2021-12-20 11:23:59,487] {spark_submit.py:514} INFO - 21/12/20 11:23:59 INFO MemoryStore: MemoryStore started with capacity 434.4 MiB
[2021-12-20 11:23:59,761] {spark_submit.py:514} INFO - 21/12/20 11:23:59 INFO SparkEnv: Registering OutputCommitCoordinator
[2021-12-20 11:24:02,396] {spark_submit.py:514} INFO - 21/12/20 11:24:02 WARN Utils: Service 'SparkUI' could not bind on port 4040. Attempting port 4041.
[2021-12-20 11:24:02,417] {spark_submit.py:514} INFO - 21/12/20 11:24:02 WARN Utils: Service 'SparkUI' could not bind on port 4041. Attempting port 4042.
[2021-12-20 11:24:02,419] {spark_submit.py:514} INFO - 21/12/20 11:24:02 WARN Utils: Service 'SparkUI' could not bind on port 4042. Attempting port 4043.
[2021-12-20 11:24:02,421] {spark_submit.py:514} INFO - 21/12/20 11:24:02 WARN Utils: Service 'SparkUI' could not bind on port 4043. Attempting port 4044.
[2021-12-20 11:24:02,423] {spark_submit.py:514} INFO - 21/12/20 11:24:02 WARN Utils: Service 'SparkUI' could not bind on port 4044. Attempting port 4045.
[2021-12-20 11:24:02,429] {spark_submit.py:514} INFO - 21/12/20 11:24:02 WARN Utils: Service 'SparkUI' could not bind on port 4045. Attempting port 4046.
[2021-12-20 11:24:02,449] {spark_submit.py:514} INFO - 21/12/20 11:24:02 WARN Utils: Service 'SparkUI' could not bind on port 4046. Attempting port 4047.
[2021-12-20 11:24:02,529] {spark_submit.py:514} INFO - 21/12/20 11:24:02 INFO Utils: Successfully started service 'SparkUI' on port 4047.
[2021-12-20 11:24:03,041] {spark_submit.py:514} INFO - 21/12/20 11:24:03 INFO SparkUI: Bound SparkUI to 0.0.0.0, and started at http://a35fe600e898:4047
[2021-12-20 11:24:03,903] {spark_submit.py:514} INFO - 21/12/20 11:24:03 INFO StandaloneAppClient$ClientEndpoint: Connecting to master spark://spark:7077...
[2021-12-20 11:24:04,116] {spark_submit.py:514} INFO - 21/12/20 11:24:04 WARN StandaloneAppClient$ClientEndpoint: Failed to connect to master spark:7077
[2021-12-20 11:24:04,117] {spark_submit.py:514} INFO - org.apache.spark.SparkException: Exception thrown in awaitResult:
[2021-12-20 11:24:04,119] {spark_submit.py:514} INFO - at org.apache.spark.util.ThreadUtils$.awaitResult(ThreadUtils.scala:301)
[2021-12-20 11:24:04,120] {spark_submit.py:514} INFO - at org.apache.spark.rpc.RpcTimeout.awaitResult(RpcTimeout.scala:75)
[2021-12-20 11:24:04,121] {spark_submit.py:514} INFO - at org.apache.spark.rpc.RpcEnv.setupEndpointRefByURI(RpcEnv.scala:101)
[2021-12-20 11:24:04,123] {spark_submit.py:514} INFO - at org.apache.spark.rpc.RpcEnv.setupEndpointRef(RpcEnv.scala:109)
[2021-12-20 11:24:04,124] {spark_submit.py:514} INFO - at org.apache.spark.deploy.client.StandaloneAppClient$ClientEndpoint$$anon$1.run(StandaloneAppClient.scala:107)
[2021-12-20 11:24:04,125] {spark_submit.py:514} INFO - at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
[2021-12-20 11:24:04,126] {spark_submit.py:514} INFO - at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
[2021-12-20 11:24:04,127] {spark_submit.py:514} INFO - at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
[2021-12-20 11:24:04,128] {spark_submit.py:514} INFO - at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
[2021-12-20 11:24:04,130] {spark_submit.py:514} INFO - at java.base/java.lang.Thread.run(Thread.java:829)
[2021-12-20 11:24:04,131] {spark_submit.py:514} INFO - Caused by: java.io.IOException: Failed to connect to spark:7077
[2021-12-20 11:24:04,132] {spark_submit.py:514} INFO - at org.apache.spark.network.client.TransportClientFactory.createClient(TransportClientFactory.java:288)
[2021-12-20 11:24:04,133] {spark_submit.py:514} INFO - at org.apache.spark.network.client.TransportClientFactory.createClient(TransportClientFactory.java:218)
[2021-12-20 11:24:04,134] {spark_submit.py:514} INFO - at org.apache.spark.network.client.TransportClientFactory.createClient(TransportClientFactory.java:230)
[2021-12-20 11:24:04,135] {spark_submit.py:514} INFO - at org.apache.spark.rpc.netty.NettyRpcEnv.createClient(NettyRpcEnv.scala:204)
[2021-12-20 11:24:04,136] {spark_submit.py:514} INFO - at org.apache.spark.rpc.netty.Outbox$$anon$1.call(Outbox.scala:202)
[2021-12-20 11:24:04,138] {spark_submit.py:514} INFO - at org.apache.spark.rpc.netty.Outbox$$anon$1.call(Outbox.scala:198)
[2021-12-20 11:24:04,140] {spark_submit.py:514} INFO - ... 4 more
[2021-12-20 11:24:04,141] {spark_submit.py:514} INFO - Caused by: java.net.UnknownHostException: spark
[2021-12-20 11:24:04,142] {spark_submit.py:514} INFO - at java.base/java.net.InetAddress$CachedAddresses.get(InetAddress.java:797)
[2021-12-20 11:24:04,143] {spark_submit.py:514} INFO - at java.base/java.net.InetAddress.getAllByName0(InetAddress.java:1509)
[2021-12-20 11:24:04,144] {spark_submit.py:514} INFO - at java.base/java.net.InetAddress.getAllByName(InetAddress.java:1368)
[2021-12-20 11:24:04,145] {spark_submit.py:514} INFO - at java.base/java.net.InetAddress.getAllByName(InetAddress.java:1302)
[2021-12-20 11:24:04,146] {spark_submit.py:514} INFO - at java.base/java.net.InetAddress.getByName(InetAddress.java:1252)
[2021-12-20 11:24:04,147] {spark_submit.py:514} INFO - at io.netty.util.internal.SocketUtils$8.run(SocketUtils.java:156)
[2021-12-20 11:24:04,148] {spark_submit.py:514} INFO - at io.netty.util.internal.SocketUtils$8.run(SocketUtils.java:153)
[2021-12-20 11:24:04,150] {spark_submit.py:514} INFO - at java.base/java.security.AccessController.doPrivileged(Native Method)
[2021-12-20 11:24:04,151] {spark_submit.py:514} INFO - at io.netty.util.internal.SocketUtils.addressByName(SocketUtils.java:153)
[2021-12-20 11:24:04,152] {spark_submit.py:514} INFO - at io.netty.resolver.DefaultNameResolver.doResolve(DefaultNameResolver.java:41)
[2021-12-20 11:24:04,154] {spark_submit.py:514} INFO - at io.netty.resolver.SimpleNameResolver.resolve(SimpleNameResolver.java:61)
[2021-12-20 11:24:04,155] {spark_submit.py:514} INFO - at io.netty.resolver.SimpleNameResolver.resolve(SimpleNameResolver.java:53)
[2021-12-20 11:24:04,156] {spark_submit.py:514} INFO - at io.netty.resolver.InetSocketAddressResolver.doResolve(InetSocketAddressResolver.java:55)
[2021-12-20 11:24:04,158] {spark_submit.py:514} INFO - at io.netty.resolver.InetSocketAddressResolver.doResolve(InetSocketAddressResolver.java:31)
[2021-12-20 11:24:04,159] {spark_submit.py:514} INFO - at io.netty.resolver.AbstractAddressResolver.resolve(AbstractAddressResolver.java:106)
[2021-12-20 11:24:04,160] {spark_submit.py:514} INFO - at io.netty.bootstrap.Bootstrap.doResolveAndConnect0(Bootstrap.java:206)
[2021-12-20 11:24:04,161] {spark_submit.py:514} INFO - at io.netty.bootstrap.Bootstrap.access$000(Bootstrap.java:46)
[2021-12-20 11:24:04,162] {spark_submit.py:514} INFO - at io.netty.bootstrap.Bootstrap$1.operationComplete(Bootstrap.java:180)
[2021-12-20 11:24:04,163] {spark_submit.py:514} INFO - at io.netty.bootstrap.Bootstrap$1.operationComplete(Bootstrap.java:166)
[2021-12-20 11:24:04,164] {spark_submit.py:514} INFO - at io.netty.util.concurrent.DefaultPromise.notifyListener0(DefaultPromise.java:578)
[2021-12-20 11:24:04,165] {spark_submit.py:514} INFO - at io.netty.util.concurrent.DefaultPromise.notifyListenersNow(DefaultPromise.java:552)
[2021-12-20 11:24:04,166] {spark_submit.py:514} INFO - at io.netty.util.concurrent.DefaultPromise.notifyListeners(DefaultPromise.java:491)
[2021-12-20 11:24:04,167] {spark_submit.py:514} INFO - at io.netty.util.concurrent.DefaultPromise.setValue0(DefaultPromise.java:616)
[2021-12-20 11:24:04,168] {spark_submit.py:514} INFO - at io.netty.util.concurrent.DefaultPromise.setSuccess0(DefaultPromise.java:605)
[2021-12-20 11:24:04,171] {spark_submit.py:514} INFO - at io.netty.util.concurrent.DefaultPromise.trySuccess(DefaultPromise.java:104)
[2021-12-20 11:24:04,172] {spark_submit.py:514} INFO - at io.netty.channel.DefaultChannelPromise.trySuccess(DefaultChannelPromise.java:84)
[2021-12-20 11:24:04,173] {spark_submit.py:514} INFO - at io.netty.channel.AbstractChannel$AbstractUnsafe.safeSetSuccess(AbstractChannel.java:1008)
[2021-12-20 11:24:04,174] {spark_submit.py:514} INFO - at io.netty.channel.AbstractChannel$AbstractUnsafe.register0(AbstractChannel.java:516)
[2021-12-20 11:24:04,176] {spark_submit.py:514} INFO - at io.netty.channel.AbstractChannel$AbstractUnsafe.access$200(AbstractChannel.java:429)
[2021-12-20 11:24:04,177] {spark_submit.py:514} INFO - at io.netty.channel.AbstractChannel$AbstractUnsafe$1.run(AbstractChannel.java:486)
[2021-12-20 11:24:04,178] {spark_submit.py:514} INFO - at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:164)
[2021-12-20 11:24:04,179] {spark_submit.py:514} INFO - at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:469)
[2021-12-20 11:24:04,180] {spark_submit.py:514} INFO - at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:500)
[2021-12-20 11:24:04,181] {spark_submit.py:514} INFO - at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:986)
[2021-12-20 11:24:04,182] {spark_submit.py:514} INFO - at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
[2021-12-20 11:24:04,184] {spark_submit.py:514} INFO - at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
[2021-12-20 11:24:04,185] {spark_submit.py:514} INFO - ... 1 more
[2021-12-20 11:24:23,840] {spark_submit.py:514} INFO - 21/12/20 11:24:23 INFO StandaloneAppClient$ClientEndpoint: Connecting to master spark://spark:7077...
[2021-12-20 11:24:23,862] {spark_submit.py:514} INFO - 21/12/20 11:24:23 WARN StandaloneAppClient$ClientEndpoint: Failed to connect to master spark:7077
[2021-12-20 11:24:23,863] {spark_submit.py:514} INFO - org.apache.spark.SparkException: Exception thrown in awaitResult:
[2021-12-20 11:24:23,865] {spark_submit.py:514} INFO - at org.apache.spark.util.ThreadUtils$.awaitResult(ThreadUtils.scala:301)
[2021-12-20 11:24:23,866] {spark_submit.py:514} INFO - at org.apache.spark.rpc.RpcTimeout.awaitResult(RpcTimeout.scala:75)
[2021-12-20 11:24:23,868] {spark_submit.py:514} INFO - at org.apache.spark.rpc.RpcEnv.setupEndpointRefByURI(RpcEnv.scala:101)
[2021-12-20 11:24:23,870] {spark_submit.py:514} INFO - at org.apache.spark.rpc.RpcEnv.setupEndpointRef(RpcEnv.scala:109)
[2021-12-20 11:24:23,871] {spark_submit.py:514} INFO - at org.apache.spark.deploy.client.StandaloneAppClient$ClientEndpoint$$anon$1.run(StandaloneAppClient.scala:107)
[2021-12-20 11:24:23,875] {spark_submit.py:514} INFO - at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
[2021-12-20 11:24:23,876] {spark_submit.py:514} INFO - at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
[2021-12-20 11:24:23,878] {spark_submit.py:514} INFO - at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
[2021-12-20 11:24:23,879] {spark_submit.py:514} INFO - at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
[2021-12-20 11:24:23,880] {spark_submit.py:514} INFO - at java.base/java.lang.Thread.run(Thread.java:829)
[2021-12-20 11:24:23,881] {spark_submit.py:514} INFO - Caused by: java.io.IOException: Failed to connect to spark:7077
[2021-12-20 11:24:23,882] {spark_submit.py:514} INFO - at org.apache.spark.network.client.TransportClientFactory.createClient(TransportClientFactory.java:288)
[2021-12-20 11:24:23,883] {spark_submit.py:514} INFO - at org.apache.spark.network.client.TransportClientFactory.createClient(TransportClientFactory.java:218)
[2021-12-20 11:24:23,884] {spark_submit.py:514} INFO - at org.apache.spark.network.client.TransportClientFactory.createClient(TransportClientFactory.java:230)
[2021-12-20 11:24:23,885] {spark_submit.py:514} INFO - at org.apache.spark.rpc.netty.NettyRpcEnv.createClient(NettyRpcEnv.scala:204)
[2021-12-20 11:24:23,887] {spark_submit.py:514} INFO - at org.apache.spark.rpc.netty.Outbox$$anon$1.call(Outbox.scala:202)
[2021-12-20 11:24:23,888] {spark_submit.py:514} INFO - at org.apache.spark.rpc.netty.Outbox$$anon$1.call(Outbox.scala:198)
[2021-12-20 11:24:23,889] {spark_submit.py:514} INFO - ... 4 more
[2021-12-20 11:24:23,890] {spark_submit.py:514} INFO - Caused by: java.net.UnknownHostException: spark
[2021-12-20 11:24:23,892] {spark_submit.py:514} INFO - at java.base/java.net.InetAddress$CachedAddresses.get(InetAddress.java:797)
[2021-12-20 11:24:23,894] {spark_submit.py:514} INFO - at java.base/java.net.InetAddress.getAllByName0(InetAddress.java:1509)
[2021-12-20 11:24:23,895] {spark_submit.py:514} INFO - at java.base/java.net.InetAddress.getAllByName(InetAddress.java:1368)
[2021-12-20 11:24:23,897] {spark_submit.py:514} INFO - at java.base/java.net.InetAddress.getAllByName(InetAddress.java:1302)
[2021-12-20 11:24:23,898] {spark_submit.py:514} INFO - at java.base/java.net.InetAddress.getByName(InetAddress.java:1252)
[2021-12-20 11:24:23,900] {spark_submit.py:514} INFO - at io.netty.util.internal.SocketUtils$8.run(SocketUtils.java:156)
[2021-12-20 11:24:23,901] {spark_submit.py:514} INFO - at io.netty.util.internal.SocketUtils$8.run(SocketUtils.java:153)
[2021-12-20 11:24:23,903] {spark_submit.py:514} INFO - at java.base/java.security.AccessController.doPrivileged(Native Method)
[2021-12-20 11:24:23,904] {spark_submit.py:514} INFO - at io.netty.util.internal.SocketUtils.addressByName(SocketUtils.java:153)
[2021-12-20 11:24:23,905] {spark_submit.py:514} INFO - at io.netty.resolver.DefaultNameResolver.doResolve(DefaultNameResolver.java:41)
[2021-12-20 11:24:23,907] {spark_submit.py:514} INFO - at io.netty.resolver.SimpleNameResolver.resolve(SimpleNameResolver.java:61)
[2021-12-20 11:24:23,908] {spark_submit.py:514} INFO - at io.netty.resolver.SimpleNameResolver.resolve(SimpleNameResolver.java:53)
[2021-12-20 11:24:23,910] {spark_submit.py:514} INFO - at io.netty.resolver.InetSocketAddressResolver.doResolve(InetSocketAddressResolver.java:55)
[2021-12-20 11:24:23,913] {spark_submit.py:514} INFO - at io.netty.resolver.InetSocketAddressResolver.doResolve(InetSocketAddressResolver.java:31)
[2021-12-20 11:24:23,914] {spark_submit.py:514} INFO - at io.netty.resolver.AbstractAddressResolver.resolve(AbstractAddressResolver.java:106)
[2021-12-20 11:24:23,915] {spark_submit.py:514} INFO - at io.netty.bootstrap.Bootstrap.doResolveAndConnect0(Bootstrap.java:206)
[2021-12-20 11:24:23,916] {spark_submit.py:514} INFO - at io.netty.bootstrap.Bootstrap.access$000(Bootstrap.java:46)
[2021-12-20 11:24:23,918] {spark_submit.py:514} INFO - at io.netty.bootstrap.Bootstrap$1.operationComplete(Bootstrap.java:180)
[2021-12-20 11:24:23,919] {spark_submit.py:514} INFO - at io.netty.bootstrap.Bootstrap$1.operationComplete(Bootstrap.java:166)
[2021-12-20 11:24:23,920] {spark_submit.py:514} INFO - at io.netty.util.concurrent.DefaultPromise.notifyListener0(DefaultPromise.java:578)
[2021-12-20 11:24:23,922] {spark_submit.py:514} INFO - at io.netty.util.concurrent.DefaultPromise.notifyListenersNow(DefaultPromise.java:552)
[2021-12-20 11:24:23,923] {spark_submit.py:514} INFO - at io.netty.util.concurrent.DefaultPromise.notifyListeners(DefaultPromise.java:491)
[2021-12-20 11:24:23,925] {spark_submit.py:514} INFO - at io.netty.util.concurrent.DefaultPromise.setValue0(DefaultPromise.java:616)
[2021-12-20 11:24:23,926] {spark_submit.py:514} INFO - at io.netty.util.concurrent.DefaultPromise.setSuccess0(DefaultPromise.java:605)
[2021-12-20 11:24:23,928] {spark_submit.py:514} INFO - at io.netty.util.concurrent.DefaultPromise.trySuccess(DefaultPromise.java:104)
[2021-12-20 11:24:23,930] {spark_submit.py:514} INFO - at io.netty.channel.DefaultChannelPromise.trySuccess(DefaultChannelPromise.java:84)
[2021-12-20 11:24:23,932] {spark_submit.py:514} INFO - at io.netty.channel.AbstractChannel$AbstractUnsafe.safeSetSuccess(AbstractChannel.java:1008)
[2021-12-20 11:24:23,933] {spark_submit.py:514} INFO - at io.netty.channel.AbstractChannel$AbstractUnsafe.register0(AbstractChannel.java:516)
[2021-12-20 11:24:23,935] {spark_submit.py:514} INFO - at io.netty.channel.AbstractChannel$AbstractUnsafe.access$200(AbstractChannel.java:429)
[2021-12-20 11:24:23,938] {spark_submit.py:514} INFO - at io.netty.channel.AbstractChannel$AbstractUnsafe$1.run(AbstractChannel.java:486)
[2021-12-20 11:24:23,939] {spark_submit.py:514} INFO - at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:164)
[2021-12-20 11:24:23,940] {spark_submit.py:514} INFO - at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:469)
[2021-12-20 11:24:23,941] {spark_submit.py:514} INFO - at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:500)
[2021-12-20 11:24:23,942] {spark_submit.py:514} INFO - at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:986)
[2021-12-20 11:24:23,943] {spark_submit.py:514} INFO - at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
[2021-12-20 11:24:23,944] {spark_submit.py:514} INFO - at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
[2021-12-20 11:24:23,945] {spark_submit.py:514} INFO - ... 1 more
[2021-12-20 11:24:43,952] {spark_submit.py:514} INFO - 21/12/20 11:24:43 INFO StandaloneAppClient$ClientEndpoint: Connecting to master spark://spark:7077...
[2021-12-20 11:24:45,696] {spark_submit.py:514} INFO - 21/12/20 11:24:45 WARN StandaloneAppClient$ClientEndpoint: Failed to connect to master spark:7077
[2021-12-20 11:24:45,756] {spark_submit.py:514} INFO - org.apache.spark.SparkException: Exception thrown in awaitResult:
[2021-12-20 11:24:45,772] {spark_submit.py:514} INFO - at org.apache.spark.util.ThreadUtils$.awaitResult(ThreadUtils.scala:301)
[2021-12-20 11:24:45,781] {spark_submit.py:514} INFO - at org.apache.spark.rpc.RpcTimeout.awaitResult(RpcTimeout.scala:75)
[2021-12-20 11:24:45,787] {spark_submit.py:514} INFO - at org.apache.spark.rpc.RpcEnv.setupEndpointRefByURI(RpcEnv.scala:101)
[2021-12-20 11:24:45,815] {spark_submit.py:514} INFO - at org.apache.spark.rpc.RpcEnv.setupEndpointRef(RpcEnv.scala:109)
[2021-12-20 11:24:45,818] {spark_submit.py:514} INFO - at org.apache.spark.deploy.client.StandaloneAppClient$ClientEndpoint$$anon$1.run(StandaloneAppClient.scala:107)
[2021-12-20 11:24:45,850] {spark_submit.py:514} INFO - at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
[2021-12-20 11:24:45,984] {spark_submit.py:514} INFO - at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
[2021-12-20 11:24:46,002] {spark_submit.py:514} INFO - at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
[2021-12-20 11:24:46,011] {spark_submit.py:514} INFO - at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
[2021-12-20 11:24:46,048] {spark_submit.py:514} INFO - at java.base/java.lang.Thread.run(Thread.java:829)
[2021-12-20 11:24:46,055] {spark_submit.py:514} INFO - Caused by: java.io.IOException: Failed to connect to spark:7077
[2021-12-20 11:24:46,106] {spark_submit.py:514} INFO - at org.apache.spark.network.client.TransportClientFactory.createClient(TransportClientFactory.java:288)
[2021-12-20 11:24:46,131] {spark_submit.py:514} INFO - at org.apache.spark.network.client.TransportClientFactory.createClient(TransportClientFactory.java:218)
[2021-12-20 11:24:46,168] {spark_submit.py:514} INFO - at org.apache.spark.network.client.TransportClientFactory.createClient(TransportClientFactory.java:230)
[2021-12-20 11:24:46,249] {spark_submit.py:514} INFO - at org.apache.spark.rpc.netty.NettyRpcEnv.createClient(NettyRpcEnv.scala:204)
[2021-12-20 11:24:46,265] {spark_submit.py:514} INFO - at org.apache.spark.rpc.netty.Outbox$$anon$1.call(Outbox.scala:202)
[2021-12-20 11:24:46,284] {spark_submit.py:514} INFO - at org.apache.spark.rpc.netty.Outbox$$anon$1.call(Outbox.scala:198)
[2021-12-20 11:24:46,302] {spark_submit.py:514} INFO - ... 4 more
[2021-12-20 11:24:46,312] {spark_submit.py:514} INFO - Caused by: java.net.UnknownHostException: spark
[2021-12-20 11:24:46,317] {spark_submit.py:514} INFO - at java.base/java.net.InetAddress$CachedAddresses.get(InetAddress.java:797)
[2021-12-20 11:24:46,323] {spark_submit.py:514} INFO - at java.base/java.net.InetAddress.getAllByName0(InetAddress.java:1509)
[2021-12-20 11:24:46,353] {spark_submit.py:514} INFO - at java.base/java.net.InetAddress.getAllByName(InetAddress.java:1368)
[2021-12-20 11:24:46,387] {spark_submit.py:514} INFO - at java.base/java.net.InetAddress.getAllByName(InetAddress.java:1302)
[2021-12-20 11:24:46,437] {spark_submit.py:514} INFO - at java.base/java.net.InetAddress.getByName(InetAddress.java:1252)
[2021-12-20 11:24:46,464] {spark_submit.py:514} INFO - at io.netty.util.internal.SocketUtils$8.run(SocketUtils.java:156)
[2021-12-20 11:24:46,481] {spark_submit.py:514} INFO - at io.netty.util.internal.SocketUtils$8.run(SocketUtils.java:153)
[2021-12-20 11:24:46,545] {spark_submit.py:514} INFO - at java.base/java.security.AccessController.doPrivileged(Native Method)
[2021-12-20 11:24:46,560] {spark_submit.py:514} INFO - at io.netty.util.internal.SocketUtils.addressByName(SocketUtils.java:153)
[2021-12-20 11:24:46,598] {spark_submit.py:514} INFO - at io.netty.resolver.DefaultNameResolver.doResolve(DefaultNameResolver.java:41)
[2021-12-20 11:24:46,618] {spark_submit.py:514} INFO - at io.netty.resolver.SimpleNameResolver.resolve(SimpleNameResolver.java:61)
[2021-12-20 11:24:46,628] {spark_submit.py:514} INFO - at io.netty.resolver.SimpleNameResolver.resolve(SimpleNameResolver.java:53)
[2021-12-20 11:24:46,665] {spark_submit.py:514} INFO - at io.netty.resolver.InetSocketAddressResolver.doResolve(InetSocketAddressResolver.java:55)
[2021-12-20 11:24:46,681] {spark_submit.py:514} INFO - at io.netty.resolver.InetSocketAddressResolver.doResolve(InetSocketAddressResolver.java:31)
[2021-12-20 11:24:46,707] {spark_submit.py:514} INFO - at io.netty.resolver.AbstractAddressResolver.resolve(AbstractAddressResolver.java:106)
[2021-12-20 11:24:46,758] {spark_submit.py:514} INFO - at io.netty.bootstrap.Bootstrap.doResolveAndConnect0(Bootstrap.java:206)
[2021-12-20 11:24:46,771] {spark_submit.py:514} INFO - at io.netty.bootstrap.Bootstrap.access$000(Bootstrap.java:46)
[2021-12-20 11:24:46,775] {spark_submit.py:514} INFO - at io.netty.bootstrap.Bootstrap$1.operationComplete(Bootstrap.java:180)
[2021-12-20 11:24:46,785] {spark_submit.py:514} INFO - at io.netty.bootstrap.Bootstrap$1.operationComplete(Bootstrap.java:166)
[2021-12-20 11:24:46,801] {spark_submit.py:514} INFO - at io.netty.util.concurrent.DefaultPromise.notifyListener0(DefaultPromise.java:578)
[2021-12-20 11:24:46,847] {spark_submit.py:514} INFO - at io.netty.util.concurrent.DefaultPromise.notifyListenersNow(DefaultPromise.java:552)
[2021-12-20 11:24:46,863] {spark_submit.py:514} INFO - at io.netty.util.concurrent.DefaultPromise.notifyListeners(DefaultPromise.java:491)
[2021-12-20 11:24:46,884] {spark_submit.py:514} INFO - at io.netty.util.concurrent.DefaultPromise.setValue0(DefaultPromise.java:616)
[2021-12-20 11:24:46,959] {spark_submit.py:514} INFO - at io.netty.util.concurrent.DefaultPromise.setSuccess0(DefaultPromise.java:605)
[2021-12-20 11:24:46,999] {spark_submit.py:514} INFO - at io.netty.util.concurrent.DefaultPromise.trySuccess(DefaultPromise.java:104)
[2021-12-20 11:24:47,340] {spark_submit.py:514} INFO - at io.netty.channel.DefaultChannelPromise.trySuccess(DefaultChannelPromise.java:84)
[2021-12-20 11:24:47,352] {spark_submit.py:514} INFO - at io.netty.channel.AbstractChannel$AbstractUnsafe.safeSetSuccess(AbstractChannel.java:1008)
[2021-12-20 11:24:47,366] {spark_submit.py:514} INFO - at io.netty.channel.AbstractChannel$AbstractUnsafe.register0(AbstractChannel.java:516)
[2021-12-20 11:24:47,378] {spark_submit.py:514} INFO - at io.netty.channel.AbstractChannel$AbstractUnsafe.access$200(AbstractChannel.java:429)
[2021-12-20 11:24:47,431] {spark_submit.py:514} INFO - at io.netty.channel.AbstractChannel$AbstractUnsafe$1.run(AbstractChannel.java:486)
[2021-12-20 11:24:47,602] {spark_submit.py:514} INFO - at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:164)
[2021-12-20 11:24:47,716] {spark_submit.py:514} INFO - at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:469)
[2021-12-20 11:24:47,728] {spark_submit.py:514} INFO - at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:500)
[2021-12-20 11:24:47,741] {spark_submit.py:514} INFO - at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:986)
[2021-12-20 11:24:47,749] {spark_submit.py:514} INFO - at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
[2021-12-20 11:24:47,767] {spark_submit.py:514} INFO - at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
[2021-12-20 11:24:47,844] {spark_submit.py:514} INFO - ... 1 more
[2021-12-20 11:25:03,943] {spark_submit.py:514} INFO - 21/12/20 11:25:03 ERROR StandaloneSchedulerBackend: Application has been killed. Reason: All masters are unresponsive! Giving up.
[2021-12-20 11:25:03,959] {spark_submit.py:514} INFO - 21/12/20 11:25:03 WARN StandaloneSchedulerBackend: Application ID is not initialized yet.
[2021-12-20 11:25:04,156] {spark_submit.py:514} INFO - 21/12/20 11:25:04 INFO Utils: Successfully started service 'org.apache.spark.network.netty.NettyBlockTransferService' on port 32863.
[2021-12-20 11:25:04,171] {spark_submit.py:514} INFO - 21/12/20 11:25:04 INFO NettyBlockTransferService: Server created on a35fe600e898:32863
[2021-12-20 11:25:04,184] {spark_submit.py:514} INFO - 21/12/20 11:25:04 INFO BlockManager: Using org.apache.spark.storage.RandomBlockReplicationPolicy for block replication policy
[2021-12-20 11:25:04,284] {spark_submit.py:514} INFO - 21/12/20 11:25:04 INFO BlockManagerMaster: Registering BlockManager BlockManagerId(driver, a35fe600e898, 32863, None)
[2021-12-20 11:25:04,530] {spark_submit.py:514} INFO - 21/12/20 11:25:04 INFO BlockManagerMasterEndpoint: Registering block manager a35fe600e898:32863 with 434.4 MiB RAM, BlockManagerId(driver, a35fe600e898, 32863, None)
[2021-12-20 11:25:04,655] {spark_submit.py:514} INFO - 21/12/20 11:25:04 INFO SparkUI: Stopped Spark web UI at http://a35fe600e898:4047
[2021-12-20 11:25:04,789] {spark_submit.py:514} INFO - 21/12/20 11:25:04 INFO StandaloneSchedulerBackend: Shutting down all executors
[2021-12-20 11:25:05,086] {spark_submit.py:514} INFO - 21/12/20 11:25:04 INFO BlockManagerMaster: Registered BlockManager BlockManagerId(driver, a35fe600e898, 32863, None)
[2021-12-20 11:25:05,166] {spark_submit.py:514} INFO - 21/12/20 11:25:04 INFO BlockManager: Initialized BlockManager: BlockManagerId(driver, a35fe600e898, 32863, None)
[2021-12-20 11:25:05,191] {spark_submit.py:514} INFO - 21/12/20 11:25:04 INFO CoarseGrainedSchedulerBackend$DriverEndpoint: Asking each executor to shut down
[2021-12-20 11:25:05,203] {spark_submit.py:514} INFO - 21/12/20 11:25:04 WARN StandaloneAppClient$ClientEndpoint: Drop UnregisterApplication(null) because has not yet connected to master
[2021-12-20 11:25:05,275] {spark_submit.py:514} INFO - 21/12/20 11:25:05 INFO MapOutputTrackerMasterEndpoint: MapOutputTrackerMasterEndpoint stopped!
[2021-12-20 11:25:05,519] {spark_submit.py:514} INFO - 21/12/20 11:25:05 INFO MemoryStore: MemoryStore cleared
[2021-12-20 11:25:05,523] {spark_submit.py:514} INFO - 21/12/20 11:25:05 INFO BlockManager: BlockManager stopped
[2021-12-20 11:25:05,562] {spark_submit.py:514} INFO - 21/12/20 11:25:05 INFO BlockManagerMaster: BlockManagerMaster stopped
[2021-12-20 11:25:05,572] {spark_submit.py:514} INFO - 21/12/20 11:25:05 INFO OutputCommitCoordinator$OutputCommitCoordinatorEndpoint: OutputCommitCoordinator stopped!
[2021-12-20 11:25:05,686] {spark_submit.py:514} INFO - 21/12/20 11:25:05 INFO SparkContext: Successfully stopped SparkContext
[2021-12-20 11:25:05,978] {spark_submit.py:514} INFO - 21/12/20 11:25:05 ERROR SparkContext: Error initializing SparkContext.
[2021-12-20 11:25:05,979] {spark_submit.py:514} INFO - java.lang.IllegalArgumentException: requirement failed: Can only call getServletHandlers on a running MetricsSystem
[2021-12-20 11:25:05,980] {spark_submit.py:514} INFO - at scala.Predef$.require(Predef.scala:281)
[2021-12-20 11:25:05,981] {spark_submit.py:514} INFO - at org.apache.spark.metrics.MetricsSystem.getServletHandlers(MetricsSystem.scala:89)
[2021-12-20 11:25:05,982] {spark_submit.py:514} INFO - at org.apache.spark.SparkContext.<init>(SparkContext.scala:603)
[2021-12-20 11:25:05,985] {spark_submit.py:514} INFO - at org.apache.spark.api.java.JavaSparkContext.<init>(JavaSparkContext.scala:58)
[2021-12-20 11:25:05,987] {spark_submit.py:514} INFO - at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
[2021-12-20 11:25:05,989] {spark_submit.py:514} INFO - at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
[2021-12-20 11:25:05,990] {spark_submit.py:514} INFO - at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
[2021-12-20 11:25:05,992] {spark_submit.py:514} INFO - at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:490)
[2021-12-20 11:25:05,993] {spark_submit.py:514} INFO - at py4j.reflection.MethodInvoker.invoke(MethodInvoker.java:247)
[2021-12-20 11:25:05,995] {spark_submit.py:514} INFO - at py4j.reflection.ReflectionEngine.invoke(ReflectionEngine.java:357)
[2021-12-20 11:25:05,997] {spark_submit.py:514} INFO - at py4j.Gateway.invoke(Gateway.java:238)
[2021-12-20 11:25:05,998] {spark_submit.py:514} INFO - at py4j.commands.ConstructorCommand.invokeConstructor(ConstructorCommand.java:80)
[2021-12-20 11:25:05,999] {spark_submit.py:514} INFO - at py4j.commands.ConstructorCommand.execute(ConstructorCommand.java:69)
[2021-12-20 11:25:06,001] {spark_submit.py:514} INFO - at py4j.ClientServerConnection.waitForCommands(ClientServerConnection.java:182)
[2021-12-20 11:25:06,001] {spark_submit.py:514} INFO - at py4j.ClientServerConnection.run(ClientServerConnection.java:106)
[2021-12-20 11:25:06,004] {spark_submit.py:514} INFO - at java.base/java.lang.Thread.run(Thread.java:829)
[2021-12-20 11:25:06,005] {spark_submit.py:514} INFO - 21/12/20 11:25:05 INFO SparkContext: SparkContext already stopped.
[2021-12-20 11:25:06,006] {spark_submit.py:514} INFO - Traceback (most recent call last):
[2021-12-20 11:25:06,007] {spark_submit.py:514} INFO - File "/opt/***/jobs/get_ads_per_county.py", line 13, in <module>
[2021-12-20 11:25:06,009] {spark_submit.py:514} INFO - .appName("Get Ads per county") \
[2021-12-20 11:25:06,010] {spark_submit.py:514} INFO - File "/home/***/.local/lib/python3.6/site-packages/pyspark/python/lib/pyspark.zip/pyspark/sql/session.py", line 228, in getOrCreate
[2021-12-20 11:25:06,011] {spark_submit.py:514} INFO - File "/home/***/.local/lib/python3.6/site-packages/pyspark/python/lib/pyspark.zip/pyspark/context.py", line 392, in getOrCreate
[2021-12-20 11:25:06,012] {spark_submit.py:514} INFO - File "/home/***/.local/lib/python3.6/site-packages/pyspark/python/lib/pyspark.zip/pyspark/context.py", line 147, in __init__
[2021-12-20 11:25:06,013] {spark_submit.py:514} INFO - File "/home/***/.local/lib/python3.6/site-packages/pyspark/python/lib/pyspark.zip/pyspark/context.py", line 209, in _do_init
[2021-12-20 11:25:06,014] {spark_submit.py:514} INFO - File "/home/***/.local/lib/python3.6/site-packages/pyspark/python/lib/pyspark.zip/pyspark/context.py", line 329, in _initialize_context
[2021-12-20 11:25:06,015] {spark_submit.py:514} INFO - File "/home/***/.local/lib/python3.6/site-packages/pyspark/python/lib/py4j-0.10.9.2-src.zip/py4j/java_gateway.py", line 1574, in __call__
[2021-12-20 11:25:06,017] {spark_submit.py:514} INFO - File "/home/***/.local/lib/python3.6/site-packages/pyspark/python/lib/py4j-0.10.9.2-src.zip/py4j/protocol.py", line 328, in get_return_value
[2021-12-20 11:25:06,019] {spark_submit.py:514} INFO - py4j.protocol.Py4JJavaError: An error occurred while calling None.org.apache.spark.api.java.JavaSparkContext.
[2021-12-20 11:25:06,020] {spark_submit.py:514} INFO - : java.lang.IllegalArgumentException: requirement failed: Can only call getServletHandlers on a running MetricsSystem
[2021-12-20 11:25:06,021] {spark_submit.py:514} INFO - at scala.Predef$.require(Predef.scala:281)
[2021-12-20 11:25:06,022] {spark_submit.py:514} INFO - at org.apache.spark.metrics.MetricsSystem.getServletHandlers(MetricsSystem.scala:89)
[2021-12-20 11:25:06,024] {spark_submit.py:514} INFO - at org.apache.spark.SparkContext.<init>(SparkContext.scala:603)
[2021-12-20 11:25:06,025] {spark_submit.py:514} INFO - at org.apache.spark.api.java.JavaSparkContext.<init>(JavaSparkContext.scala:58)
[2021-12-20 11:25:06,026] {spark_submit.py:514} INFO - at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
[2021-12-20 11:25:06,027] {spark_submit.py:514} INFO - at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
[2021-12-20 11:25:06,028] {spark_submit.py:514} INFO - at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
[2021-12-20 11:25:06,029] {spark_submit.py:514} INFO - at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:490)
[2021-12-20 11:25:06,030] {spark_submit.py:514} INFO - at py4j.reflection.MethodInvoker.invoke(MethodInvoker.java:247)
[2021-12-20 11:25:06,031] {spark_submit.py:514} INFO - at py4j.reflection.ReflectionEngine.invoke(ReflectionEngine.java:357)
[2021-12-20 11:25:06,032] {spark_submit.py:514} INFO - at py4j.Gateway.invoke(Gateway.java:238)
[2021-12-20 11:25:06,033] {spark_submit.py:514} INFO - at py4j.commands.ConstructorCommand.invokeConstructor(ConstructorCommand.java:80)
[2021-12-20 11:25:06,034] {spark_submit.py:514} INFO - at py4j.commands.ConstructorCommand.execute(ConstructorCommand.java:69)
[2021-12-20 11:25:06,035] {spark_submit.py:514} INFO - at py4j.ClientServerConnection.waitForCommands(ClientServerConnection.java:182)
[2021-12-20 11:25:06,036] {spark_submit.py:514} INFO - at py4j.ClientServerConnection.run(ClientServerConnection.java:106)
[2021-12-20 11:25:06,038] {spark_submit.py:514} INFO - at java.base/java.lang.Thread.run(Thread.java:829)
[2021-12-20 11:25:06,039] {spark_submit.py:514} INFO - 
[2021-12-20 11:25:06,316] {spark_submit.py:514} INFO - 21/12/20 11:25:06 INFO ShutdownHookManager: Shutdown hook called
[2021-12-20 11:25:06,323] {spark_submit.py:514} INFO - 21/12/20 11:25:06 INFO ShutdownHookManager: Deleting directory /tmp/spark-a550a0c0-961d-414f-ac26-d4011293a76b
[2021-12-20 11:25:06,345] {spark_submit.py:514} INFO - 21/12/20 11:25:06 INFO ShutdownHookManager: Deleting directory /tmp/spark-3627ade8-e36f-4edb-8fce-af805226164a
[2021-12-20 11:25:07,050] {taskinstance.py:1703} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 1332, in _run_raw_task
    self._execute_task_with_callbacks(context)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 1458, in _execute_task_with_callbacks
    result = self._execute_task(context, self.task)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 1514, in _execute_task
    result = execute_callable(context=context)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/providers/apache/spark/operators/spark_submit.py", line 179, in execute
    self._hook.submit(self._application)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/providers/apache/spark/hooks/spark_submit.py", line 446, in submit
    f"Cannot execute: {self._mask_cmd(spark_submit_cmd)}. Error code is: {returncode}."
airflow.exceptions.AirflowException: Cannot execute: spark-submit --master spark://spark:7077 --conf spark.master=spark://spark:7077 --name scrap data --verbose /opt/***/jobs/get_ads_per_county.py westmeath. Error code is: 1.
[2021-12-20 11:25:07,078] {taskinstance.py:1280} INFO - Marking task as UP_FOR_RETRY. dag_id=scraping_daft_westmeath, task_id=scrap_data, execution_date=20211219T110000, start_date=20211220T112247, end_date=20211220T112507
[2021-12-20 11:25:07,119] {standard_task_runner.py:91} ERROR - Failed to execute job 3445 for task scrap_data
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/task/task_runner/standard_task_runner.py", line 85, in _start_by_fork
    args.func(args, dag=self.dag)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/cli/cli_parser.py", line 48, in command
    return func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/utils/cli.py", line 92, in wrapper
    return f(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/cli/commands/task_command.py", line 292, in task_run
    _run_task_by_selected_method(args, dag, ti)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/cli/commands/task_command.py", line 107, in _run_task_by_selected_method
    _run_raw_task(args, ti)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/cli/commands/task_command.py", line 184, in _run_raw_task
    error_file=args.error_file,
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/utils/session.py", line 70, in wrapper
    return func(*args, session=session, **kwargs)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 1332, in _run_raw_task
    self._execute_task_with_callbacks(context)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 1458, in _execute_task_with_callbacks
    result = self._execute_task(context, self.task)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 1514, in _execute_task
    result = execute_callable(context=context)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/providers/apache/spark/operators/spark_submit.py", line 179, in execute
    self._hook.submit(self._application)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/providers/apache/spark/hooks/spark_submit.py", line 446, in submit
    f"Cannot execute: {self._mask_cmd(spark_submit_cmd)}. Error code is: {returncode}."
airflow.exceptions.AirflowException: Cannot execute: spark-submit --master spark://spark:7077 --conf spark.master=spark://spark:7077 --name scrap data --verbose /opt/***/jobs/get_ads_per_county.py westmeath. Error code is: 1.
[2021-12-20 11:25:07,196] {local_task_job.py:154} INFO - Task exited with return code 1
[2021-12-20 11:25:07,430] {local_task_job.py:264} INFO - 0 downstream tasks scheduled from follow-on schedule check
